# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:fine_print/animations/pause_all
scoreboard players set @s aj.give_back_item.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:fine_print/animations/give_back_item/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only