# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lid) {transformation: [-0.9962f,0f,0.0877f,0.0384f,0f,1f,0f,0.9426f,-0.0877f,0f,-0.9962f,-0.4358f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(base) {transformation: [-0.9962f,0f,-0.0877f,-0.4542f,0f,-1f,0f,0.3801f,-0.0877f,0f,0.9962f,-0.5419f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(freedom) {transformation: [-0.9962f,0f,0.0877f,0f,0f,1f,0f,0.3801f,-0.0877f,0f,-0.9962f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0","py":"0.443","pz":"0","ry":"5.029","rx":"0"},"hitbox":{"px":"0","py":"0.255","pz":"0","ry":"5.029","rx":"0"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args