# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lid) {transformation: [-1f,-0.003f,0.0001f,-0.0013f,0f,-0.0259f,-0.9997f,1.1296f,0.003f,-0.9997f,0.0259f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(base) {transformation: [-1f,0f,0.003f,-0.5015f,0f,-1f,0f,0.5671f,0.003f,0f,1f,-0.4985f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(freedom) {transformation: [-1f,0f,-0.003f,0f,0f,1f,0f,0.5671f,0.003f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0","py":"0.63","pz":"0","ry":"359.831","rx":"0"},"hitbox":{"px":"0","py":"0.442","pz":"0","ry":"359.831","rx":"0"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args