# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lid) {transformation: [-1f,-0.0031f,0.0033f,-0.002f,0f,-0.7376f,-0.6753f,1.276f,0.0045f,-0.6753f,0.7375f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(base) {transformation: [-1f,0f,0.0045f,-0.5023f,0f,-1f,0f,0.7135f,0.0045f,0f,1f,-0.4977f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(freedom) {transformation: [-1f,0f,-0.0045f,0f,0f,1f,0f,0.7135f,0.0045f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0","py":"0.776","pz":"0","ry":"359.741","rx":"0"},"hitbox":{"px":"0","py":"0.589","pz":"0","ry":"359.741","rx":"0"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args