# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lid) {transformation: [-1f,-0.0034f,0.004f,-0.0023f,0f,-0.7619f,-0.6477f,1.283f,0.0053f,-0.6477f,0.7619f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(base) {transformation: [-1f,0f,0.0053f,-0.5026f,0f,-1f,0f,0.7205f,0.0053f,0f,1f,-0.4974f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(freedom) {transformation: [-1f,0f,-0.0053f,0f,0f,1f,0f,0.7205f,0.0053f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0","py":"0.783","pz":"0","ry":"359.697","rx":"0"},"hitbox":{"px":"0","py":"0.596","pz":"0","ry":"359.697","rx":"0"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args