# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lid) {transformation: [-1f,-0.0039f,0.0043f,-0.0026f,0f,-0.7446f,-0.6675f,1.277f,0.0058f,-0.6675f,0.7446f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(base) {transformation: [-1f,0f,0.0058f,-0.5029f,0f,-1f,0f,0.7145f,0.0058f,0f,1f,-0.4971f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(freedom) {transformation: [-1f,0f,-0.0058f,0f,0f,1f,0f,0.7145f,0.0058f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0","py":"0.777","pz":"0","ry":"359.665","rx":"0"},"hitbox":{"px":"0","py":"0.59","pz":"0","ry":"359.665","rx":"0"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args