# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lid) {transformation: [-1f,-0.005f,0.0042f,-0.0028f,0f,-0.6428f,-0.766f,1.2456f,0.0065f,-0.766f,0.6428f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(base) {transformation: [-1f,0f,0.0065f,-0.5032f,0f,-1f,0f,0.6831f,0.0065f,0f,1f,-0.4968f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(freedom) {transformation: [-1f,0f,-0.0065f,0f,0f,1f,0f,0.6831f,0.0065f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0","py":"0.746","pz":"0","ry":"359.63","rx":"0"},"hitbox":{"px":"0","py":"0.558","pz":"0","ry":"359.63","rx":"0"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args