# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lid) {transformation: [-1f,-0.0044f,0.0039f,-0.0026f,0f,-0.666f,-0.746f,1.2249f,0.0059f,-0.746f,0.666f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(base) {transformation: [-1f,0f,0.0059f,-0.5029f,0f,-1f,0f,0.6624f,0.0059f,0f,1f,-0.4971f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(freedom) {transformation: [-1f,0f,-0.0059f,0f,0f,1f,0f,0.6624f,0.0059f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0","py":"0.725","pz":"0","ry":"359.665","rx":"0"},"hitbox":{"px":"0","py":"0.537","pz":"0","ry":"359.665","rx":"0"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args