# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lid) {transformation: [-1f,-0.0042f,0.0038f,-0.0025f,0f,-0.6731f,-0.7396f,1.2206f,0.0057f,-0.7396f,0.6731f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(base) {transformation: [-1f,0f,0.0057f,-0.5028f,0f,-1f,0f,0.6581f,0.0057f,0f,1f,-0.4972f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(freedom) {transformation: [-1f,0f,-0.0057f,0f,0f,1f,0f,0.6581f,0.0057f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0","py":"0.721","pz":"0","ry":"359.676","rx":"0"},"hitbox":{"px":"0","py":"0.533","pz":"0","ry":"359.676","rx":"0"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args