# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lid) {transformation: [-1f,-0.0029f,0.003f,-0.0018f,0f,-0.7207f,-0.6932f,1.1921f,0.0042f,-0.6932f,0.7207f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(base) {transformation: [-1f,0f,0.0042f,-0.5021f,0f,-1f,0f,0.6296f,0.0042f,0f,1f,-0.4979f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(freedom) {transformation: [-1f,0f,-0.0042f,0f,0f,1f,0f,0.6296f,0.0042f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0","py":"0.692","pz":"0","ry":"359.76","rx":"0"},"hitbox":{"px":"0","py":"0.505","pz":"0","ry":"359.76","rx":"0"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args