# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lid) {transformation: [-1f,-0.0014f,0.0017f,-0.001f,0f,-0.7593f,-0.6507f,1.1585f,0.0022f,-0.6507f,0.7593f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(base) {transformation: [-1f,0f,0.0022f,-0.5011f,0f,-1f,0f,0.596f,0.0022f,0f,1f,-0.4989f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(freedom) {transformation: [-1f,0f,-0.0022f,0f,0f,1f,0f,0.596f,0.0022f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0","py":"0.659","pz":"0","ry":"359.875","rx":"0"},"hitbox":{"px":"0","py":"0.471","pz":"0","ry":"359.875","rx":"0"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args