# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lid) {transformation: [-1f,-0.0008f,0.0009f,-0.0005f,0f,-0.759f,-0.6511f,1.1425f,0.0012f,-0.6511f,0.759f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(base) {transformation: [-1f,0f,0.0012f,-0.5006f,0f,-1f,0f,0.58f,0.0012f,0f,1f,-0.4994f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(freedom) {transformation: [-1f,0f,-0.0012f,0f,0f,1f,0f,0.58f,0.0012f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0","py":"0.642","pz":"0","ry":"359.934","rx":"0"},"hitbox":{"px":"0","py":"0.455","pz":"0","ry":"359.934","rx":"0"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args