# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lid) {transformation: [-1f,-0.0006f,0.0007f,-0.0004f,0f,-0.7552f,-0.6555f,1.1391f,0.0009f,-0.6555f,0.7552f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(base) {transformation: [-1f,0f,0.0009f,-0.5005f,0f,-1f,0f,0.5766f,0.0009f,0f,1f,-0.4995f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(freedom) {transformation: [-1f,0f,-0.0009f,0f,0f,1f,0f,0.5766f,0.0009f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0","py":"0.639","pz":"0","ry":"359.946","rx":"0"},"hitbox":{"px":"0","py":"0.452","pz":"0","ry":"359.946","rx":"0"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args