# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lid) {transformation: [-1f,-0.0002f,0.0002f,-0.0001f,0f,-0.7204f,-0.6936f,1.1288f,0.0003f,-0.6936f,0.7204f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(base) {transformation: [-1f,0f,0.0003f,-0.5001f,0f,-1f,0f,0.5663f,0.0003f,0f,1f,-0.4999f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(freedom) {transformation: [-1f,0f,-0.0003f,0f,0f,1f,0f,0.5663f,0.0003f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0","py":"0.629","pz":"0","ry":"359.985","rx":"0"},"hitbox":{"px":"0","py":"0.441","pz":"0","ry":"359.985","rx":"0"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args