# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.wander.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'wander', 'function_path': 'animated_java:wander/variants/sack/apply'}
execute on passengers if entity @s[tag=aj.wander.bone.sack_top] run function animated_java:wander/variants/sack/zzz/0
execute on passengers if entity @s[tag=aj.wander.bone.sack_main] run function animated_java:wander/variants/sack/zzz/1