# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function aj:fine_print/root/on_tick/select_locator_locator with storage animated_java:temp entry.data.locators.locator
function aj:fine_print/root/on_tick/select_locator_hitbox with storage animated_java:temp entry.data.locators.hitbox