# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [0.295f,0.5478f,0.825f,-1.5192f,0.9508f,-0.3973f,-0.0762f,1.8337f,0.2768f,0.7809f,-0.6175f,1.0685f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.6553f,0.0385f,0.798f,-1.2359f,0.6433f,-0.5866f,0.5566f,1.8093f,0.4737f,0.8498f,0.3481f,0.8032f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0f,0f,0f,-1.3614f,0f,0f,0f,2.1564f,0f,0f,0f,0.4399f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.6553f,0.0385f,0.798f,-1.4551f,0.6433f,-0.5866f,0.5566f,2.2303f,0.4737f,0.8498f,0.3481f,0.6326f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.6553f,0.0385f,0.798f,-1.0046f,0.6433f,-0.5866f,0.5566f,1.788f,0.4737f,0.8498f,0.3481f,0.3069f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.2187f,-0.5055f,0.8743f,-1.3113f,0.8833f,-0.5294f,-0.0852f,2.1537f,0.4896f,0.7293f,0.5442f,0.8088f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9395f,-0.0928f,0.4201f,-0.9427f,0.2536f,-0.9345f,0.3606f,1.7918f,0.3476f,0.431f,0.8724f,0.5423f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-0.6553f,0.0385f,0.798f,-1.2454f,0.6433f,-0.5866f,0.5566f,2.3509f,0.4737f,0.8498f,0.3481f,0.0546f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.6553f,0.0673f,0.7961f,-1.4005f,0.6433f,-0.5661f,0.5774f,2.3352f,0.4737f,0.8618f,0.3171f,0.1571f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.6553f,0.0673f,0.7961f,-1.2126f,0.6433f,-0.5661f,0.5774f,2.2757f,0.4737f,0.8618f,0.3171f,-0.2064f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"-1.35","py":"1.96","pz":"0.441","ry":"113.566","rx":"32.592"},"hitbox":{"px":"-1.324","py":"2.782","pz":"-0.639","ry":"111.722","rx":"33.974"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] at @s run function aj:fine_print/animations/give_back_item/zzz/frames/108_root_function