# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.4622f,0.865f,0.2719f,-0.108f,0.603f,0.0652f,0.8173f,1.7003f,0.6772f,0.5323f,-0.5421f,0.8528f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.6607f,0.764f,0.1246f,-0.0349f,-0.38f,-0.4628f,0.823f,1.9961f,0.6745f,0.4877f,0.5857f,0.6207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0f,0f,0f,-0.4915f,0f,0f,0f,2.147f,0f,0f,0f,0.4504f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.6607f,0.764f,0.1246f,-0.5279f,-0.38f,-0.4628f,0.823f,2.0509f,0.6745f,0.4877f,0.5857f,0.6485f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.6607f,0.764f,0.1246f,-0.0736f,-0.38f,-0.4628f,0.823f,2.3121f,0.6745f,0.4877f,0.5857f,0.1848f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.606f,0.3919f,0.7177f,-0.3319f,0.0879f,-0.8569f,0.5421f,2.0883f,0.8129f,0.3848f,0.4763f,0.7753f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.5617f,0.808f,0.2598f,0.0398f,-0.7594f,-0.6176f,0.2788f,2.3021f,0.379f,-0.04f,0.9437f,0.3959f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-0.6607f,0.764f,0.1246f,-0.7139f,-0.38f,-0.4628f,0.823f,2.4354f,0.6745f,0.4877f,0.5857f,0.203f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.6607f,0.768f,0.097f,-0.7473f,-0.38f,-0.4328f,0.8391f,2.2717f,0.6745f,0.5086f,0.5677f,0.2797f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.6607f,0.768f,0.097f,-0.7328f,-0.38f,-0.4328f,0.8391f,2.4987f,0.6745f,0.5086f,0.5677f,-0.0582f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"-0.337","py":"2.067","pz":"0.365","ry":"167.988","rx":"53.959"},"hitbox":{"px":"-1.327","py":"2.753","pz":"-0.218","ry":"170.309","rx":"55.537"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args