# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.3349f,0.934f,0.1671f,0.4758f,0.6364f,0.0897f,0.7742f,1.6514f,0.7037f,0.3633f,-0.6206f,0.7256f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.5244f,0.8302f,0.2194f,0.5054f,-0.3327f,-0.4334f,0.8449f,1.9296f,0.7916f,0.3678f,0.5004f,0.4705f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0f,0f,0f,0.1292f,0f,0f,0f,2.1339f,0f,0f,0f,0.2272f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.5244f,0.8302f,0.2194f,0.0302f,-0.3327f,-0.4334f,0.8449f,1.9882f,0.7916f,0.3678f,0.5004f,0.58f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.5244f,0.8302f,0.2194f,0.3907f,-0.3327f,-0.4334f,0.8449f,2.2169f,0.7916f,0.3678f,0.5004f,0.0357f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.4491f,0.4518f,0.7788f,0.2428f,0.1366f,-0.826f,0.558f,2.0312f,0.89f,0.3548f,0.3073f,0.6669f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.4776f,0.7821f,0.4154f,0.5377f,-0.7247f,-0.6165f,0.3274f,2.2184f,0.509f,-0.1438f,0.8559f,0.2216f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-0.5244f,0.8302f,0.2194f,-0.2298f,-0.3327f,-0.4334f,0.8449f,2.3434f,0.7916f,0.3678f,0.5004f,0.1574f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.5244f,0.8376f,0.1893f,-0.2483f,-0.3327f,-0.4026f,0.86f,2.1864f,0.7916f,0.3856f,0.4868f,0.247f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.5244f,0.8376f,0.1893f,-0.2938f,-0.3327f,-0.4026f,0.86f,2.391f,0.7916f,0.3856f,0.4868f,-0.0968f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.167","py":"1.987","pz":"0.27","ry":"156.327","rx":"57.107"},"hitbox":{"px":"-0.901","py":"2.636","pz":"-0.164","ry":"158.755","rx":"58.726"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args