# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [0.0975f,0.667f,0.1894f,0.3221f,0.5346f,-0.1941f,0.4084f,0.6808f,0.4415f,0.0877f,-0.5363f,0.4189f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.2591f,0.4653f,0.4545f,0.3653f,-0.0179f,-0.4941f,0.4958f,0.8347f,0.6502f,0.1719f,0.1948f,0.2094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0f,0f,0f,0.1419f,0f,0f,0f,1.0596f,0f,0f,0f,0.0794f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.2591f,0.4653f,0.4545f,0.1098f,-0.0179f,-0.4941f,0.4958f,1.0144f,0.6502f,0.1719f,0.1948f,0.3482f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.2591f,0.4653f,0.4545f,0.288f,-0.0179f,-0.4941f,0.4958f,1.0267f,0.6502f,0.1719f,0.1948f,-0.0989f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.0696f,0.1263f,0.6852f,0.2685f,0.2617f,-0.6334f,0.1433f,0.9847f,0.6457f,0.2704f,0.0158f,0.3682f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.3884f,0.2895f,0.5056f,0.4142f,-0.2933f,-0.6222f,0.131f,0.9948f,0.5034f,-0.1391f,0.4664f,0.0024f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-0.2591f,0.4653f,0.4545f,-0.0364f,-0.0179f,-0.4941f,0.4958f,1.2918f,0.6502f,0.1719f,0.1948f,0.0619f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.2591f,0.4815f,0.4374f,-0.0723f,-0.0179f,-0.4759f,0.5133f,1.2027f,0.6502f,0.1788f,0.1884f,0.1441f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.2591f,0.4815f,0.4374f,-0.1117f,-0.0179f,-0.4759f,0.5133f,1.3272f,0.6502f,0.1788f,0.1884f,-0.1038f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.134","py":"0.958","pz":"0.121","ry":"113.196","rx":"45.075"},"hitbox":{"px":"-0.432","py":"1.653","pz":"-0.086","ry":"113.305","rx":"47.144"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args