# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [0.1591f,0.4473f,0.1472f,0.1416f,0.364f,-0.2154f,0.2611f,0.4022f,0.2988f,0.0242f,-0.3965f,0.2651f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.1423f,0.2763f,0.3879f,0.177f,0.0209f,-0.4008f,0.2931f,0.5039f,0.4758f,0.1002f,0.1031f,0.1122f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0f,0f,0f,0.0133f,0f,0f,0f,0.6915f,0f,0f,0f,0.1199f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.1423f,0.2763f,0.3879f,0.029f,0.0209f,-0.4008f,0.2931f,0.6607f,0.4758f,0.1002f,0.1031f,0.2233f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.1423f,0.2763f,0.3879f,0.1268f,0.0209f,-0.4008f,0.2931f,0.6464f,0.4758f,0.1002f,0.1031f,-0.1038f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [0.0228f,0.0295f,0.4956f,0.1373f,0.1938f,-0.4573f,0.0183f,0.621f,0.4571f,0.1924f,-0.0325f,0.2282f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.2743f,0.1191f,0.397f,0.2173f,-0.1569f,-0.4705f,0.0328f,0.6093f,0.3837f,-0.1072f,0.2972f,-0.0394f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-0.1423f,0.2763f,0.3879f,-0.0577f,0.0209f,-0.4008f,0.2931f,0.8713f,0.4758f,0.1002f,0.1031f,0.0259f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.1423f,0.2901f,0.3777f,-0.0883f,0.0209f,-0.39f,0.3074f,0.8135f,0.4758f,0.1039f,0.0994f,0.0874f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.1423f,0.2901f,0.3777f,-0.1163f,0.0209f,-0.39f,0.3074f,0.9045f,0.4758f,0.1039f,0.0994f,-0.0872f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0.025","py":"0.618","pz":"0.062","ry":"104.885","rx":"36.141"},"hitbox":{"px":"-0.3","py":"1.171","pz":"-0.06","ry":"104.748","rx":"38.208"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args