# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [0.1396f,0.2426f,0.0916f,0.0249f,0.1963f,-0.1669f,0.1428f,0.2011f,0.1695f,-0.0066f,-0.2408f,0.1353f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.0595f,0.1294f,0.2578f,0.0478f,0.0213f,-0.2606f,0.1357f,0.2587f,0.2877f,0.046f,0.0433f,0.0434f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0f,0f,0f,-0.0192f,0f,0f,0f,0.3793f,0f,0f,0f,0.0018f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.0595f,0.1294f,0.2578f,-0.0193f,0.0213f,-0.2606f,0.1357f,0.363f,0.2877f,0.046f,0.0433f,0.1161f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.0595f,0.1294f,0.2578f,0.0216f,0.0213f,-0.2606f,0.1357f,0.3484f,0.2877f,0.046f,0.0433f,-0.0817f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [0.0518f,-0.0156f,0.2895f,0.0406f,0.1077f,-0.272f,-0.0339f,0.3299f,0.2692f,0.1118f,-0.0421f,0.1139f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.1569f,0.0218f,0.2483f,0.074f,-0.0701f,-0.2854f,-0.0192f,0.318f,0.2392f,-0.0693f,0.1572f,-0.0479f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-0.0595f,0.1294f,0.2578f,-0.0597f,0.0213f,-0.2606f,0.1357f,0.4958f,0.2877f,0.046f,0.0433f,0.0037f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.0595f,0.1386f,0.253f,-0.08f,0.0213f,-0.2555f,0.145f,0.4642f,0.2877f,0.0475f,0.0416f,0.0414f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.0595f,0.1386f,0.253f,-0.0961f,0.0213f,-0.2555f,0.145f,0.5215f,0.2877f,0.0475f,0.0416f,-0.0604f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"-0.033","py":"0.339","pz":"0.021","ry":"99.53","rx":"27.426"},"hitbox":{"px":"-0.178","py":"0.694","pz":"-0.035","ry":"99.336","rx":"29.489"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args