# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.7186f,0.1148f,0.8119f,-0.1004f,-0.3273f,0.9497f,-0.4239f,2.4239f,-0.7519f,-0.5231f,-0.5914f,1.54f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0669f,-0.0328f,-0.2221f,0.2075f,-0.0358f,1.0897f,0.0108f,2.2318f,0.2217f,0.0178f,-1.0674f,1.3487f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.0671f,-0.0616f,-0.216f,0.2581f,-0.0358f,1.0819f,-0.1316f,1.7023f,0.2217f,-0.1217f,-1.0607f,1.5069f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.0669f,-0.0328f,-0.2221f,-0.1136f,-0.0358f,1.0897f,0.0108f,1.812f,0.2217f,0.0178f,-1.0674f,1.4113f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0669f,-0.0328f,-0.2221f,0.6199f,-0.0358f,1.0897f,0.0108f,1.8366f,0.2217f,0.0178f,-1.0674f,1.2589f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-1.0484f,-0.2497f,0.165f,-0.0875f,-0.1355f,0.932f,0.5493f,2.0197f,-0.2669f,0.5077f,-0.9273f,1.2688f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.8447f,0.4004f,-0.5611f,0.5127f,0.0762f,0.9363f,0.5534f,2.0398f,0.6851f,0.3895f,-0.7534f,1.1441f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0669f,-0.0328f,-0.2221f,0.2299f,-0.0358f,1.0897f,0.0108f,1.2582f,0.2217f,0.0178f,-1.0674f,1.2995f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0667f,-0.0277f,-0.2238f,0.1087f,-0.0322f,1.0897f,0.0187f,1.3408f,0.2232f,0.0249f,-1.0669f,1.4308f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0667f,-0.0277f,-0.2238f,0.4489f,-0.0322f,1.0897f,0.0187f,1.0784f,0.2232f,0.0249f,-1.0669f,1.3548f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0.248","py":"1.822","pz":"1.475","ry":"348.245","rx":"0.566"},"hitbox":{"px":"0.259","py":"0.393","pz":"1.313","ry":"348.154","rx":"0.984"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args