# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6144f,0.2155f,0.841f,-0.2957f,-0.2958f,0.9167f,-0.4509f,2.3704f,-0.8162f,-0.4944f,-0.4696f,1.3997f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0604f,0.0112f,-0.0812f,0.0178f,0.0103f,1.0634f,0.011f,2.169f,0.0813f,0.0101f,-1.0604f,1.2536f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.0622f,0.0005f,-0.0821f,0.0251f,0.0104f,1.0576f,-0.1282f,1.6522f,0.0814f,-0.1286f,-1.0544f,1.4144f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.0604f,0.0112f,-0.0812f,-0.3178f,0.0103f,1.0634f,0.011f,1.7735f,0.0813f,0.0101f,-1.0604f,1.2752f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0604f,0.0112f,-0.0812f,0.4112f,0.0103f,1.0634f,0.011f,1.7664f,0.0813f,0.0101f,-1.0604f,1.2193f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9752f,-0.2906f,0.3093f,-0.2662f,-0.0959f,0.9059f,0.5489f,1.9737f,-0.4134f,0.4754f,-0.8568f,1.14f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.8987f,0.3772f,-0.4255f,0.3303f,0.1142f,0.8994f,0.5561f,1.9678f,0.5571f,0.4242f,-0.8005f,1.0943f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0604f,0.0112f,-0.0812f,0.0053f,0.0103f,1.0634f,0.011f,1.2189f,0.0813f,0.0101f,-1.0604f,1.2114f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0604f,0.0099f,-0.0813f,-0.1255f,0.0103f,1.0635f,-0.0061f,1.3073f,0.0813f,-0.0068f,-1.0604f,1.321f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0604f,0.0099f,-0.0813f,0.2034f,0.0103f,1.0635f,-0.0061f,1.0382f,0.0813f,-0.0068f,-1.0604f,1.2973f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.024","py":"1.769","pz":"1.382","ry":"355.623","rx":"0.59"},"hitbox":{"px":"-0","py":"0.375","pz":"1.25","ry":"355.614","rx":"-0.327"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args