# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [0.577f,-0.0439f,0.3942f,-1.2104f,0.2017f,0.6317f,-0.2249f,1.1656f,-0.3415f,0.2989f,0.5332f,-0.1372f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.0187f,-0.3714f,0.5933f,-1.0682f,0.1448f,0.5786f,0.3668f,1.0541f,-0.6848f,0.1325f,0.0614f,0.0546f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0f,0f,0f,-0.981f,0f,0f,0f,0.7165f,0f,0f,0f,-0.0192f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.0187f,-0.3714f,0.5933f,-0.9348f,0.1448f,0.5786f,0.3668f,0.8824f,-0.6848f,0.1325f,0.0614f,-0.2091f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.0187f,-0.3714f,0.5933f,-0.922f,0.1448f,0.5786f,0.3668f,0.7828f,-0.6848f,0.1325f,0.0614f,0.2617f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [0.0496f,-0.4303f,0.5501f,-0.9292f,0.1665f,0.5429f,0.4096f,1.0285f,-0.6783f,0.1018f,0.1408f,-0.1381f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.3259f,-0.5578f,0.2701f,-0.9187f,0.0204f,0.2953f,0.6345f,0.9471f,-0.6194f,0.3032f,-0.1212f,0.2471f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-0.0187f,-0.3714f,0.5933f,-0.7178f,0.1448f,0.5786f,0.3668f,0.5484f,-0.6848f,0.1325f,0.0614f,-0.0619f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [0.0729f,-0.1437f,0.6814f,-0.7379f,0.013f,0.6853f,0.1431f,0.5623f,-0.6963f,-0.0022f,0.0741f,-0.1562f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [0.0729f,-0.1961f,0.6682f,-0.7228f,0.013f,0.6721f,0.1958f,0.4403f,-0.6963f,-0.008f,0.0737f,0.0631f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"-1.003","py":"0.791","pz":"-0.003","ry":"95.907","rx":"31.59"},"hitbox":{"px":"-0.625","py":"0","pz":"-0.063","ry":"96.203","rx":"11.793"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args