# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6046f,0.2316f,0.8557f,-0.2616f,-0.2781f,0.934f,-0.4493f,2.2898f,-0.8418f,-0.4749f,-0.4662f,1.4574f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0713f,0.016f,-0.0604f,0.0566f,0.0141f,1.0725f,0.0338f,2.0882f,0.0609f,0.0329f,-1.0709f,1.3121f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0.9663f,0.183f,0.4298f,-0.2181f,-0.095f,1.0439f,-0.2309f,1.4952f,-0.4574f,0.1698f,0.956f,1.686f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.272f,0.048f,1.0369f,-0.2841f,0.2129f,1.0517f,0.0072f,1.6905f,-1.016f,0.2076f,-0.2761f,1.3188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0713f,0.016f,-0.0604f,0.4524f,0.0141f,1.0725f,0.0338f,1.6808f,0.0609f,0.0329f,-1.0709f,1.2769f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9758f,-0.2986f,0.3319f,-0.2284f,-0.0831f,0.9053f,0.5701f,1.895f,-0.4386f,0.4927f,-0.8464f,1.1877f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9174f,0.3761f,-0.4105f,0.3742f,0.108f,0.8964f,0.5799f,1.887f,0.5462f,0.4544f,-0.8042f,1.1534f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0713f,0.016f,-0.0604f,0.0405f,0.0141f,1.0725f,0.0338f,1.1308f,0.0609f,0.0329f,-1.0709f,1.2492f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0713f,0.0138f,-0.0609f,-0.0933f,0.0141f,1.073f,-0.005f,1.2203f,0.0609f,-0.0058f,-1.0713f,1.3572f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0713f,0.0138f,-0.0609f,0.238f,0.0141f,1.073f,-0.005f,0.9476f,0.0609f,-0.0058f,-1.0713f,1.3396f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"-0.329","py":"1.623","pz":"1.671","ry":"75.092","rx":"0.382"},"hitbox":{"px":"0.031","py":"0.279","pz":"1.287","ry":"356.745","rx":"-0.266"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args