# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6023f,0.2348f,0.8647f,-0.2547f,-0.2802f,0.9403f,-0.4505f,2.2779f,-0.8511f,-0.4757f,-0.4636f,1.4677f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0782f,0.0143f,-0.0537f,0.0668f,0.0125f,1.079f,0.0345f,2.0756f,0.0541f,0.0338f,-1.0777f,1.3236f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0.965f,0.1823f,0.4485f,-0.2618f,-0.0879f,1.0495f,-0.2375f,1.518f,-0.4761f,0.1758f,0.9529f,1.5045f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.2741f,0.0466f,1.0432f,-0.2755f,0.2186f,1.0572f,0.0103f,1.6749f,-1.0211f,0.2139f,-0.2778f,1.3278f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0782f,0.0143f,-0.0537f,0.4658f,0.0125f,1.079f,0.0345f,1.6663f,0.0541f,0.0338f,-1.0777f,1.2906f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9787f,-0.305f,0.3386f,-0.2189f,-0.0848f,0.9101f,0.5746f,1.8808f,-0.4478f,0.4942f,-0.849f,1.1964f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9267f,0.374f,-0.4085f,0.3876f,0.107f,0.9022f,0.5832f,1.8738f,0.5434f,0.4601f,-0.8115f,1.1659f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0782f,0.0143f,-0.0537f,0.0524f,0.0125f,1.079f,0.0345f,1.1124f,0.0541f,0.0338f,-1.0777f,1.2597f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0782f,0.0123f,-0.0542f,-0.0831f,0.0125f,1.0795f,-0.0045f,1.2021f,0.0541f,-0.0051f,-1.0782f,1.3674f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0782f,0.0123f,-0.0542f,0.2508f,0.0125f,1.0795f,-0.0045f,0.9283f,0.0541f,-0.0051f,-1.0782f,1.3518f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"-0.32","py":"1.605","pz":"1.682","ry":"75.088","rx":"0.544"},"hitbox":{"px":"0.044","py":"0.256","pz":"1.297","ry":"357.124","rx":"-0.24"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args