# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6f,0.2372f,0.8714f,-0.2502f,-0.2818f,0.9448f,-0.4511f,2.27f,-0.858f,-0.4761f,-0.4612f,1.4733f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0831f,0.0128f,-0.0482f,0.0736f,0.0113f,1.0836f,0.035f,2.0673f,0.0486f,0.0345f,-1.0826f,1.3301f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0.9873f,0.176f,0.412f,-0.219f,-0.098f,1.0577f,-0.2171f,1.4739f,-0.4372f,0.1605f,0.9791f,1.7088f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.2343f,0.0383f,1.0579f,-0.2697f,0.1968f,1.0662f,0.005f,1.6645f,-1.0402f,0.1931f,-0.2373f,1.3324f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0831f,0.0128f,-0.0482f,0.475f,0.0113f,1.0836f,0.035f,1.6568f,0.0486f,0.0345f,-1.0826f,1.299f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9804f,-0.3101f,0.3439f,-0.2124f,-0.0862f,0.9134f,0.5778f,1.8714f,-0.4549f,0.4951f,-0.8506f,1.2008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9337f,0.3721f,-0.4067f,0.3969f,0.1061f,0.9063f,0.5856f,1.8651f,0.5409f,0.4645f,-0.8169f,1.1735f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0831f,0.0128f,-0.0482f,0.0607f,0.0113f,1.0836f,0.035f,1.1f,0.0486f,0.0345f,-1.0826f,1.2655f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0831f,0.0111f,-0.0487f,-0.076f,0.0113f,1.0842f,-0.0041f,1.1899f,0.0486f,-0.0046f,-1.0831f,1.373f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0831f,0.0111f,-0.0487f,0.2597f,0.0113f,1.0842f,-0.0041f,0.9153f,0.0486f,-0.0046f,-1.0831f,1.359f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"-0.329","py":"1.602","pz":"1.687","ry":"77.356","rx":"0.264"},"hitbox":{"px":"0.053","py":"0.24","pz":"1.303","ry":"357.427","rx":"-0.218"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args