# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5979f,0.2388f,0.876f,-0.2479f,-0.2828f,0.9478f,-0.4514f,2.2656f,-0.8628f,-0.4761f,-0.4591f,1.4753f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0862f,0.0117f,-0.0441f,0.0776f,0.0103f,1.0866f,0.0355f,2.0627f,0.0445f,0.035f,-1.0857f,1.333f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [1.0032f,0.1714f,0.3825f,-0.2652f,-0.1058f,1.0636f,-0.1991f,1.5078f,-0.4055f,0.1464f,0.998f,1.5185f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.2025f,0.0323f,1.0677f,-0.2662f,0.1777f,1.0726f,0.0012f,1.6584f,-1.0533f,0.1747f,-0.205f,1.3337f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0862f,0.0117f,-0.0441f,0.4805f,0.0103f,1.0866f,0.0355f,1.6513f,0.0445f,0.035f,-1.0857f,1.3032f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9812f,-0.3137f,0.3477f,-0.2085f,-0.0871f,0.9154f,0.58f,1.866f,-0.4601f,0.4956f,-0.8513f,1.2021f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9385f,0.3704f,-0.4051f,0.4025f,0.1054f,0.9089f,0.5871f,1.8602f,0.5387f,0.4675f,-0.8205f,1.1771f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0862f,0.0117f,-0.0441f,0.0657f,0.0103f,1.0866f,0.0355f,1.0926f,0.0445f,0.035f,-1.0857f,1.2678f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0862f,0.0101f,-0.0445f,-0.0718f,0.0103f,1.0871f,-0.0038f,1.1827f,0.0445f,-0.0042f,-1.0863f,1.3751f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0862f,0.0101f,-0.0445f,0.2651f,0.0103f,1.0871f,-0.0038f,0.9077f,0.0445f,-0.0042f,-1.0863f,1.3622f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"-0.336","py":"1.603","pz":"1.689","ry":"79.13","rx":"0.065"},"hitbox":{"px":"0.059","py":"0.23","pz":"1.305","ry":"357.654","rx":"-0.201"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args