# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5972f,0.2394f,0.8775f,-0.2473f,-0.2831f,0.9486f,-0.4515f,2.2644f,-0.8643f,-0.4761f,-0.4584f,1.4755f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0872f,0.0114f,-0.0427f,0.0787f,0.01f,1.0874f,0.0356f,2.0614f,0.0431f,0.0352f,-1.0866f,1.3334f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [1.0097f,0.1707f,0.3761f,-0.2657f,-0.1078f,1.0679f,-0.1951f,1.5068f,-0.3987f,0.1434f,1.0053f,1.5193f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.1945f,0.0308f,1.0701f,-0.2653f,0.1729f,1.0742f,0.0005f,1.6568f,-1.0565f,0.1702f,-0.197f,1.3337f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0872f,0.0114f,-0.0427f,0.4821f,0.01f,1.0874f,0.0356f,1.6499f,0.0431f,0.0352f,-1.0866f,1.3041f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9813f,-0.3149f,0.3489f,-0.2074f,-0.0875f,0.916f,0.5806f,1.8646f,-0.4618f,0.4956f,-0.8515f,1.202f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9399f,0.3698f,-0.4045f,0.4041f,0.1051f,0.9097f,0.5876f,1.8589f,0.5379f,0.4685f,-0.8216f,1.1778f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0872f,0.0114f,-0.0427f,0.0672f,0.01f,1.0874f,0.0356f,1.0907f,0.0431f,0.0352f,-1.0866f,1.268f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0872f,0.0098f,-0.0431f,-0.0707f,0.01f,1.088f,-0.0037f,1.1807f,0.0431f,-0.0041f,-1.0872f,1.3753f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0872f,0.0098f,-0.0431f,0.2666f,0.01f,1.088f,-0.0037f,0.9056f,0.0431f,-0.0041f,-1.0872f,1.3628f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute unless entity @s[tag=aj.transforms_only] positioned ^-0.3383069217 ^1.6026714198 ^1.688466305 rotated ~79.5707172153 ~0.0270196372 run function aj:fine_print/animations/give_back_item/zzz/frames/71_locator_locator
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"-0.338","py":"1.603","pz":"1.688","ry":"79.571","rx":"0.027"},"hitbox":{"px":"0.061","py":"0.227","pz":"1.305","ry":"357.73","rx":"-0.195"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args