# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5781f,0.2451f,0.8902f,-0.2612f,-0.2846f,0.9518f,-0.4469f,2.2771f,-0.8783f,-0.4698f,-0.4411f,1.4307f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0892f,0.0054f,-0.02f,0.0691f,0.0047f,1.0887f,0.0375f,2.0758f,0.0201f,0.0374f,-1.0885f,1.2951f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0f,0f,0f,-0.176f,0f,0f,0f,1.4892f,0f,0f,0f,1.4109f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.7289f,0.1319f,0.7988f,-0.2733f,0.3372f,1.0266f,0.1381f,1.669f,-0.736f,0.3396f,-0.7277f,1.2873f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0892f,0.0054f,-0.02f,0.4755f,0.0047f,1.0887f,0.0375f,1.6658f,0.0201f,0.0374f,-1.0885f,1.2735f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9721f,-0.3301f,0.3644f,-0.2135f,-0.0914f,0.9146f,0.5847f,1.8776f,-0.4832f,0.4911f,-0.8439f,1.1571f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9527f,0.3559f,-0.3903f,0.3992f,0.0997f,0.9117f,0.5879f,1.8749f,0.5187f,0.4784f,-0.8299f,1.1458f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0892f,0.0054f,-0.02f,0.0637f,0.0047f,1.0887f,0.0375f,1.1039f,0.0201f,0.0374f,-1.0885f,1.2276f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0892f,0.0046f,-0.0201f,-0.077f,0.0047f,1.0894f,-0.0018f,1.1932f,0.0201f,-0.0019f,-1.0892f,1.3322f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0892f,0.0046f,-0.0201f,0.2622f,0.0047f,1.0894f,-0.0018f,0.9194f,0.0201f,-0.0019f,-1.0892f,1.3264f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"-0.145","py":"1.546","pz":"1.608","ry":"47.664","rx":"7.284"},"hitbox":{"px":"0.061","py":"0.239","pz":"1.263","ry":"358.941","rx":"-0.096"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args