# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5727f,0.2453f,0.8897f,-0.27f,-0.284f,0.9494f,-0.4446f,2.2881f,-0.8781f,-0.4671f,-0.4364f,1.4095f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.086f,0.0042f,-0.0156f,0.06f,0.0037f,1.0855f,0.0378f,2.0877f,0.0158f,0.0377f,-1.0854f,1.2755f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0f,0f,0f,-0.1435f,0f,0f,0f,1.5114f,0f,0f,0f,1.3602f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.9149f,0.1506f,0.5657f,-0.2809f,0.2757f,1.0367f,0.17f,1.6817f,-0.5164f,0.2867f,-0.9115f,1.2663f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.086f,0.0042f,-0.0156f,0.4657f,0.0037f,1.0855f,0.0378f,1.6792f,0.0158f,0.0377f,-1.0854f,1.2555f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9672f,-0.3319f,0.3662f,-0.221f,-0.0918f,0.9114f,0.5836f,1.8898f,-0.4856f,0.4887f,-0.8397f,1.1368f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9521f,0.3521f,-0.3864f,0.3899f,0.0983f,0.9091f,0.5861f,1.8877f,0.5135f,0.4788f,-0.8288f,1.1279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.086f,0.0042f,-0.0156f,0.0558f,0.0037f,1.0855f,0.0378f,1.1187f,0.0158f,0.0377f,-1.0854f,1.2079f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.086f,0.0036f,-0.0158f,-0.085f,0.0037f,1.0861f,-0.0014f,1.2076f,0.0158f,-0.0015f,-1.086f,1.3116f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.086f,0.0036f,-0.0158f,0.2535f,0.0037f,1.0861f,-0.0014f,0.9349f,0.0158f,-0.0015f,-1.086f,1.3071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"-0.066","py":"1.574","pz":"1.542","ry":"31.823","rx":"9.002"},"hitbox":{"px":"0.053","py":"0.257","pz":"1.243","ry":"359.168","rx":"-0.076"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args