# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5707f,0.2453f,0.8893f,-0.2735f,-0.2837f,0.9483f,-0.4437f,2.2924f,-0.8778f,-0.466f,-0.4348f,1.4014f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0847f,0.0038f,-0.0142f,0.0564f,0.0033f,1.0841f,0.0379f,2.0924f,0.0143f,0.0378f,-1.084f,1.2679f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0f,0f,0f,0.046f,0f,0f,0f,1.4766f,0f,0f,0f,1.4242f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.9625f,0.1459f,0.4785f,-0.284f,0.2422f,1.0438f,0.1691f,1.6869f,-0.4377f,0.2569f,-0.9587f,1.2582f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0847f,0.0038f,-0.0142f,0.4617f,0.0033f,1.0841f,0.0379f,1.6846f,0.0143f,0.0378f,-1.084f,1.2484f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9653f,-0.3324f,0.3666f,-0.2241f,-0.092f,0.9101f,0.583f,1.8947f,-0.4863f,0.4877f,-0.8381f,1.129f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9516f,0.3507f,-0.385f,0.386f,0.0978f,0.908f,0.5853f,1.8928f,0.5116f,0.4787f,-0.8282f,1.121f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0847f,0.0038f,-0.0142f,0.0525f,0.0033f,1.0841f,0.0379f,1.1247f,0.0143f,0.0378f,-1.084f,1.2003f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0847f,0.0033f,-0.0143f,-0.0883f,0.0033f,1.0848f,-0.0013f,1.2134f,0.0143f,-0.0014f,-1.0847f,1.3037f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0847f,0.0033f,-0.0143f,0.2499f,0.0033f,1.0848f,-0.0013f,0.9411f,0.0143f,-0.0014f,-1.0847f,1.2996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"-0.043","py":"1.59","pz":"1.515","ry":"26.526","rx":"8.968"},"hitbox":{"px":"0.05","py":"0.264","pz":"1.235","ry":"359.244","rx":"-0.07"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args