# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=aj.fine_print.animation.spawn.playing] run function aj:fine_print/animations/spawn/zzz/on_tick
execute if entity @s[tag=aj.fine_print.animation.loop.playing] run function aj:fine_print/animations/loop/zzz/on_tick
execute if entity @s[tag=aj.fine_print.animation.vanish.playing] run function aj:fine_print/animations/vanish/zzz/on_tick
execute if entity @s[tag=aj.fine_print.animation.bring_item.playing] run function aj:fine_print/animations/bring_item/zzz/on_tick
execute if entity @s[tag=aj.fine_print.animation.give_back_item.playing] run function aj:fine_print/animations/give_back_item/zzz/on_tick
execute if entity @s[tag=aj.fine_print.animation.trade_item.playing] run function aj:fine_print/animations/trade_item/zzz/on_tick
execute if entity @s[tag=aj.fine_print.animation.pocket_enter.playing] run function aj:fine_print/animations/pocket_enter/zzz/on_tick
execute if entity @s[tag=aj.fine_print.animation.pocket_leave.playing] run function aj:fine_print/animations/pocket_leave/zzz/on_tick
function aj:fine_print/root/on_tick/transform_floating_entities
function aj:fine_print/root/zzz/0 with storage animated_java:temp entry.data.uuids_by_name