# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6029f,0.2429f,0.9135f,-0.3253f,-0.4841f,0.8512f,-0.5459f,2.5164f,-0.8118f,-0.6881f,-0.3529f,1.4329f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.1207f,0.001f,-0.0322f,0.0141f,0.0069f,1.1019f,-0.2065f,2.2844f,0.0315f,-0.2066f,-1.1015f,1.3381f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.7769f,0.0112f,-0.0499f,0.0142f,0.0109f,1.7776f,0.0082f,1.5119f,0.0499f,0.0079f,-1.7769f,1.5132f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1207f,0.0098f,-0.0307f,-0.3398f,0.0069f,1.1164f,0.1029f,1.8679f,0.0315f,0.1026f,-1.116f,1.3094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1207f,0.0098f,-0.0307f,0.4307f,0.0069f,1.1164f,0.1029f,1.8632f,0.0315f,0.1026f,-1.116f,1.2878f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-1.0053f,-0.3318f,0.3691f,-0.2788f,-0.0625f,0.9117f,0.6495f,2.0897f,-0.4924f,0.5618f,-0.836f,1.1874f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9752f,0.374f,-0.4075f,0.3516f,0.0746f,0.9074f,0.6542f,2.0859f,0.548f,0.542f,-0.8142f,1.1697f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.1207f,0.0098f,-0.0307f,0.0044f,0.0069f,1.1164f,0.1029f,1.2899f,0.0315f,0.1026f,-1.116f,1.2115f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.1207f,0.0068f,-0.0315f,-0.1392f,0.0069f,1.1211f,-0.0042f,1.3823f,0.0315f,-0.0044f,-1.1207f,1.3203f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.1207f,0.0068f,-0.0315f,0.2093f,0.0069f,1.1211f,-0.0042f,1.0998f,0.0315f,-0.0044f,-1.1207f,1.3116f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.014","py":"1.853","pz":"1.439","ry":"358.423","rx":"5.264"},"hitbox":{"px":"-0","py":"0.4","pz":"1.25","ry":"358.389","rx":"-0.217"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args