# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6034f,0.2522f,0.9115f,-0.3249f,-0.2192f,1.0145f,-0.4258f,2.4585f,-0.92f,-0.4072f,-0.4964f,1.4962f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.1214f,0.0099f,-0.0291f,0.0134f,0.0066f,1.1146f,0.1268f,2.2617f,0.0301f,0.1266f,-1.1143f,1.3379f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.7807f,0.0106f,-0.0477f,0.0136f,0.0104f,1.7813f,0.0075f,1.4887f,0.0477f,0.0072f,-1.7807f,1.5135f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1214f,0.0093f,-0.0293f,-0.3405f,0.0066f,1.1171f,0.1025f,1.8448f,0.0301f,0.1023f,-1.1168f,1.3089f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1214f,0.0093f,-0.0293f,0.4305f,0.0066f,1.1171f,0.1025f,1.8403f,0.0301f,0.1023f,-1.1168f,1.2883f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-1.0053f,-0.333f,0.3702f,-0.2794f,-0.063f,0.9124f,0.6497f,2.0668f,-0.494f,0.5614f,-0.8363f,1.1868f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9766f,0.3733f,-0.4069f,0.3514f,0.0746f,0.9083f,0.6542f,2.0631f,0.5471f,0.5424f,-0.8155f,1.1699f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.1214f,0.0093f,-0.0293f,0.0042f,0.0066f,1.1171f,0.1025f,1.2665f,0.0301f,0.1023f,-1.1168f,1.2116f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.1214f,0.0065f,-0.0301f,-0.1397f,0.0066f,1.1218f,-0.0041f,1.3589f,0.0301f,-0.0042f,-1.1214f,1.3203f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.1214f,0.0065f,-0.0301f,0.2092f,0.0066f,1.1218f,-0.0041f,1.0764f,0.0301f,-0.0042f,-1.1214f,1.312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.014","py":"1.83","pz":"1.439","ry":"358.495","rx":"5.241"},"hitbox":{"px":"-0","py":"0.376","pz":"1.25","ry":"358.463","rx":"-0.207"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args