# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6028f,0.257f,0.911f,-0.3248f,-0.0684f,1.0654f,-0.3458f,2.4216f,-0.9441f,-0.2413f,-0.5566f,1.5249f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.1218f,0.0141f,-0.0266f,0.0131f,0.0064f,1.0808f,0.3017f,2.2509f,0.0294f,0.3015f,-1.0805f,1.3378f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.7825f,0.0104f,-0.0466f,0.0133f,0.0102f,1.7831f,0.0071f,1.4777f,0.0467f,0.0068f,-1.7825f,1.5136f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1218f,0.0091f,-0.0287f,-0.3409f,0.0064f,1.1175f,0.1023f,1.8339f,0.0294f,0.1021f,-1.1171f,1.3087f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1218f,0.0091f,-0.0287f,0.4303f,0.0064f,1.1175f,0.1023f,1.8295f,0.0294f,0.1021f,-1.1171f,1.2885f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-1.0052f,-0.3336f,0.3708f,-0.2797f,-0.0633f,0.9128f,0.6497f,2.0558f,-0.4947f,0.5611f,-0.8365f,1.1865f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9772f,0.3729f,-0.4066f,0.3513f,0.0746f,0.9087f,0.6542f,2.0522f,0.5466f,0.5426f,-0.8161f,1.17f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.1218f,0.0091f,-0.0287f,0.0041f,0.0064f,1.1175f,0.1023f,1.2554f,0.0294f,0.1021f,-1.1171f,1.2117f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.1218f,0.0063f,-0.0294f,-0.1399f,0.0064f,1.1222f,-0.004f,1.3477f,0.0294f,-0.0041f,-1.1218f,1.3204f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.1218f,0.0063f,-0.0294f,0.2091f,0.0064f,1.1222f,-0.004f,1.0652f,0.0294f,-0.0041f,-1.1218f,1.3122f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.013","py":"1.819","pz":"1.439","ry":"358.531","rx":"5.228"},"hitbox":{"px":"-0","py":"0.365","pz":"1.25","ry":"358.5","rx":"-0.202"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args