# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6017f,0.2605f,0.9111f,-0.3251f,0.0471f,1.0861f,-0.2795f,2.3888f,-0.9464f,-0.1116f,-0.5932f,1.5435f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.1221f,0.0167f,-0.0241f,0.0127f,0.0062f,1.0372f,0.4292f,2.2407f,0.0287f,0.429f,-1.0369f,1.3377f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.7842f,-0.002f,-0.0466f,0.0129f,0.0099f,1.7257f,-0.4555f,1.4674f,0.0456f,-0.4556f,-1.7251f,1.5137f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1221f,0.0088f,-0.028f,-0.3412f,0.0062f,1.1178f,0.102f,1.8235f,0.0287f,0.1018f,-1.1175f,1.3084f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1221f,0.0088f,-0.028f,0.4302f,0.0062f,1.1178f,0.102f,1.8192f,0.0287f,0.1018f,-1.1175f,1.2887f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-1.0052f,-0.3342f,0.3713f,-0.2799f,-0.0636f,0.9131f,0.6498f,2.0455f,-0.4955f,0.5608f,-0.8366f,1.1862f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9778f,0.3725f,-0.4063f,0.3512f,0.0746f,0.9092f,0.6541f,2.042f,0.5461f,0.5428f,-0.8168f,1.1701f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.1221f,0.0088f,-0.028f,0.004f,0.0062f,1.1178f,0.102f,1.2449f,0.0287f,0.1018f,-1.1175f,1.2117f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.1221f,0.0061f,-0.0287f,-0.1401f,0.0062f,1.1225f,-0.0039f,1.3373f,0.0287f,-0.004f,-1.1221f,1.3204f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.1221f,0.0061f,-0.0287f,0.209f,0.0062f,1.1225f,-0.0039f,1.0547f,0.0287f,-0.004f,-1.1221f,1.3124f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0.013","py":"1.809","pz":"1.439","ry":"358.566","rx":"5.215"},"hitbox":{"px":"-0","py":"0.354","pz":"1.25","ry":"358.536","rx":"-0.197"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args