# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5997f,0.2487f,0.9173f,-0.3295f,-0.3947f,0.9215f,-0.5079f,2.4272f,-0.8645f,-0.5933f,-0.4044f,1.4541f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.1235f,0.0034f,-0.0255f,0.011f,0.0054f,1.1203f,-0.0881f,2.2056f,0.0252f,-0.0882f,-1.12f,1.3369f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.7922f,-0.002f,-0.0411f,0.0113f,0.0086f,1.7327f,-0.4599f,1.4316f,0.0402f,-0.46f,-1.7322f,1.5142f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1235f,0.0076f,-0.0246f,-0.3429f,0.0054f,1.1193f,0.1006f,1.7876f,0.0252f,0.1004f,-1.119f,1.3071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1235f,0.0076f,-0.0246f,0.4295f,0.0054f,1.1193f,0.1006f,1.7838f,0.0252f,0.1004f,-1.119f,1.2897f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-1.0048f,-0.337f,0.3738f,-0.2814f,-0.0651f,0.9147f,0.6497f,2.0097f,-0.4991f,0.5592f,-0.8373f,1.1846f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9807f,0.3706f,-0.4047f,0.3506f,0.0747f,0.9112f,0.6534f,2.0066f,0.5436f,0.5433f,-0.8199f,1.1704f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.1235f,0.0076f,-0.0246f,0.0034f,0.0054f,1.1193f,0.1006f,1.2084f,0.0252f,0.1004f,-1.119f,1.2121f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.1235f,0.0053f,-0.0252f,-0.1412f,0.0054f,1.1238f,-0.0034f,1.3007f,0.0252f,-0.0035f,-1.1235f,1.3205f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.1235f,0.0053f,-0.0252f,0.2085f,0.0054f,1.1238f,-0.0034f,1.0181f,0.0252f,-0.0035f,-1.1235f,1.3135f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0.011","py":"1.773","pz":"1.439","ry":"358.74","rx":"5.135"},"hitbox":{"px":"-0","py":"0.317","pz":"1.25","ry":"358.714","rx":"-0.171"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args