# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.7044f,-0.0192f,0.7271f,-0.1753f,-0.3461f,0.8991f,-0.3115f,2.2391f,-0.6398f,-0.4652f,-0.6321f,1.6353f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9589f,-0.1165f,-0.3038f,0.1061f,-0.1267f,1.0045f,0.0147f,2.0913f,0.2996f,0.052f,-0.9658f,1.4251f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.5431f,-0.2294f,-0.4706f,0.2508f,-0.204f,1.6124f,-0.1173f,1.4132f,0.4822f,-0.0522f,-1.5557f,1.6015f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.9589f,-0.1165f,-0.3038f,-0.1499f,-0.1267f,1.0045f,0.0147f,1.675f,0.2996f,0.052f,-0.9658f,1.4993f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.9589f,-0.1165f,-0.3038f,0.5093f,-0.1267f,1.0045f,0.0147f,1.7621f,0.2996f,0.052f,-0.9658f,1.2933f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9951f,-0.1748f,-0.0666f,-0.1558f,-0.187f,0.9238f,0.37f,1.8723f,-0.0031f,0.3759f,-0.9402f,1.3714f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.7206f,0.3289f,-0.6307f,0.3836f,-0.0148f,0.8907f,0.4814f,1.9436f,0.7111f,0.3518f,-0.6291f,1.2029f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-0.9589f,-0.1165f,-0.3038f,0.2007f,-0.1267f,1.0045f,0.0147f,1.194f,0.2996f,0.052f,-0.9658f,1.3485f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.9584f,-0.0907f,-0.3139f,0.097f,-0.1095f,1.0057f,0.0437f,1.2572f,0.3079f,0.0753f,-0.9617f,1.4852f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.9584f,-0.0907f,-0.3139f,0.4192f,-0.1095f,1.0057f,0.0437f,1.04f,0.3079f,0.0753f,-0.9617f,1.3701f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.188","py":"1.713","pz":"1.526","ry":"342.541","rx":"0.833"},"hitbox":{"px":"0.283","py":"0.394","pz":"1.319","ry":"341.92","rx":"2.476"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args