# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5929f,0.2557f,0.9212f,-0.3353f,-0.1692f,1.0388f,-0.3972f,2.492f,-0.9409f,-0.3479f,-0.5091f,1.4953f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.1248f,0.0058f,-0.0154f,0.0063f,0.0031f,1.1089f,0.189f,2.3044f,0.0162f,0.189f,-1.1088f,1.3302f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.8069f,0.0048f,-0.026f,0.0069f,0.005f,1.8071f,-0.0103f,1.5311f,0.026f,-0.0103f,-1.8069f,1.5139f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1248f,0.0044f,-0.0159f,-0.3468f,0.0031f,1.1212f,0.0917f,1.8849f,0.0162f,0.0916f,-1.1211f,1.3009f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1248f,0.0044f,-0.0159f,0.4265f,0.0031f,1.1212f,0.0917f,1.8828f,0.0162f,0.0916f,-1.1211f,1.2898f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-1.0016f,-0.3439f,0.3795f,-0.2847f,-0.0714f,0.9193f,0.6444f,2.1064f,-0.5071f,0.5497f,-0.8403f,1.177f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9862f,0.3646f,-0.3999f,0.348f,0.0769f,0.9173f,0.6466f,2.1047f,0.5357f,0.5395f,-0.8291f,1.1679f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.1248f,0.0044f,-0.0159f,0.0019f,0.0031f,1.1212f,0.0917f,1.3052f,0.0162f,0.0916f,-1.1211f,1.2133f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.1248f,0.0031f,-0.0162f,-0.1439f,0.0031f,1.1249f,-0.0019f,1.3972f,0.0162f,-0.002f,-1.1248f,1.3207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.1248f,0.0031f,-0.0162f,0.2068f,0.0031f,1.1249f,-0.0019f,1.115f,0.0162f,-0.002f,-1.1248f,1.3161f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.007","py":"1.873","pz":"1.436","ry":"359.19","rx":"4.674"},"hitbox":{"px":"-0","py":"0.412","pz":"1.25","ry":"359.177","rx":"-0.099"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args