# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5906f,0.2542f,0.9227f,-0.3372f,-0.2748f,0.9935f,-0.4497f,2.555f,-0.9167f,-0.4616f,-0.4596f,1.4657f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.1245f,0.0032f,-0.0136f,0.0051f,0.0025f,1.1228f,0.0634f,2.3508f,0.0138f,0.0634f,-1.1227f,1.3233f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.8088f,-0.0022f,-0.0224f,0.0057f,0.004f,1.7411f,-0.4907f,1.579f,0.0222f,-0.4907f,-1.7409f,1.5125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1245f,0.0035f,-0.0136f,-0.3477f,0.0025f,1.1215f,0.0836f,1.931f,0.0138f,0.0835f,-1.1214f,1.2963f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1245f,0.0035f,-0.0136f,0.4254f,0.0025f,1.1215f,0.0836f,1.9293f,0.0138f,0.0835f,-1.1214f,1.2868f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-1.0002f,-0.3455f,0.3807f,-0.2854f,-0.0757f,0.9227f,0.6384f,2.1516f,-0.5085f,0.5422f,-0.8439f,1.171f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9871f,0.3627f,-0.3985f,0.3471f,0.0801f,0.9212f,0.6401f,2.1502f,0.5329f,0.5335f,-0.8344f,1.1632f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.1245f,0.0035f,-0.0136f,0.0015f,0.0025f,1.1215f,0.0836f,1.3511f,0.0138f,0.0835f,-1.1214f,1.2136f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.1245f,0.0025f,-0.0138f,-0.1446f,0.0025f,1.1246f,-0.0016f,1.4429f,0.0138f,-0.0016f,-1.1245f,1.3207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.1245f,0.0025f,-0.0138f,0.2062f,0.0025f,1.1246f,-0.0016f,1.161f,0.0138f,-0.0016f,-1.1245f,1.3168f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0.005","py":"1.92","pz":"1.432","ry":"359.307","rx":"4.261"},"hitbox":{"px":"-0","py":"0.458","pz":"1.25","ry":"359.298","rx":"-0.079"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args