# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.7439f,-0.0367f,0.689f,-0.1165f,-0.3474f,0.8953f,-0.3274f,2.2528f,-0.5961f,-0.4759f,-0.669f,1.644f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9436f,-0.104f,-0.3579f,0.1517f,-0.1134f,1.0082f,0.006f,2.0992f,0.3551f,0.0455f,-0.9493f,1.4199f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.5145f,-0.2163f,-0.5577f,0.2999f,-0.182f,1.6128f,-0.1315f,1.4205f,0.5698f,-0.06f,-1.5242f,1.597f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.9436f,-0.104f,-0.3579f,-0.1042f,-0.1134f,1.0082f,0.006f,1.6857f,0.3551f,0.0455f,-0.9493f,1.5138f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.9436f,-0.104f,-0.3579f,0.5446f,-0.1134f,1.0082f,0.006f,1.7636f,0.3551f,0.0455f,-0.9493f,1.2697f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9978f,-0.1553f,-0.0982f,-0.1153f,-0.1814f,0.9193f,0.3891f,1.8818f,0.0294f,0.4002f,-0.9318f,1.3837f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.6811f,0.3574f,-0.6616f,0.4154f,0.0014f,0.8933f,0.481f,1.9456f,0.7519f,0.322f,-0.6002f,1.184f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-0.9436f,-0.104f,-0.3579f,0.2335f,-0.1134f,1.0082f,0.006f,1.1983f,0.3551f,0.0455f,-0.9493f,1.3496f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.9425f,-0.0758f,-0.3679f,0.1381f,-0.0956f,1.0094f,0.0371f,1.2643f,0.3633f,0.0691f,-0.9448f,1.4915f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.9425f,-0.0758f,-0.3679f,0.4516f,-0.0956f,1.0094f,0.0371f,1.0418f,0.3633f,0.0691f,-0.9448f,1.3607f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.235","py":"1.72","pz":"1.522","ry":"339.343","rx":"0.336"},"hitbox":{"px":"0.305","py":"0.396","pz":"1.324","ry":"338.724","rx":"2.094"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args