# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.59f,0.2542f,0.9229f,-0.3376f,-0.2847f,0.9885f,-0.4542f,2.5663f,-0.914f,-0.472f,-0.4543f,1.4613f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.1244f,0.0029f,-0.0131f,0.0048f,0.0023f,1.1233f,0.0515f,2.3607f,0.0132f,0.0515f,-1.1232f,1.3212f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.8091f,0.0034f,-0.0213f,0.0054f,0.0037f,1.809f,-0.0272f,1.5894f,0.0212f,-0.0273f,-1.8089f,1.512f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1244f,0.0033f,-0.013f,-0.3479f,0.0023f,1.1215f,0.0811f,1.9409f,0.0132f,0.0811f,-1.1215f,1.2949f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1244f,0.0033f,-0.013f,0.4252f,0.0023f,1.1215f,0.0811f,1.9393f,0.0132f,0.0811f,-1.1215f,1.2858f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9998f,-0.3459f,0.381f,-0.2856f,-0.0769f,0.9237f,0.6366f,2.1612f,-0.5088f,0.54f,-0.845f,1.1692f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9873f,0.3623f,-0.3981f,0.3469f,0.0811f,0.9223f,0.6382f,2.1599f,0.5322f,0.5316f,-0.8358f,1.1618f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.1244f,0.0033f,-0.013f,0.0014f,0.0023f,1.1215f,0.0811f,1.3609f,0.0132f,0.0811f,-1.1215f,1.2137f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.1244f,0.0023f,-0.0132f,-0.1447f,0.0023f,1.1245f,-0.0015f,1.4527f,0.0132f,-0.0015f,-1.1244f,1.3207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.1244f,0.0023f,-0.0132f,0.2061f,0.0023f,1.1245f,-0.0015f,1.1708f,0.0132f,-0.0015f,-1.1244f,1.3169f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.005","py":"1.93","pz":"1.431","ry":"359.336","rx":"4.138"},"hitbox":{"px":"-0","py":"0.468","pz":"1.25","ry":"359.327","rx":"-0.075"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args