# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5864f,0.2541f,0.9238f,-0.3396f,-0.3304f,0.963f,-0.4747f,2.6035f,-0.8993f,-0.5195f,-0.4279f,1.4352f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.1233f,0.0015f,-0.0099f,0.003f,0.0015f,1.1233f,-0.0047f,2.3919f,0.0099f,-0.0048f,-1.1233f,1.3067f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.8093f,0.002f,-0.016f,0.0038f,0.0024f,1.8085f,-0.0542f,1.6243f,0.0159f,-0.0542f,-1.8085f,1.5088f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1233f,0.0021f,-0.0098f,-0.3488f,0.0015f,1.1215f,0.0644f,1.9718f,0.0099f,0.0643f,-1.1214f,1.2856f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1233f,0.0021f,-0.0098f,0.4235f,0.0015f,1.1215f,0.0644f,1.9708f,0.0099f,0.0643f,-1.1214f,1.2788f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9972f,-0.3479f,0.3826f,-0.2864f,-0.0853f,0.9304f,0.6237f,2.1901f,-0.51f,0.5246f,-0.8524f,1.157f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9879f,0.3596f,-0.3958f,0.3454f,0.088f,0.9294f,0.6247f,2.1892f,0.5275f,0.5184f,-0.8455f,1.1514f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.1233f,0.0021f,-0.0098f,0.0009f,0.0015f,1.1215f,0.0644f,1.3916f,0.0099f,0.0643f,-1.1214f,1.2141f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.1233f,0.0015f,-0.0099f,-0.1455f,0.0015f,1.1233f,-0.001f,1.4832f,0.0099f,-0.001f,-1.1233f,1.3206f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.1233f,0.0015f,-0.0099f,0.2052f,0.0015f,1.1233f,-0.001f,1.2019f,0.0099f,-0.001f,-1.1233f,1.3178f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.003","py":"1.963","pz":"1.423","ry":"359.501","rx":"3.284"},"hitbox":{"px":"-0","py":"0.5","pz":"1.25","ry":"359.497","rx":"-0.049"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args