# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5846f,0.2543f,0.9239f,-0.3403f,-0.3392f,0.9572f,-0.4781f,2.5924f,-0.8962f,-0.5282f,-0.4217f,1.4244f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.1225f,0.001f,-0.0083f,0.0023f,0.0012f,1.1224f,-0.0157f,2.3799f,0.0083f,-0.0157f,-1.1224f,1.2985f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.8084f,0.0014f,-0.0134f,0.0031f,0.0019f,1.8071f,-0.0691f,1.6146f,0.0134f,-0.0691f,-1.807f,1.5068f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1225f,0.0016f,-0.0082f,-0.349f,0.0012f,1.1211f,0.055f,1.9598f,0.0083f,0.055f,-1.1211f,1.2805f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1225f,0.0016f,-0.0082f,0.4226f,0.0012f,1.1211f,0.055f,1.959f,0.0083f,0.055f,-1.1211f,1.2748f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9957f,-0.3487f,0.3832f,-0.2866f,-0.0899f,0.9339f,0.6163f,2.1768f,-0.5103f,0.516f,-0.8564f,1.1502f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9879f,0.3582f,-0.3946f,0.3447f,0.0919f,0.9331f,0.6171f,2.1762f,0.5249f,0.5108f,-0.8506f,1.1455f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.1225f,0.0016f,-0.0082f,0.0007f,0.0012f,1.1211f,0.055f,1.3796f,0.0083f,0.055f,-1.1211f,1.2143f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.1225f,0.0012f,-0.0083f,-0.1458f,0.0012f,1.1225f,-0.0007f,1.471f,0.0083f,-0.0007f,-1.1225f,1.3206f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.1225f,0.0012f,-0.0083f,0.2047f,0.0012f,1.1225f,-0.0007f,1.19f,0.0083f,-0.0007f,-1.1225f,1.3182f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.003","py":"1.953","pz":"1.418","ry":"359.58","rx":"2.81"},"hitbox":{"px":"-0","py":"0.489","pz":"1.25","ry":"359.577","rx":"-0.038"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args