# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5798f,0.2554f,0.9229f,-0.3414f,-0.2097f,1.0189f,-0.4137f,2.4725f,-0.9344f,-0.3872f,-0.4799f,1.4293f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.1195f,0.001f,-0.0043f,0.0008f,0.0004f,1.1106f,0.141f,2.28f,0.0044f,0.141f,-1.1105f,1.2766f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.8024f,0.0002f,-0.0072f,0.0014f,0.0007f,1.7992f,-0.1089f,1.5216f,0.0071f,-0.1089f,-1.7992f,1.5012f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1195f,0.0005f,-0.0044f,-0.3492f,0.0004f,1.1191f,0.03f,1.8605f,0.0044f,0.03f,-1.1191f,1.2667f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1195f,0.0005f,-0.0044f,0.4204f,0.0004f,1.1191f,0.03f,1.8602f,0.0044f,0.03f,-1.1191f,1.2637f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9913f,-0.3502f,0.3847f,-0.2867f,-0.1017f,0.9423f,0.5958f,2.0741f,-0.5102f,0.4926f,-0.8662f,1.1322f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9871f,0.3548f,-0.3911f,0.343f,0.1025f,0.942f,0.5961f,2.0738f,0.518f,0.4898f,-0.8631f,1.1297f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.1195f,0.0005f,-0.0044f,0.0002f,0.0004f,1.1191f,0.03f,1.2808f,0.0044f,0.03f,-1.1191f,1.2148f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.1195f,0.0004f,-0.0044f,-0.1463f,0.0004f,1.1195f,-0.0003f,1.3718f,0.0044f,-0.0003f,-1.1195f,1.3203f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.1195f,0.0004f,-0.0044f,0.2034f,0.0004f,1.1195f,-0.0003f,1.0918f,0.0044f,-0.0003f,-1.1195f,1.319f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.001","py":"1.857","pz":"1.405","ry":"359.774","rx":"1.537"},"hitbox":{"px":"-0","py":"0.392","pz":"1.25","ry":"359.773","rx":"-0.014"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args