# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5792f,0.2559f,0.9226f,-0.3413f,-0.0731f,1.0633f,-0.3409f,2.4344f,-0.9546f,-0.2368f,-0.5337f,1.4526f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.119f,0.0014f,-0.0038f,0.0007f,0.0003f,1.0784f,0.2988f,2.2657f,0.004f,0.2988f,-1.0784f,1.274f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.8013f,-0.0015f,-0.0063f,0.0012f,0.0006f,1.7071f,-0.5749f,1.5081f,0.0064f,-0.5749f,-1.7071f,1.5005f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.119f,0.0004f,-0.004f,-0.3492f,0.0003f,1.1187f,0.0271f,1.8463f,0.004f,0.0271f,-1.1187f,1.2651f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.119f,0.0004f,-0.004f,0.4201f,0.0003f,1.1187f,0.0271f,1.846f,0.004f,0.0271f,-1.1187f,1.2624f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9906f,-0.3504f,0.3848f,-0.2867f,-0.1031f,0.9431f,0.5933f,2.0594f,-0.5101f,0.4898f,-0.8672f,1.1301f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9869f,0.3544f,-0.3906f,0.3428f,0.1037f,0.9429f,0.5936f,2.0592f,0.5171f,0.4873f,-0.8644f,1.1279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.119f,0.0004f,-0.004f,0.0001f,0.0003f,1.1187f,0.0271f,1.2667f,0.004f,0.0271f,-1.1187f,1.2149f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.119f,0.0003f,-0.004f,-0.1463f,0.0003f,1.119f,-0.0002f,1.3577f,0.004f,-0.0002f,-1.119f,1.3203f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.119f,0.0003f,-0.004f,0.2033f,0.0003f,1.119f,-0.0002f,1.0778f,0.004f,-0.0002f,-1.119f,1.3191f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0.001","py":"1.843","pz":"1.404","ry":"359.796","rx":"1.388"},"hitbox":{"px":"-0","py":"0.379","pz":"1.25","ry":"359.796","rx":"-0.011"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args