# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5779f,0.2567f,0.9221f,-0.3413f,0.2163f,1.0842f,-0.1663f,2.3466f,-0.9323f,0.0925f,-0.6101f,1.4896f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.118f,0.0019f,-0.0025f,0.0004f,0.0002f,0.9387f,0.6073f,2.2388f,0.0031f,0.6073f,-0.9387f,1.2691f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.7989f,0f,-0.005f,0.0009f,0.0004f,1.7947f,-0.1222f,1.4831f,0.005f,-0.1222f,-1.7947f,1.4992f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.118f,0.0003f,-0.0031f,-0.3491f,0.0002f,1.1178f,0.0215f,1.8197f,0.0031f,0.0215f,-1.1178f,1.262f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.118f,0.0003f,-0.0031f,0.4196f,0.0002f,1.1178f,0.0215f,1.8196f,0.0031f,0.0215f,-1.1178f,1.2599f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9894f,-0.3505f,0.3851f,-0.2865f,-0.1056f,0.9447f,0.5886f,2.032f,-0.5099f,0.4844f,-0.8691f,1.1262f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9865f,0.3536f,-0.3897f,0.3424f,0.106f,0.9445f,0.5887f,2.0319f,0.5154f,0.4825f,-0.8669f,1.1244f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.118f,0.0003f,-0.0031f,0.0001f,0.0002f,1.1178f,0.0215f,1.2404f,0.0031f,0.0215f,-1.1178f,1.2149f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.118f,0.0002f,-0.0031f,-0.1464f,0.0002f,1.118f,-0.0001f,1.3313f,0.0031f,-0.0001f,-1.118f,1.3202f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.118f,0.0002f,-0.0031f,0.203f,0.0002f,1.118f,-0.0001f,1.0517f,0.0031f,-0.0001f,-1.118f,1.3192f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.001","py":"1.817","pz":"1.401","ry":"359.84","rx":"1.104"},"hitbox":{"px":"-0","py":"0.353","pz":"1.25","ry":"359.84","rx":"-0.007"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args