# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5772f,0.2567f,0.9218f,-0.3413f,0.3057f,1.0696f,-0.1065f,2.3128f,-0.9068f,0.1972f,-0.6227f,1.4964f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.1175f,0.0018f,-0.002f,0.0003f,0.0002f,0.8749f,0.6952f,2.2269f,0.0027f,0.6952f,-0.8749f,1.2668f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.7975f,0f,-0.0044f,0.0008f,0.0003f,1.7931f,-0.1263f,1.472f,0.0043f,-0.1263f,-1.793f,1.4985f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1175f,0.0002f,-0.0027f,-0.349f,0.0002f,1.1174f,0.0189f,1.8079f,0.0027f,0.0189f,-1.1174f,1.2606f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1175f,0.0002f,-0.0027f,0.4193f,0.0002f,1.1174f,0.0189f,1.8078f,0.0027f,0.0189f,-1.1174f,1.2587f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9887f,-0.3506f,0.3852f,-0.2864f,-0.1068f,0.9454f,0.5863f,2.0198f,-0.5098f,0.4819f,-0.8699f,1.1243f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9862f,0.3532f,-0.3892f,0.3422f,0.1071f,0.9453f,0.5864f,2.0197f,0.5146f,0.4802f,-0.8681f,1.1228f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.1175f,0.0002f,-0.0027f,0.0001f,0.0002f,1.1174f,0.0189f,1.2288f,0.0027f,0.0189f,-1.1174f,1.215f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.1175f,0.0002f,-0.0027f,-0.1464f,0.0002f,1.1175f,-0.0001f,1.3197f,0.0027f,-0.0001f,-1.1175f,1.3201f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.1175f,0.0002f,-0.0027f,0.2028f,0.0002f,1.1175f,-0.0001f,1.0402f,0.0027f,-0.0001f,-1.1175f,1.3193f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.001","py":"1.805","pz":"1.399","ry":"359.862","rx":"0.969"},"hitbox":{"px":"-0","py":"0.342","pz":"1.25","ry":"359.861","rx":"-0.006"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args