# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5766f,0.2565f,0.9216f,-0.3413f,0.3261f,1.0643f,-0.0922f,2.2969f,-0.8994f,0.2215f,-0.6243f,1.4959f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.117f,0.0016f,-0.0017f,0.0002f,0.0001f,0.8585f,0.7146f,2.2163f,0.0023f,0.7146f,-0.8585f,1.2646f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.796f,-0.0001f,-0.0037f,0.0006f,0.0002f,1.7913f,-0.1302f,1.4623f,0.0037f,-0.1302f,-1.7913f,1.4979f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.117f,0.0002f,-0.0023f,-0.3489f,0.0001f,1.1169f,0.0164f,1.7975f,0.0023f,0.0164f,-1.1169f,1.2592f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.117f,0.0002f,-0.0023f,0.4191f,0.0001f,1.1169f,0.0164f,1.7974f,0.0023f,0.0164f,-1.1169f,1.2576f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9881f,-0.3507f,0.3853f,-0.2863f,-0.108f,0.946f,0.5841f,2.009f,-0.5097f,0.4794f,-0.8707f,1.1225f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9859f,0.3528f,-0.3887f,0.342f,0.1082f,0.9459f,0.5842f,2.0089f,0.5137f,0.478f,-0.8691f,1.1212f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.117f,0.0002f,-0.0023f,0f,0.0001f,1.1169f,0.0164f,1.2186f,0.0023f,0.0164f,-1.1169f,1.215f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.117f,0.0001f,-0.0023f,-0.1463f,0.0001f,1.117f,-0.0001f,1.3094f,0.0023f,-0.0001f,-1.117f,1.32f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.117f,0.0001f,-0.0023f,0.2027f,0.0001f,1.117f,-0.0001f,1.0301f,0.0023f,-0.0001f,-1.117f,1.3193f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0","py":"1.795","pz":"1.398","ry":"359.883","rx":"0.841"},"hitbox":{"px":"-0","py":"0.332","pz":"1.25","ry":"359.883","rx":"-0.004"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args