# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5735f,0.2554f,0.9203f,-0.3411f,0.3675f,1.0498f,-0.0623f,2.2626f,-0.8815f,0.2716f,-0.6247f,1.4891f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.114f,0.0002f,-0.0003f,0f,0f,0.8214f,0.7526f,2.1933f,0.0004f,0.7526f,-0.8214f,1.2554f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.7874f,0f,-0.0006f,0.0001f,0f,1.7815f,-0.1461f,1.4435f,0.0006f,-0.1461f,-1.7815f,1.495f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.114f,0f,-0.0004f,-0.3481f,0f,1.114f,0.0061f,1.7755f,0.0004f,0.0061f,-1.114f,1.2533f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.114f,0f,-0.0004f,0.4178f,0f,1.114f,0.0061f,1.7755f,0.0004f,0.0061f,-1.114f,1.253f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9846f,-0.3507f,0.3857f,-0.2855f,-0.1125f,0.9478f,0.5745f,1.9851f,-0.509f,0.4688f,-0.8731f,1.1151f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9842f,0.351f,-0.3863f,0.3411f,0.1125f,0.9478f,0.5745f,1.9851f,0.5096f,0.4686f,-0.8728f,1.1149f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.114f,0f,-0.0004f,0f,0f,1.114f,0.0061f,1.1978f,0.0004f,0.0061f,-1.114f,1.2152f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.114f,0f,-0.0004f,-0.1462f,0f,1.114f,0f,1.2883f,0.0004f,0f,-1.114f,1.3197f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.114f,0f,-0.0004f,0.2019f,0f,1.114f,0f,1.0098f,0.0004f,0f,-1.114f,1.3196f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0","py":"1.775","pz":"1.392","ry":"359.982","rx":"0.312"},"hitbox":{"px":"-0","py":"0.314","pz":"1.25","ry":"359.982","rx":"-0"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args