# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5729f,0.2551f,0.92f,-0.341f,0.3641f,1.0502f,-0.0645f,2.2654f,-0.8825f,0.2677f,-0.6238f,1.4872f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.1134f,0f,0f,0f,0f,0.8236f,0.7492f,2.1952f,0f,0.7492f,-0.8236f,1.2541f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.7855f,0f,0f,0f,0f,1.7793f,-0.1484f,1.4462f,0f,-0.1484f,-1.7793f,1.4946f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1134f,0f,0f,-0.3479f,0f,1.1134f,0.0045f,1.7777f,0f,0.0045f,-1.1134f,1.2524f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1134f,0f,0f,0.4175f,0f,1.1134f,0.0045f,1.7777f,0f,0.0045f,-1.1134f,1.2524f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9838f,-0.3506f,0.3858f,-0.2853f,-0.1131f,0.9479f,0.573f,1.987f,-0.5089f,0.4671f,-0.8732f,1.114f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9838f,0.3506f,-0.3858f,0.341f,0.1131f,0.9479f,0.573f,1.987f,0.5089f,0.4671f,-0.8732f,1.114f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.1134f,0f,0f,0f,0f,1.1134f,0.0045f,1.2003f,0f,0.0045f,-1.1134f,1.2152f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.1134f,0f,0f,-0.1461f,0f,1.1134f,0f,1.2907f,0f,0f,-1.1134f,1.3196f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.1134f,0f,0f,0.2018f,0f,1.1134f,0f,1.0124f,0f,0f,-1.1134f,1.3196f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"-0","py":"1.777","pz":"1.392","ry":"0","rx":"0.233"},"hitbox":{"px":"-0","py":"0.317","pz":"1.25","ry":"0","rx":"0"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args