# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5726f,0.255f,0.9194f,-0.3408f,0.3568f,1.0517f,-0.0695f,2.2708f,-0.8849f,0.2591f,-0.6229f,1.4853f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.1127f,0f,0f,0f,0f,0.8291f,0.7421f,2.1989f,0f,0.7421f,-0.8291f,1.2529f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.7834f,0f,0f,0f,0f,1.777f,-0.1503f,1.4506f,0f,-0.1503f,-1.777f,1.4941f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1127f,0f,0f,-0.3477f,0f,1.1127f,0.0032f,1.7816f,0f,0.0032f,-1.1127f,1.2517f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1127f,0f,0f,0.4173f,0f,1.1127f,0.0032f,1.7816f,0f,0.0032f,-1.1127f,1.2517f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9832f,-0.3504f,0.3855f,-0.2851f,-0.1137f,0.9479f,0.5716f,1.9906f,-0.5084f,0.4657f,-0.8734f,1.1132f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9832f,0.3504f,-0.3855f,0.3408f,0.1137f,0.9479f,0.5716f,1.9906f,0.5084f,0.4657f,-0.8734f,1.1132f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.1127f,0f,0f,0f,0f,1.1127f,0.0032f,1.2045f,0f,0.0032f,-1.1127f,1.2152f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.1127f,0f,0f,-0.146f,0f,1.1127f,0f,1.2949f,0f,0f,-1.1127f,1.3195f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.1127f,0f,0f,0.2017f,0f,1.1127f,0f,1.0167f,0f,0f,-1.1127f,1.3195f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"-0","py":"1.781","pz":"1.391","ry":"0","rx":"0.165"},"hitbox":{"px":"-0","py":"0.321","pz":"1.25","ry":"0","rx":"0"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args