# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5703f,0.254f,0.9158f,-0.3394f,0.0586f,1.0754f,-0.2617f,2.3877f,-0.9485f,-0.0862f,-0.5668f,1.4471f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.1084f,0f,0f,0f,0f,1.0171f,0.4403f,2.2465f,0f,0.4403f,-1.0171f,1.2502f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.7689f,0f,0f,0f,0f,1.7622f,-0.1539f,1.5018f,0f,-0.1539f,-1.7622f,1.4925f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1084f,0f,0f,-0.3464f,0f,1.1084f,0.0002f,1.8309f,0f,0.0002f,-1.1084f,1.2501f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1084f,0f,0f,0.4156f,0f,1.1084f,0.0002f,1.8309f,0f,0.0002f,-1.1084f,1.2501f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9794f,-0.349f,0.384f,-0.284f,-0.1146f,0.9454f,0.567f,2.0387f,-0.5061f,0.4613f,-0.8715f,1.1116f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9794f,0.349f,-0.384f,0.3394f,0.1146f,0.9454f,0.567f,2.0387f,0.5061f,0.4613f,-0.8715f,1.1116f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.1084f,0f,0f,0f,0f,1.1084f,0.0002f,1.2559f,0f,0.0002f,-1.1084f,1.2154f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.1084f,0f,0f,-0.1455f,0f,1.1084f,0f,1.346f,0f,0f,-1.1084f,1.3193f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.1084f,0f,0f,0.2009f,0f,1.1084f,0f,1.0689f,0f,0f,-1.1084f,1.3193f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"-0","py":"1.831","pz":"1.389","ry":"0","rx":"0.009"},"hitbox":{"px":"-0","py":"0.376","pz":"1.25","ry":"0","rx":"0"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args