# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5687f,0.2532f,0.9131f,-0.3384f,-0.3475f,0.935f,-0.4757f,2.4999f,-0.8815f,-0.5319f,-0.4015f,1.3719f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.1051f,0f,0f,0f,0f,1.1046f,-0.0317f,2.2892f,0f,-0.0317f,-1.1046f,1.2536f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.7574f,0f,0f,0f,0f,1.7513f,-0.1468f,1.5458f,0f,-0.1468f,-1.7513f,1.4926f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1051f,0f,0f,-0.3453f,0f,1.1051f,0.004f,1.8748f,0f,0.004f,-1.1051f,1.2521f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1051f,0f,0f,0.4144f,0f,1.1051f,0.004f,1.8748f,0f,0.004f,-1.1051f,1.2521f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9765f,-0.348f,0.3829f,-0.2832f,-0.1125f,0.941f,0.5684f,2.0825f,-0.505f,0.4632f,-0.8669f,1.1147f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9765f,0.348f,-0.3829f,0.3384f,0.1125f,0.941f,0.5684f,2.0825f,0.505f,0.4632f,-0.8669f,1.1147f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.1051f,0f,0f,0f,0f,1.1051f,0.004f,1.3017f,0f,0.004f,-1.1051f,1.2155f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.1051f,0f,0f,-0.145f,0f,1.1051f,0f,1.3914f,0f,0f,-1.1051f,1.3191f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.1051f,0f,0f,0.2003f,0f,1.1051f,0f,1.1152f,0f,0f,-1.1051f,1.3191f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"-0","py":"1.874","pz":"1.39","ry":"0","rx":"0.21"},"hitbox":{"px":"-0","py":"0.424","pz":"1.25","ry":"0","rx":"0"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args