# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5678f,0.2528f,0.9116f,-0.3379f,-0.3794f,0.9131f,-0.4895f,2.5239f,-0.8667f,-0.5653f,-0.383f,1.3671f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.1033f,0f,0f,0f,0f,1.1009f,-0.0725f,2.3093f,0f,-0.0725f,-1.1009f,1.2568f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.7511f,0f,0f,0f,0f,1.6496f,-0.5875f,1.5664f,0f,-0.5875f,-1.6496f,1.493f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1033f,0f,0f,-0.3448f,0f,1.1033f,0.0076f,1.8956f,0f,0.0076f,-1.1033f,1.254f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1033f,0f,0f,0.4138f,0f,1.1033f,0.0076f,1.8956f,0f,0.0076f,-1.1033f,1.254f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9749f,-0.3475f,0.3823f,-0.2827f,-0.1107f,0.938f,0.5703f,2.1034f,-0.5046f,0.4656f,-0.8637f,1.1175f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9749f,0.3475f,-0.3823f,0.3379f,0.1107f,0.938f,0.5703f,2.1034f,0.5046f,0.4656f,-0.8637f,1.1175f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.1033f,0f,0f,0f,0f,1.1033f,0.0076f,1.3235f,0f,0.0076f,-1.1033f,1.2155f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.1033f,0f,0f,-0.1448f,0f,1.1033f,0f,1.4131f,0f,0f,-1.1033f,1.319f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.1033f,0f,0f,0.2f,0f,1.1033f,0f,1.1373f,0f,0f,-1.1033f,1.319f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"-0","py":"1.895","pz":"1.392","ry":"0","rx":"0.397"},"hitbox":{"px":"-0","py":"0.448","pz":"1.25","ry":"0","rx":"0"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args