# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5668f,0.2524f,0.9101f,-0.3373f,-0.3822f,0.9094f,-0.4902f,2.5414f,-0.8637f,-0.568f,-0.3804f,1.3701f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.1015f,0f,0f,0f,0f,1.0988f,-0.0768f,2.3267f,0f,-0.0768f,-1.0988f,1.2609f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.7444f,0f,0f,0f,0f,1.7393f,-0.1329f,1.5841f,0f,-0.1329f,-1.7393f,1.4936f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1015f,0f,0f,-0.3442f,0f,1.1014f,0.0121f,1.9137f,0f,0.0121f,-1.1014f,1.2563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1015f,0f,0f,0.4131f,0f,1.1014f,0.0121f,1.9137f,0f,0.0121f,-1.1014f,1.2563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9733f,-0.3469f,0.3816f,-0.2823f,-0.1084f,0.9346f,0.5729f,2.1217f,-0.5042f,0.4686f,-0.8599f,1.1209f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9733f,0.3469f,-0.3816f,0.3373f,0.1084f,0.9346f,0.5729f,2.1217f,0.5042f,0.4686f,-0.8599f,1.1209f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.1015f,0f,0f,0f,0f,1.1014f,0.0121f,1.3427f,0f,0.0121f,-1.1014f,1.2156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.1015f,0f,0f,-0.1446f,0f,1.1015f,0f,1.4322f,0f,0f,-1.1015f,1.3188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.1015f,0f,0f,0.1996f,0f,1.1015f,0f,1.1568f,0f,0f,-1.1015f,1.3188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"-0","py":"1.912","pz":"1.394","ry":"0","rx":"0.632"},"hitbox":{"px":"-0","py":"0.468","pz":"1.25","ry":"0","rx":"0"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args