# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5598f,0.2493f,0.8989f,-0.3332f,0.3889f,1.0152f,-0.0394f,2.3486f,-0.8479f,0.301f,-0.6115f,1.5331f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0879f,0f,0f,0f,0f,0.7758f,0.7626f,2.2889f,0f,0.7626f,-0.7758f,1.3028f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.6907f,0f,0f,0f,0f,1.6895f,-0.0636f,1.5471f,0f,-0.0636f,-1.6895f,1.5042f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.0879f,0f,0f,-0.34f,0f,1.0865f,0.054f,1.8815f,0f,0.054f,-1.0865f,1.2826f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0879f,0f,0f,0.4079f,0f,1.0865f,0.054f,1.8815f,0f,0.054f,-1.0865f,1.2826f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9613f,-0.3426f,0.3769f,-0.2788f,-0.0878f,0.9044f,0.5981f,2.0919f,-0.5017f,0.4981f,-0.8268f,1.1569f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9613f,0.3426f,-0.3769f,0.3332f,0.0878f,0.9044f,0.5981f,2.0919f,0.5017f,0.4981f,-0.8268f,1.1569f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0879f,0f,0f,0f,0f,1.0865f,0.054f,1.3195f,0f,0.054f,-1.0865f,1.2206f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0879f,0f,0f,-0.1428f,0f,1.0879f,0f,1.4079f,0f,0f,-1.0879f,1.3226f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0879f,0f,0f,0.1972f,0f,1.0879f,0f,1.1359f,0f,0f,-1.0879f,1.3226f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"-0","py":"1.875","pz":"1.418","ry":"0","rx":"2.843"},"hitbox":{"px":"-0","py":"0.456","pz":"1.255","ry":"0","rx":"0"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args