# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5519f,0.2458f,0.8862f,-0.3285f,-0.1508f,0.9953f,-0.3699f,2.3019f,-0.9072f,-0.3149f,-0.4776f,1.489f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0725f,0f,0f,0f,0f,1.0548f,0.1943f,2.126f,0f,0.1943f,-1.0548f,1.3339f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.6254f,0f,0f,0f,0f,1.6254f,-0.0075f,1.3885f,0f,-0.0075f,-1.6254f,1.5082f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.0725f,0f,0f,-0.3352f,0f,1.0688f,0.0885f,1.7251f,0f,0.0885f,-1.0688f,1.3007f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0725f,0f,0f,0.4022f,0f,1.0688f,0.0885f,1.7251f,0f,0.0885f,-1.0688f,1.3007f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9477f,-0.3377f,0.3716f,-0.2748f,-0.0702f,0.8749f,0.6163f,1.9366f,-0.4972f,0.5202f,-0.7952f,1.1837f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9477f,0.3377f,-0.3716f,0.3285f,0.0702f,0.8749f,0.6163f,1.9366f,0.4972f,0.5202f,-0.7952f,1.1837f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0725f,0f,0f,0f,0f,1.0688f,0.0885f,1.1734f,0f,0.0885f,-1.0688f,1.2214f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0725f,0f,0f,-0.1408f,0f,1.0725f,0f,1.2606f,0f,0f,-1.0725f,1.3219f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0725f,0f,0f,0.1944f,0f,1.0725f,0f,0.9925f,0f,0f,-1.0725f,1.3219f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"-0","py":"1.714","pz":"1.434","ry":"0","rx":"4.736"},"hitbox":{"px":"-0","py":"0.322","pz":"1.255","ry":"0","rx":"0"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args