# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5512f,0.2454f,0.885f,-0.328f,-0.2382f,0.9586f,-0.4142f,2.3076f,-0.887f,-0.41f,-0.4387f,1.4703f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0711f,0f,0f,0f,0f,1.0673f,0.0903f,2.1177f,0f,0.0903f,-1.0673f,1.3333f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.6193f,0f,0f,0f,0f,1.5629f,-0.4235f,1.3808f,0f,-0.4235f,-1.5629f,1.5061f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.0711f,0f,0f,-0.3347f,0f,1.0673f,0.0903f,1.7175f,0f,0.0903f,-1.0673f,1.2994f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0711f,0f,0f,0.4017f,0f,1.0673f,0.0903f,1.7175f,0f,0.0903f,-1.0673f,1.2994f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9464f,-0.3373f,0.3711f,-0.2745f,-0.0692f,0.8729f,0.6169f,1.9289f,-0.4967f,0.5211f,-0.7931f,1.183f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9464f,0.3373f,-0.3711f,0.328f,0.0692f,0.8729f,0.6169f,1.9289f,0.4967f,0.5211f,-0.7931f,1.183f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0711f,0f,0f,0f,0f,1.0673f,0.0903f,1.1666f,0f,0.0903f,-1.0673f,1.2192f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0711f,0f,0f,-0.1406f,0f,1.0711f,0f,1.2536f,0f,0f,-1.0711f,1.3196f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0711f,0f,0f,0.1941f,0f,1.0711f,0f,0.9859f,0f,0f,-1.0711f,1.3196f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"-0","py":"1.706","pz":"1.433","ry":"0","rx":"4.837"},"hitbox":{"px":"-0","py":"0.316","pz":"1.253","ry":"0","rx":"0"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args