# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5489f,0.2444f,0.8814f,-0.324f,-0.2956f,0.9254f,-0.4407f,2.2926f,-0.8656f,-0.471f,-0.4085f,1.4503f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0668f,0f,0f,0.0027f,0f,1.0666f,0.019f,2.0948f,0f,0.019f,-1.0666f,1.3268f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.6002f,0f,0f,0.0027f,0f,1.6002f,0f,1.3604f,0f,0f,-1.6002f,1.4968f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.0668f,0f,0f,-0.3306f,0f,1.0627f,0.093f,1.6962f,0f,0.093f,-1.0627f,1.2919f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0668f,0f,0f,0.4028f,0f,1.0627f,0.093f,1.6962f,0f,0.093f,-1.0627f,1.2919f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9426f,-0.3359f,0.3696f,-0.2706f,-0.0675f,0.8679f,0.6166f,1.9071f,-0.4949f,0.5215f,-0.7881f,1.1765f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9426f,0.3359f,-0.3696f,0.3294f,0.0675f,0.8679f,0.6166f,1.9071f,0.4949f,0.5215f,-0.7881f,1.1765f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0668f,0f,0f,0.0027f,0f,1.0627f,0.093f,1.1479f,0f,0.093f,-1.0627f,1.2105f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0668f,0f,0f,-0.1373f,0f,1.0668f,0f,1.2345f,0f,0f,-1.0668f,1.3105f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0668f,0f,0f,0.1961f,0f,1.0668f,0f,0.9678f,0f,0f,-1.0668f,1.3105f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.003","py":"1.685","pz":"1.425","ry":"0","rx":"5"},"hitbox":{"px":"0.003","py":"0.301","pz":"1.244","ry":"0","rx":"0"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args