# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5443f,0.2424f,0.8739f,-0.2911f,-0.2327f,0.9477f,-0.4078f,2.1826f,-0.8765f,-0.4021f,-0.4344f,1.4306f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0577f,0f,0f,0.0328f,0f,1.0536f,0.0922f,1.9954f,0f,0.0922f,-1.0536f,1.2948f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0f,0f,0f,0.0328f,0f,0f,0f,1.2673f,0f,0f,0f,1.4634f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.0577f,0f,0f,-0.2978f,0f,1.0536f,0.0922f,1.6003f,0f,0.0922f,-1.0536f,1.2603f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0577f,0f,0f,0.4294f,0f,1.0536f,0.0922f,1.6003f,0f,0.0922f,-1.0536f,1.2603f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9346f,-0.3331f,0.3665f,-0.2383f,-0.0669f,0.8605f,0.6114f,1.8093f,-0.4907f,0.517f,-0.7814f,1.1458f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9346f,0.3331f,-0.3665f,0.3567f,0.0669f,0.8605f,0.6114f,1.8093f,0.4907f,0.517f,-0.7814f,1.1458f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0577f,0f,0f,0.0328f,0f,1.0536f,0.0922f,1.0566f,0f,0.0922f,-1.0536f,1.1795f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0577f,0f,0f,-0.106f,0f,1.0577f,0f,1.1425f,0f,0f,-1.0577f,1.2787f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0577f,0f,0f,0.2245f,0f,1.0577f,0f,0.8781f,0f,0f,-1.0577f,1.2787f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0.033","py":"1.589","pz":"1.392","ry":"0","rx":"5"},"hitbox":{"px":"0.033","py":"0.217","pz":"1.213","ry":"0","rx":"0"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] run function aj:fine_print/variants/sad_mask/apply
execute unless entity @s[tag=aj.transforms_only] at @s run function aj:fine_print/animations/bring_item/zzz/frames/208_root_function