# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5418f,0.2413f,0.8699f,-0.2708f,-0.1557f,0.9744f,-0.3672f,2.1139f,-0.8892f,-0.3176f,-0.4657f,1.4256f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0529f,0f,0f,0.0516f,0f,1.0371f,0.1817f,1.9399f,0f,0.1817f,-1.0371f,1.2749f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0f,0f,0f,0.0516f,0f,0f,0f,1.2152f,0f,0f,0f,1.4427f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.0529f,0f,0f,-0.2774f,0f,1.0489f,0.0918f,1.5466f,0f,0.0918f,-1.0489f,1.2405f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0529f,0f,0f,0.4465f,0f,1.0489f,0.0918f,1.5466f,0f,0.0918f,-1.0489f,1.2405f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9303f,-0.3316f,0.3648f,-0.2182f,-0.0666f,0.8566f,0.6086f,1.7547f,-0.4884f,0.5147f,-0.7779f,1.1266f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9303f,0.3316f,-0.3648f,0.3741f,0.0666f,0.8566f,0.6086f,1.7547f,0.4884f,0.5147f,-0.7779f,1.1266f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0529f,0f,0f,0.0516f,0f,1.0489f,0.0918f,1.0054f,0f,0.0918f,-1.0489f,1.1601f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0529f,0f,0f,-0.0866f,0f,1.0529f,0f,1.0909f,0f,0f,-1.0529f,1.2588f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0529f,0f,0f,0.2425f,0f,1.0529f,0f,0.8277f,0f,0f,-1.0529f,1.2588f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.052","py":"1.535","pz":"1.372","ry":"0","rx":"5"},"hitbox":{"px":"0.052","py":"0.17","pz":"1.193","ry":"0","rx":"0"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args