# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5357f,0.2385f,0.8601f,-0.2451f,0.1242f,1.0133f,-0.2037f,1.9991f,-0.8839f,-0.0022f,-0.5499f,1.4249f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.041f,0f,0f,0.0737f,0f,0.9203f,0.4866f,1.8813f,0f,0.4866f,-0.9203f,1.2301f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0f,0f,0f,0.0737f,0f,0f,0f,1.1647f,0f,0f,0f,1.396f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.041f,0f,0f,-0.2516f,0f,1.037f,0.0907f,1.4924f,0f,0.0907f,-1.037f,1.1961f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.041f,0f,0f,0.4641f,0f,1.037f,0.0907f,1.4924f,0f,0.0907f,-1.037f,1.1961f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9199f,-0.3278f,0.3607f,-0.193f,-0.0659f,0.8469f,0.6017f,1.6982f,-0.4829f,0.5089f,-0.7691f,1.0834f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9199f,0.3278f,-0.3607f,0.3925f,0.0659f,0.8469f,0.6017f,1.6982f,0.4829f,0.5089f,-0.7691f,1.0834f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.041f,0f,0f,0.0737f,0f,1.037f,0.0907f,0.9573f,0f,0.0907f,-1.037f,1.1166f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.041f,0f,0f,-0.0629f,0f,1.041f,0f,1.0419f,0f,0f,-1.041f,1.2142f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.041f,0f,0f,0.2624f,0f,1.041f,0f,0.7816f,0f,0f,-1.041f,1.2142f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0.074","py":"1.481","pz":"1.326","ry":"0","rx":"5"},"hitbox":{"px":"0.074","py":"0.131","pz":"1.149","ry":"0","rx":"0"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args