# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5291f,0.2356f,0.8496f,-0.2971f,0.267f,0.9871f,-0.1075f,2.1316f,-0.8403f,0.1653f,-0.5691f,1.4146f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0282f,0f,0f,0.0178f,0f,0.8158f,0.626f,2.049f,0f,0.626f,-0.8158f,1.2054f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0f,0f,0f,0.0178f,0f,0f,0f,1.3412f,0f,0f,0f,1.3693f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.0282f,0f,0f,-0.3035f,0f,1.0243f,0.0896f,1.6649f,0f,0.0896f,-1.0243f,1.1718f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0282f,0f,0f,0.4034f,0f,1.0243f,0.0896f,1.6649f,0f,0.0896f,-1.0243f,1.1718f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9086f,-0.3238f,0.3563f,-0.2457f,-0.0651f,0.8365f,0.5944f,1.8682f,-0.477f,0.5026f,-0.7597f,1.0606f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9086f,0.3238f,-0.3563f,0.3327f,0.0651f,0.8365f,0.5944f,1.8682f,0.477f,0.5026f,-0.7597f,1.0606f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0282f,0f,0f,0.0178f,0f,1.0243f,0.0896f,1.1364f,0f,0.0896f,-1.0243f,1.0933f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0282f,0f,0f,-0.1172f,0f,1.0282f,0f,1.2199f,0f,0f,-1.0282f,1.1897f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0282f,0f,0f,0.2041f,0f,1.0282f,0f,0.9628f,0f,0f,-1.0282f,1.1897f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0.018","py":"1.654","pz":"1.3","ry":"0","rx":"5"},"hitbox":{"px":"0.018","py":"0.32","pz":"1.125","ry":"0","rx":"0"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args