# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6026f,0.1981f,0.8187f,-0.2791f,-0.2934f,0.8942f,-0.4323f,2.3174f,-0.7896f,-0.4835f,-0.4641f,1.4083f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0319f,0.0022f,-0.088f,0.0267f,0.0013f,1.0356f,0.0096f,2.1239f,0.088f,0.0094f,-1.0319f,1.2635f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.5489f,-0.0083f,-0.1318f,0.0445f,0.002f,1.5498f,-0.1212f,1.426f,0.1321f,-0.1209f,-1.5442f,1.4829f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.0319f,0.0022f,-0.088f,-0.2966f,0.0013f,1.0356f,0.0096f,1.736f,0.088f,0.0094f,-1.0319f,1.2875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0319f,0.0022f,-0.088f,0.4128f,0.0013f,1.0356f,0.0096f,1.7351f,0.088f,0.0094f,-1.0319f,1.227f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9522f,-0.2865f,0.2895f,-0.2492f,-0.1016f,0.8799f,0.5367f,1.9313f,-0.3944f,0.4651f,-0.8371f,1.1553f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.8714f,0.3634f,-0.4256f,0.3313f,0.104f,0.879f,0.5376f,1.9305f,0.5499f,0.4097f,-0.7761f,1.1058f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0319f,0.0022f,-0.088f,0.022f,0.0013f,1.0356f,0.0096f,1.1986f,0.088f,0.0094f,-1.0319f,1.2228f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0319f,0.0013f,-0.088f,-0.1051f,0.0013f,1.0356f,-0.0008f,1.283f,0.088f,-0.0009f,-1.0319f,1.3311f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0319f,0.0013f,-0.088f,0.2171f,0.0013f,1.0356f,-0.0008f,1.0237f,0.088f,-0.0009f,-1.0319f,1.3038f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.037","py":"1.734","pz":"1.389","ry":"355.128","rx":"0.53"},"hitbox":{"px":"0.024","py":"0.377","pz":"1.256","ry":"355.127","rx":"-0.042"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args