# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6038f,0.2007f,0.8216f,-0.3106f,-0.2886f,0.9f,-0.432f,2.3213f,-0.795f,-0.4792f,-0.4672f,1.4071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0356f,0.0035f,-0.0867f,-0.0039f,0.0022f,1.0391f,0.0162f,2.1276f,0.0867f,0.016f,-1.0355f,1.2611f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.5552f,-0.0061f,-0.1302f,0.0127f,0.0033f,1.5566f,-0.1117f,1.4259f,0.1303f,-0.1116f,-1.5512f,1.4768f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.0356f,0.0035f,-0.0867f,-0.3288f,0.0022f,1.0391f,0.0162f,1.7386f,0.0867f,0.016f,-1.0355f,1.2822f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0356f,0.0035f,-0.0867f,0.3831f,0.0022f,1.0391f,0.0162f,1.7371f,0.0867f,0.016f,-1.0355f,1.2225f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.955f,-0.287f,0.2924f,-0.2808f,-0.0982f,0.8804f,0.5435f,1.9354f,-0.3978f,0.4718f,-0.8361f,1.1509f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.8751f,0.3652f,-0.4252f,0.3018f,0.102f,0.879f,0.545f,1.9341f,0.5511f,0.4172f,-0.776f,1.1021f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0356f,0.0035f,-0.0867f,-0.0098f,0.0022f,1.0391f,0.0162f,1.1994f,0.0867f,0.016f,-1.0355f,1.2144f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0356f,0.0021f,-0.0867f,-0.1374f,0.0022f,1.0392f,-0.0012f,1.2842f,0.0867f,-0.0014f,-1.0356f,1.3228f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0356f,0.0021f,-0.0867f,0.1857f,0.0022f,1.0392f,-0.0012f,1.0238f,0.0867f,-0.0014f,-1.0356f,1.296f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.006","py":"1.736","pz":"1.384","ry":"355.214","rx":"0.895"},"hitbox":{"px":"-0.009","py":"0.375","pz":"1.248","ry":"355.212","rx":"-0.068"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args