# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6083f,0.2111f,0.833f,-0.3104f,-0.2636f,0.9256f,-0.427f,2.3459f,-0.8179f,-0.4553f,-0.4819f,1.4409f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0497f,0.0089f,-0.0813f,0.0002f,0.0051f,1.0517f,0.0499f,2.1528f,0.0816f,0.0494f,-1.0485f,1.2887f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.5806f,-0.0292f,-0.1196f,0.012f,0.0077f,1.5138f,-0.471f,1.4353f,0.1229f,-0.4701f,-1.509f,1.4849f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.0497f,0.0089f,-0.0813f,-0.3311f,0.0051f,1.0517f,0.0499f,1.76f,0.0816f,0.0494f,-1.0485f,1.2957f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0497f,0.0089f,-0.0813f,0.3905f,0.0051f,1.0517f,0.0499f,1.7565f,0.0816f,0.0494f,-1.0485f,1.2396f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9656f,-0.2891f,0.3044f,-0.2806f,-0.0815f,0.878f,0.5754f,1.9631f,-0.4118f,0.5041f,-0.8276f,1.1693f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.8895f,0.372f,-0.423f,0.3099f,0.0905f,0.8748f,0.5789f,1.9603f,0.556f,0.4527f,-0.771f,1.1234f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0497f,0.0089f,-0.0813f,-0.0103f,0.0051f,1.0517f,0.0499f,1.2144f,0.0816f,0.0494f,-1.0485f,1.2118f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0497f,0.0048f,-0.0816f,-0.14f,0.0051f,1.0528f,-0.0029f,1.3009f,0.0816f,-0.0033f,-1.0497f,1.3206f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0497f,0.0048f,-0.0816f,0.1868f,0.0051f,1.0528f,-0.0029f,1.0361f,0.0816f,-0.0033f,-1.0497f,1.296f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0.007","py":"1.752","pz":"1.401","ry":"355.568","rx":"2.717"},"hitbox":{"px":"-0.012","py":"0.379","pz":"1.247","ry":"355.555","rx":"-0.157"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args