# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6108f,0.2233f,0.8341f,-0.299f,-0.1514f,0.9782f,-0.3728f,2.3354f,-0.8501f,-0.3346f,-0.5329f,1.4777f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0547f,0.0198f,-0.0773f,0.0116f,0.006f,1.0414f,0.1849f,2.1592f,0.0796f,0.1839f,-1.0385f,1.302f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.5902f,0.0057f,-0.1202f,0.0217f,0.009f,1.5941f,-0.0442f,1.436f,0.12f,-0.0448f,-1.5896f,1.4904f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.0547f,0.0107f,-0.0791f,-0.322f,0.006f,1.0558f,0.0629f,1.7651f,0.0796f,0.0623f,-1.0528f,1.3035f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0547f,0.0107f,-0.0791f,0.4031f,0.006f,1.0558f,0.0629f,1.761f,0.0796f,0.0623f,-1.0528f,1.2488f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9691f,-0.2901f,0.3087f,-0.2705f,-0.0752f,0.8763f,0.5874f,1.9706f,-0.4169f,0.5163f,-0.8236f,1.1791f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.8947f,0.3741f,-0.4221f,0.3227f,0.0858f,0.8726f,0.5915f,1.9672f,0.5575f,0.4661f,-0.7685f,1.1343f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0547f,0.0107f,-0.0791f,-0.0004f,0.006f,1.0558f,0.0629f,1.2175f,0.0796f,0.0623f,-1.0528f,1.2134f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0547f,0.0057f,-0.0796f,-0.1309f,0.006f,1.0577f,-0.0034f,1.3046f,0.0796f,-0.0038f,-1.0547f,1.3224f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0547f,0.0057f,-0.0796f,0.1972f,0.006f,1.0577f,-0.0034f,1.0383f,0.0796f,-0.0038f,-1.0547f,1.2985f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.017","py":"1.755","pz":"1.41","ry":"355.704","rx":"3.411"},"hitbox":{"px":"-0.002","py":"0.378","pz":"1.249","ry":"355.684","rx":"-0.185"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args