# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6114f,0.2381f,0.8335f,-0.2944f,0.0059f,1.0211f,-0.2874f,2.3086f,-0.8668f,-0.161f,-0.5899f,1.5131f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0579f,0.0329f,-0.0713f,0.0154f,0.0065f,0.9966f,0.3633f,2.1606f,0.0782f,0.3619f,-0.9941f,1.3094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.5967f,0.0074f,-0.1182f,0.0245f,0.0099f,1.6007f,-0.0325f,1.434f,0.1181f,-0.0332f,-1.5964f,1.4931f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.0579f,0.0117f,-0.0776f,-0.3196f,0.0065f,1.0584f,0.071f,1.7657f,0.0782f,0.0703f,-1.0556f,1.3075f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0579f,0.0117f,-0.0776f,0.4077f,0.0065f,1.0584f,0.071f,1.7612f,0.0782f,0.0703f,-1.0556f,1.2537f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9714f,-0.2908f,0.3115f,-0.2676f,-0.0713f,0.8754f,0.5948f,1.9727f,-0.4202f,0.5238f,-0.8212f,1.1843f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.8981f,0.3754f,-0.4216f,0.3275f,0.0829f,0.8713f,0.5994f,1.969f,0.5584f,0.4745f,-0.767f,1.1403f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0579f,0.0117f,-0.0776f,0.0025f,0.0065f,1.0584f,0.071f,1.2169f,0.0782f,0.0703f,-1.0556f,1.2136f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0579f,0.0062f,-0.0782f,-0.1285f,0.0065f,1.0608f,-0.0037f,1.3043f,0.0782f,-0.0042f,-1.0579f,1.3227f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0579f,0.0062f,-0.0782f,0.2005f,0.0065f,1.0608f,-0.0037f,1.037f,0.0782f,-0.0042f,-1.0579f,1.2993f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.021","py":"1.755","pz":"1.415","ry":"355.795","rx":"3.836"},"hitbox":{"px":"-0","py":"0.375","pz":"1.25","ry":"355.77","rx":"-0.201"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args