# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [0.5799f,-0.0441f,0.3962f,-1.2133f,0.2027f,0.6349f,-0.226f,1.1715f,-0.3432f,0.3004f,0.5359f,-0.1376f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.0188f,-0.3733f,0.5962f,-1.0705f,0.1456f,0.5815f,0.3686f,1.0593f,-0.6882f,0.1332f,0.0617f,0.0552f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0f,0f,0f,-0.9501f,0f,0f,0f,0.588f,0f,0f,0f,-0.0478f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.0188f,-0.3733f,0.5962f,-0.9364f,0.1456f,0.5815f,0.3686f,0.8868f,-0.6882f,0.1332f,0.0617f,-0.2099f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.0188f,-0.3733f,0.5962f,-0.9234f,0.1456f,0.5815f,0.3686f,0.7867f,-0.6882f,0.1332f,0.0617f,0.2633f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [0.0498f,-0.4324f,0.5529f,-0.9308f,0.1673f,0.5456f,0.4117f,1.0337f,-0.6817f,0.1023f,0.1415f,-0.1385f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.3275f,-0.5606f,0.2714f,-0.9202f,0.0205f,0.2968f,0.6377f,0.9518f,-0.6225f,0.3047f,-0.1218f,0.2487f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-0.0188f,-0.3733f,0.5962f,-0.7182f,0.1456f,0.5815f,0.3686f,0.5512f,-0.6882f,0.1332f,0.0617f,-0.0619f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [0.0733f,-0.1444f,0.6848f,-0.7385f,0.0131f,0.6887f,0.1438f,0.5651f,-0.6998f,-0.0022f,0.0744f,-0.1567f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [0.0733f,-0.197f,0.6716f,-0.7233f,0.0131f,0.6755f,0.1968f,0.4425f,-0.6998f,-0.008f,0.074f,0.0638f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"-1.005","py":"0.795","pz":"-0.002","ry":"95.907","rx":"31.59"},"hitbox":{"px":"-0.625","py":"0","pz":"-0.063","ry":"96.203","rx":"11.793"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] at @s run function aj:fine_print/animations/bring_item/zzz/frames/4_root_function