# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6092f,0.257f,0.8371f,-0.2927f,0.2061f,1.0332f,-0.1672f,2.2645f,-0.8511f,0.0663f,-0.6397f,1.5521f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0641f,0.047f,-0.0595f,0.0177f,0.0075f,0.8982f,0.5755f,2.1585f,0.0754f,0.5736f,-0.8963f,1.3206f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.6097f,-0.0195f,-0.113f,0.025f,0.0113f,1.5552f,-0.4306f,1.4256f,0.1141f,-0.4303f,-1.5511f,1.4966f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.0641f,0.0134f,-0.0746f,-0.3199f,0.0075f,1.0634f,0.0841f,1.762f,0.0754f,0.0834f,-1.0608f,1.3129f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0641f,0.0134f,-0.0746f,0.4117f,0.0075f,1.0634f,0.0841f,1.7569f,0.0754f,0.0834f,-1.0608f,1.261f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9757f,-0.2926f,0.3169f,-0.2669f,-0.065f,0.8745f,0.6075f,1.9715f,-0.4264f,0.5363f,-0.8177f,1.1917f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9048f,0.3776f,-0.4205f,0.3317f,0.0783f,0.8698f,0.6126f,1.9673f,0.5597f,0.4888f,-0.7654f,1.1493f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0641f,0.0134f,-0.0746f,0.0033f,0.0075f,1.0634f,0.0841f,1.2107f,0.0754f,0.0834f,-1.0608f,1.2129f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0641f,0.0072f,-0.0755f,-0.1287f,0.0075f,1.0668f,-0.0043f,1.2987f,0.0754f,-0.0048f,-1.0641f,1.3222f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0641f,0.0072f,-0.0755f,0.2021f,0.0075f,1.0668f,-0.0043f,1.0297f,0.0754f,-0.0048f,-1.0641f,1.2998f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0.022","py":"1.749","pz":"1.422","ry":"355.977","rx":"4.523"},"hitbox":{"px":"-0","py":"0.364","pz":"1.25","ry":"355.943","rx":"-0.231"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] at @s run function aj:fine_print/animations/bring_item/zzz/frames/43_root_function