# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.609f,0.2596f,0.8402f,-0.2929f,0.227f,1.0338f,-0.1549f,2.2562f,-0.8496f,0.0901f,-0.6437f,1.5584f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0671f,0.0479f,-0.057f,0.0185f,0.0079f,0.8874f,0.5972f,2.1545f,0.074f,0.5953f,-0.8856f,1.3244f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.6162f,0.0115f,-0.1122f,0.0251f,0.012f,1.6201f,-0.0069f,1.4189f,0.1121f,-0.0077f,-1.6162f,1.498f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.0671f,0.014f,-0.0731f,-0.3202f,0.0079f,1.066f,0.0887f,1.7573f,0.074f,0.0879f,-1.0635f,1.3146f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0671f,0.014f,-0.0731f,0.4134f,0.0079f,1.066f,0.0887f,1.7518f,0.074f,0.0879f,-1.0635f,1.2637f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9777f,-0.2937f,0.3194f,-0.2667f,-0.0628f,0.8749f,0.6122f,1.9678f,-0.4293f,0.5408f,-0.817f,1.194f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9081f,0.3784f,-0.4201f,0.3335f,0.0768f,0.8699f,0.6177f,1.9633f,0.5601f,0.4942f,-0.7657f,1.1523f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0671f,0.014f,-0.0731f,0.0037f,0.0079f,1.066f,0.0887f,1.2046f,0.074f,0.0879f,-1.0635f,1.2126f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0671f,0.0076f,-0.0741f,-0.1288f,0.0079f,1.0696f,-0.0046f,1.293f,0.074f,-0.0051f,-1.0671f,1.322f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0671f,0.0076f,-0.0741f,0.2028f,0.0079f,1.0696f,-0.0046f,1.0231f,0.074f,-0.0051f,-1.0671f,1.3001f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.022","py":"1.744","pz":"1.424","ry":"356.067","rx":"4.756"},"hitbox":{"px":"-0","py":"0.356","pz":"1.25","ry":"356.03","rx":"-0.244"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args