# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6089f,0.2631f,0.8463f,-0.2939f,0.2515f,1.0359f,-0.1411f,2.2415f,-0.8498f,0.118f,-0.6481f,1.5628f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0729f,0.0483f,-0.053f,0.0196f,0.0086f,0.8763f,0.623f,2.1447f,0.0712f,0.6212f,-0.8747f,1.3261f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.6292f,-0.0156f,-0.1077f,0.0251f,0.0131f,1.5761f,-0.4265f,1.405f,0.1081f,-0.4264f,-1.5724f,1.4994f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.0729f,0.0146f,-0.0702f,-0.3211f,0.0086f,1.0713f,0.091f,1.7456f,0.0712f,0.0903f,-1.0691f,1.3145f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0729f,0.0146f,-0.0702f,0.4165f,0.0086f,1.0713f,0.091f,1.7397f,0.0712f,0.0903f,-1.0691f,1.2656f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9816f,-0.2962f,0.324f,-0.2668f,-0.0617f,0.8788f,0.6165f,1.9574f,-0.4346f,0.5442f,-0.8192f,1.1938f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9144f,0.3795f,-0.4194f,0.3367f,0.0769f,0.8733f,0.6225f,1.9525f,0.5604f,0.4994f,-0.7699f,1.1538f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0729f,0.0146f,-0.0702f,0.0044f,0.0086f,1.0713f,0.091f,1.19f,0.0712f,0.0903f,-1.0691f,1.2121f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0729f,0.0083f,-0.0712f,-0.1291f,0.0086f,1.0752f,-0.005f,1.279f,0.0712f,-0.0056f,-1.0729f,1.3215f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0729f,0.0083f,-0.0712f,0.2041f,0.0086f,1.0752f,-0.005f,1.0075f,0.0712f,-0.0056f,-1.0729f,1.3007f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0.023","py":"1.732","pz":"1.426","ry":"356.245","rx":"4.857"},"hitbox":{"px":"-0","py":"0.337","pz":"1.25","ry":"356.203","rx":"-0.266"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args