# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6089f,0.2643f,0.8493f,-0.2946f,0.2578f,1.0375f,-0.138f,2.2357f,-0.8513f,0.1252f,-0.6492f,1.5644f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0756f,0.048f,-0.0513f,0.0201f,0.0089f,0.8745f,0.6301f,2.1399f,0.0697f,0.6283f,-0.8731f,1.327f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.6357f,0.0134f,-0.106f,0.0251f,0.0136f,1.6391f,-0.0027f,1.3982f,0.106f,-0.0036f,-1.6357f,1.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.0756f,0.0149f,-0.0687f,-0.3216f,0.0089f,1.0739f,0.0921f,1.7399f,0.0697f,0.0914f,-1.0718f,1.3145f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0756f,0.0149f,-0.0687f,0.4179f,0.0089f,1.0739f,0.0921f,1.7338f,0.0697f,0.0914f,-1.0718f,1.2666f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9833f,-0.2975f,0.3263f,-0.2669f,-0.0611f,0.8806f,0.6186f,1.9523f,-0.4373f,0.5458f,-0.8202f,1.1937f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9175f,0.38f,-0.4191f,0.3381f,0.077f,0.875f,0.6248f,1.9473f,0.5604f,0.5019f,-0.7719f,1.1545f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0756f,0.0149f,-0.0687f,0.0046f,0.0089f,1.0739f,0.0921f,1.1829f,0.0697f,0.0914f,-1.0718f,1.2118f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0756f,0.0086f,-0.0697f,-0.1293f,0.0089f,1.0779f,-0.0052f,1.2722f,0.0697f,-0.0058f,-1.0756f,1.3213f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0756f,0.0086f,-0.0697f,0.2047f,0.0089f,1.0779f,-0.0052f,0.9999f,0.0697f,-0.0058f,-1.0756f,1.301f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.023","py":"1.726","pz":"1.427","ry":"356.333","rx":"4.904"},"hitbox":{"px":"-0","py":"0.328","pz":"1.25","ry":"356.29","rx":"-0.276"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args