# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6089f,0.2647f,0.8508f,-0.2949f,0.2595f,1.0385f,-0.1374f,2.2335f,-0.8524f,0.1271f,-0.6496f,1.565f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.077f,0.0478f,-0.0506f,0.0203f,0.0091f,0.8747f,0.6321f,2.1378f,0.069f,0.6304f,-0.8732f,1.3274f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.6389f,0.0137f,-0.105f,0.0251f,0.0138f,1.6423f,-0.0021f,1.3951f,0.105f,-0.003f,-1.639f,1.5004f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.077f,0.015f,-0.0679f,-0.3219f,0.0091f,1.0752f,0.0927f,1.7374f,0.069f,0.0919f,-1.0731f,1.3145f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.077f,0.015f,-0.0679f,0.4185f,0.0091f,1.0752f,0.0927f,1.7312f,0.069f,0.0919f,-1.0731f,1.2671f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9842f,-0.2981f,0.3274f,-0.267f,-0.0609f,0.8815f,0.6196f,1.9501f,-0.4386f,0.5466f,-0.8207f,1.1937f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9191f,0.3802f,-0.4189f,0.3388f,0.077f,0.8758f,0.6259f,1.945f,0.5605f,0.5032f,-0.7729f,1.1549f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.077f,0.015f,-0.0679f,0.0048f,0.0091f,1.0752f,0.0927f,1.1797f,0.069f,0.0919f,-1.0731f,1.2117f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.077f,0.0087f,-0.069f,-0.1294f,0.0091f,1.0792f,-0.0053f,1.2691f,0.069f,-0.0058f,-1.077f,1.3213f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.077f,0.0087f,-0.069f,0.205f,0.0091f,1.0792f,-0.0053f,0.9965f,0.069f,-0.0058f,-1.077f,1.3012f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.023","py":"1.723","pz":"1.427","ry":"356.377","rx":"4.927"},"hitbox":{"px":"-0","py":"0.323","pz":"1.25","ry":"356.333","rx":"-0.28"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args