# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.609f,0.2653f,0.8538f,-0.2957f,0.26f,1.041f,-0.1381f,2.2308f,-0.8554f,0.1274f,-0.6498f,1.5658f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0796f,0.0471f,-0.0493f,0.0206f,0.0093f,0.8769f,0.6334f,2.1348f,0.0675f,0.6317f,-0.8756f,1.3282f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.6454f,-0.013f,-0.103f,0.025f,0.0142f,1.5922f,-0.4275f,1.3902f,0.1029f,-0.4275f,-1.5889f,1.501f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.0796f,0.0151f,-0.0664f,-0.3224f,0.0093f,1.0777f,0.0937f,1.7335f,0.0675f,0.093f,-1.0757f,1.3144f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0796f,0.0151f,-0.0664f,0.4198f,0.0093f,1.0777f,0.0937f,1.7271f,0.0675f,0.093f,-1.0757f,1.268f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9859f,-0.2994f,0.3296f,-0.2672f,-0.0605f,0.8833f,0.6216f,1.9468f,-0.4412f,0.5481f,-0.8217f,1.1936f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9221f,0.3805f,-0.4186f,0.3401f,0.077f,0.8774f,0.6281f,1.9415f,0.5604f,0.5056f,-0.7749f,1.1556f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0796f,0.0151f,-0.0664f,0.005f,0.0093f,1.0777f,0.0937f,1.1745f,0.0675f,0.093f,-1.0757f,1.2115f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0796f,0.009f,-0.0675f,-0.1296f,0.0093f,1.0817f,-0.0054f,1.2641f,0.0675f,-0.006f,-1.0797f,1.3211f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0796f,0.009f,-0.0675f,0.2055f,0.0093f,1.0817f,-0.0054f,0.9908f,0.0675f,-0.006f,-1.0797f,1.3015f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0.023","py":"1.719","pz":"1.428","ry":"356.465","rx":"4.97"},"hitbox":{"px":"-0","py":"0.316","pz":"1.25","ry":"356.42","rx":"-0.287"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args