# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6091f,0.2655f,0.8553f,-0.2961f,0.2587f,1.0424f,-0.1394f,2.2305f,-0.8574f,0.1259f,-0.6497f,1.5661f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0809f,0.0466f,-0.0487f,0.0208f,0.0094f,0.8791f,0.6325f,2.134f,0.0668f,0.6308f,-0.8778f,1.3286f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.6486f,0.0144f,-0.1018f,0.0249f,0.0144f,1.6517f,-0.0002f,1.3885f,0.1018f,-0.0011f,-1.6486f,1.5014f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.0809f,0.0152f,-0.0657f,-0.3227f,0.0094f,1.0789f,0.0942f,1.7323f,0.0668f,0.0935f,-1.0769f,1.3144f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0809f,0.0152f,-0.0657f,0.4204f,0.0094f,1.0789f,0.0942f,1.7258f,0.0668f,0.0935f,-1.0769f,1.2685f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9867f,-0.3001f,0.3306f,-0.2673f,-0.0603f,0.8841f,0.6226f,1.9459f,-0.4424f,0.5488f,-0.8222f,1.1936f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9236f,0.3807f,-0.4184f,0.3407f,0.077f,0.8782f,0.6292f,1.9406f,0.5604f,0.5068f,-0.7759f,1.156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0809f,0.0152f,-0.0657f,0.0051f,0.0094f,1.0789f,0.0942f,1.1726f,0.0668f,0.0935f,-1.0769f,1.2114f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0809f,0.0091f,-0.0668f,-0.1297f,0.0094f,1.083f,-0.0055f,1.2624f,0.0668f,-0.0061f,-1.081f,1.321f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0809f,0.0091f,-0.0668f,0.2058f,0.0094f,1.083f,-0.0055f,0.9887f,0.0668f,-0.0061f,-1.081f,1.3017f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.023","py":"1.718","pz":"1.428","ry":"356.509","rx":"4.991"},"hitbox":{"px":"-0","py":"0.313","pz":"1.25","ry":"356.463","rx":"-0.291"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args