# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6092f,0.2656f,0.8567f,-0.2965f,0.2564f,1.044f,-0.1414f,2.2311f,-0.8595f,0.1232f,-0.6494f,1.5662f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0822f,0.0462f,-0.0482f,0.0209f,0.0095f,0.8819f,0.6307f,2.1338f,0.066f,0.629f,-0.8807f,1.329f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.6518f,-0.012f,-0.1011f,0.0248f,0.0146f,1.5986f,-0.428f,1.3874f,0.1008f,-0.4281f,-1.5954f,1.5017f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.0822f,0.0153f,-0.0649f,-0.323f,0.0095f,1.0801f,0.0947f,1.7317f,0.066f,0.094f,-1.0782f,1.3144f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0822f,0.0153f,-0.0649f,0.421f,0.0095f,1.0801f,0.0947f,1.7252f,0.066f,0.094f,-1.0782f,1.269f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9875f,-0.3008f,0.3317f,-0.2674f,-0.0601f,0.885f,0.6236f,1.9455f,-0.4437f,0.5495f,-0.8227f,1.1935f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.925f,0.3808f,-0.4182f,0.3413f,0.0769f,0.879f,0.6302f,1.9402f,0.5604f,0.508f,-0.7769f,1.1564f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0822f,0.0153f,-0.0649f,0.0052f,0.0095f,1.0801f,0.0947f,1.1714f,0.066f,0.094f,-1.0782f,1.2113f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0822f,0.0092f,-0.0661f,-0.1299f,0.0095f,1.0842f,-0.0056f,1.2613f,0.066f,-0.0061f,-1.0822f,1.3209f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0822f,0.0092f,-0.0661f,0.206f,0.0095f,1.0842f,-0.0056f,0.9872f,0.066f,-0.0061f,-1.0822f,1.3018f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0.023","py":"1.717","pz":"1.429","ry":"356.553","rx":"5.012"},"hitbox":{"px":"-0","py":"0.311","pz":"1.25","ry":"356.506","rx":"-0.294"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args