# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6094f,0.2656f,0.8596f,-0.2973f,0.2489f,1.0475f,-0.1473f,2.2352f,-0.8646f,0.1143f,-0.6483f,1.5662f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0847f,0.045f,-0.0473f,0.0211f,0.0097f,0.8896f,0.624f,2.1356f,0.0645f,0.6224f,-0.8884f,1.3298f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.6582f,0.0149f,-0.0986f,0.0247f,0.0149f,1.6611f,0.0015f,1.3874f,0.0987f,0.0006f,-1.6583f,1.5024f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.0847f,0.0153f,-0.0634f,-0.3236f,0.0097f,1.0824f,0.0957f,1.7327f,0.0645f,0.0949f,-1.0806f,1.3143f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0847f,0.0153f,-0.0634f,0.4221f,0.0097f,1.0824f,0.0957f,1.726f,0.0645f,0.0949f,-1.0806f,1.27f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.989f,-0.3021f,0.3338f,-0.2677f,-0.0597f,0.8866f,0.6255f,1.9471f,-0.4462f,0.5509f,-0.8236f,1.1934f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9279f,0.3811f,-0.4179f,0.3425f,0.0769f,0.8805f,0.6322f,1.9416f,0.5603f,0.5103f,-0.7788f,1.1571f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0847f,0.0153f,-0.0634f,0.0054f,0.0097f,1.0824f,0.0957f,1.1711f,0.0645f,0.0949f,-1.0806f,1.2111f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0847f,0.0094f,-0.0646f,-0.1301f,0.0097f,1.0866f,-0.0057f,1.2612f,0.0645f,-0.0062f,-1.0847f,1.3208f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0847f,0.0094f,-0.0646f,0.2065f,0.0097f,1.0866f,-0.0057f,0.9865f,0.0645f,-0.0062f,-1.0847f,1.3022f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.023","py":"1.718","pz":"1.429","ry":"356.641","rx":"5.051"},"hitbox":{"px":"-0","py":"0.309","pz":"1.25","ry":"356.593","rx":"-0.3"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args