# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6133f,0.2422f,0.8812f,-0.3063f,-0.2011f,0.9995f,-0.4146f,2.4151f,-0.8915f,-0.392f,-0.5127f,1.4995f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0992f,0.0169f,-0.053f,0.0211f,0.0101f,1.0917f,0.1388f,2.2229f,0.0547f,0.1382f,-1.0905f,1.3341f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.6985f,-0.0065f,-0.0857f,0.0228f,0.0156f,1.6445f,-0.433f,1.4646f,0.0845f,-0.4333f,-1.6424f,1.5064f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.0992f,0.015f,-0.0536f,-0.328f,0.0101f,1.0959f,0.1007f,1.8151f,0.0547f,0.1f,-1.0947f,1.3137f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0992f,0.015f,-0.0536f,0.4277f,0.0101f,1.0959f,0.1007f,1.8082f,0.0547f,0.1f,-1.0947f,1.2761f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9973f,-0.311f,0.3464f,-0.27f,-0.0585f,0.8962f,0.6362f,2.0326f,-0.4619f,0.558f,-0.8286f,1.1926f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9452f,0.3812f,-0.4153f,0.3482f,0.0763f,0.8898f,0.6431f,2.0269f,0.5585f,0.5236f,-0.7907f,1.1618f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0992f,0.015f,-0.0536f,0.006f,0.0101f,1.0959f,0.1007f,1.2466f,0.0547f,0.1f,-1.0947f,1.2105f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0992f,0.0098f,-0.0548f,-0.1323f,0.0101f,1.1005f,-0.006f,1.3379f,0.0547f,-0.0065f,-1.0992f,1.3202f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0992f,0.0098f,-0.0548f,0.2087f,0.0101f,1.1005f,-0.006f,1.0596f,0.0547f,-0.0065f,-1.0992f,1.3047f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0.022","py":"1.799","pz":"1.433","ry":"357.199","rx":"5.247"},"hitbox":{"px":"-0","py":"0.373","pz":"1.25","ry":"357.148","rx":"-0.311"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args