# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.613f,0.2408f,0.8829f,-0.3071f,-0.2331f,0.9866f,-0.4309f,2.4307f,-0.885f,-0.4267f,-0.4981f,1.493f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.1001f,0.0149f,-0.0528f,0.0211f,0.0101f,1.0968f,0.1009f,2.2333f,0.0539f,0.1003f,-1.0956f,1.3344f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.7015f,0.0159f,-0.0834f,0.0226f,0.0155f,1.7035f,0.0077f,1.4743f,0.0834f,0.0069f,-1.7015f,1.5067f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1001f,0.0149f,-0.0528f,-0.3283f,0.0101f,1.0968f,0.1009f,1.8252f,0.0539f,0.1003f,-1.0956f,1.3136f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1001f,0.0149f,-0.0528f,0.428f,0.0101f,1.0968f,0.1009f,1.8182f,0.0539f,0.1003f,-1.0956f,1.2766f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9978f,-0.3117f,0.3473f,-0.2703f,-0.0585f,0.8968f,0.6369f,2.0429f,-0.463f,0.5584f,-0.8289f,1.1925f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9465f,0.3812f,-0.4151f,0.3486f,0.0763f,0.8905f,0.6438f,2.0372f,0.5583f,0.5245f,-0.7915f,1.1621f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.1001f,0.0149f,-0.0528f,0.006f,0.0101f,1.0968f,0.1009f,1.2562f,0.0539f,0.1003f,-1.0956f,1.2105f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.1001f,0.0097f,-0.054f,-0.1325f,0.0101f,1.1015f,-0.006f,1.3476f,0.0539f,-0.0065f,-1.1002f,1.3202f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.1001f,0.0097f,-0.054f,0.2089f,0.0101f,1.1015f,-0.006f,1.0691f,0.0539f,-0.0065f,-1.1002f,1.3049f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.022","py":"1.809","pz":"1.434","ry":"357.241","rx":"5.258"},"hitbox":{"px":"-0","py":"0.382","pz":"1.25","ry":"357.19","rx":"-0.311"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args