# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6127f,0.241f,0.8854f,-0.3083f,-0.248f,0.9815f,-0.4387f,2.4544f,-0.8834f,-0.4426f,-0.4909f,1.4902f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.102f,0.0139f,-0.0515f,0.0208f,0.01f,1.1001f,0.0837f,2.2545f,0.0524f,0.0831f,-1.099f,1.3349f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.7074f,0.0158f,-0.0811f,0.0221f,0.0155f,1.7093f,0.0083f,1.4942f,0.0812f,0.0075f,-1.7074f,1.5072f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.102f,0.0148f,-0.0513f,-0.3291f,0.01f,1.0986f,0.1015f,1.8457f,0.0524f,0.1009f,-1.0975f,1.3135f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.102f,0.0148f,-0.0513f,0.4286f,0.01f,1.0986f,0.1015f,1.8388f,0.0524f,0.1009f,-1.0975f,1.2775f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9987f,-0.3131f,0.3491f,-0.2707f,-0.0585f,0.8981f,0.6382f,2.0638f,-0.4653f,0.5592f,-0.8296f,1.1923f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9488f,0.381f,-0.4146f,0.3492f,0.0762f,0.8918f,0.6451f,2.0582f,0.5579f,0.5262f,-0.7932f,1.1628f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.102f,0.0148f,-0.0513f,0.0061f,0.01f,1.0986f,0.1015f,1.2758f,0.0524f,0.1009f,-1.0975f,1.2105f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.102f,0.0097f,-0.0525f,-0.1329f,0.01f,1.1033f,-0.0059f,1.3673f,0.0524f,-0.0064f,-1.1021f,1.3201f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.102f,0.0097f,-0.0525f,0.2091f,0.01f,1.1033f,-0.0059f,1.0884f,0.0524f,-0.0064f,-1.1021f,1.3054f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.022","py":"1.83","pz":"1.434","ry":"357.325","rx":"5.278"},"hitbox":{"px":"-0","py":"0.4","pz":"1.25","ry":"357.274","rx":"-0.309"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args