# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6119f,0.2424f,0.8898f,-0.3104f,-0.2568f,0.9808f,-0.4438f,2.4981f,-0.8857f,-0.4518f,-0.4861f,1.489f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.1056f,0.0131f,-0.0486f,0.0203f,0.0098f,1.1042f,0.0744f,2.2965f,0.0494f,0.0739f,-1.1032f,1.3359f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.7189f,0.0156f,-0.0767f,0.0212f,0.0152f,1.7205f,0.0093f,1.5337f,0.0768f,0.0086f,-1.7189f,1.5083f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1056f,0.0143f,-0.0483f,-0.3306f,0.0098f,1.102f,0.1024f,1.8863f,0.0494f,0.1019f,-1.101f,1.3131f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1056f,0.0143f,-0.0483f,0.4295f,0.0098f,1.102f,0.1024f,1.8796f,0.0494f,0.1019f,-1.101f,1.2792f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-1.0005f,-0.3159f,0.3524f,-0.2718f,-0.0586f,0.9005f,0.6407f,2.1052f,-0.4696f,0.5605f,-0.8308f,1.1919f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9534f,0.3804f,-0.4137f,0.3502f,0.0759f,0.8944f,0.6475f,2.0997f,0.5569f,0.5294f,-0.7966f,1.1641f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.1056f,0.0143f,-0.0483f,0.006f,0.0098f,1.102f,0.1024f,1.3148f,0.0494f,0.1019f,-1.101f,1.2105f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.1056f,0.0095f,-0.0494f,-0.1337f,0.0098f,1.1067f,-0.0058f,1.4065f,0.0494f,-0.0063f,-1.1056f,1.3201f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.1056f,0.0095f,-0.0494f,0.2094f,0.0098f,1.1067f,-0.0058f,1.1268f,0.0494f,-0.0063f,-1.1056f,1.3062f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.021","py":"1.87","pz":"1.435","ry":"357.49","rx":"5.309"},"hitbox":{"px":"-0","py":"0.437","pz":"1.25","ry":"357.441","rx":"-0.303"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args