# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6117f,0.2429f,0.8908f,-0.3109f,-0.2557f,0.9822f,-0.4434f,2.508f,-0.8872f,-0.4506f,-0.4864f,1.4894f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.1065f,0.013f,-0.0478f,0.0201f,0.0097f,1.1049f,0.076f,2.3064f,0.0486f,0.0755f,-1.1039f,1.3361f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.7217f,-0.0046f,-0.077f,0.021f,0.0151f,1.667f,-0.4369f,1.543f,0.0756f,-0.4371f,-1.6653f,1.5086f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1065f,0.0142f,-0.0475f,-0.331f,0.0097f,1.1028f,0.1026f,1.8959f,0.0486f,0.1021f,-1.1018f,1.313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1065f,0.0142f,-0.0475f,0.4297f,0.0097f,1.1028f,0.1026f,1.8892f,0.0486f,0.1021f,-1.1018f,1.2796f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-1.0008f,-0.3166f,0.3532f,-0.272f,-0.0587f,0.9011f,0.6413f,2.115f,-0.4707f,0.5608f,-0.831f,1.1917f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9545f,0.3803f,-0.4135f,0.3504f,0.0758f,0.895f,0.648f,2.1095f,0.5566f,0.5302f,-0.7974f,1.1644f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.1065f,0.0142f,-0.0475f,0.006f,0.0097f,1.1028f,0.1026f,1.324f,0.0486f,0.1021f,-1.1018f,1.2105f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.1065f,0.0094f,-0.0487f,-0.1339f,0.0097f,1.1075f,-0.0058f,1.4158f,0.0486f,-0.0062f,-1.1065f,1.3201f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.1065f,0.0094f,-0.0487f,0.2095f,0.0097f,1.1075f,-0.0058f,1.1359f,0.0486f,-0.0062f,-1.1065f,1.3064f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0.021","py":"1.88","pz":"1.436","ry":"357.531","rx":"5.315"},"hitbox":{"px":"-0","py":"0.445","pz":"1.25","ry":"357.482","rx":"-0.301"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args