# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.1081f,0.2403f,0.9691f,-0.6454f,-0.2025f,0.9492f,-0.2579f,2.167f,-0.9777f,-0.2232f,-0.0537f,1.4016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9114f,-0.1689f,0.3865f,-0.2912f,-0.1086f,0.9832f,0.1735f,2.0354f,-0.4075f,0.1157f,-0.9105f,1.4023f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-0.4051f,-0.0598f,0.1777f,-0.2623f,-0.0483f,0.442f,0.0387f,1.3369f,-0.1811f,0.016f,-0.4076f,1.5238f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.9114f,-0.1689f,0.3865f,-0.5127f,-0.1086f,0.9832f,0.1735f,1.6328f,-0.4075f,0.1157f,-0.9105f,1.2316f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.9114f,-0.1689f,0.3865f,0.1139f,-0.1086f,0.9832f,0.1735f,1.7074f,-0.4075f,0.1157f,-0.9105f,1.5118f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.8074f,-0.3224f,0.5026f,-0.4448f,-0.1192f,0.9153f,0.3957f,1.8449f,-0.5851f,0.2585f,-0.7742f,1.1624f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9993f,-0.0179f,-0.0982f,0.0679f,-0.0735f,0.8007f,0.6017f,1.906f,0.0676f,0.6059f,-0.798f,1.3916f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-0.9114f,-0.1689f,0.3865f,-0.1282f,-0.1086f,0.9832f,0.1735f,1.1621f,-0.4075f,0.1157f,-0.9105f,1.2705f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.9018f,-0.1774f,0.4047f,-0.307f,-0.1359f,0.9865f,0.1296f,1.2242f,-0.4204f,0.0616f,-0.9099f,1.3191f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.9018f,-0.1695f,0.408f,0.0206f,-0.1359f,0.9889f,0.1105f,1.0012f,-0.4204f,0.044f,-0.911f,1.4381f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"-0.276","py":"1.645","pz":"1.473","ry":"22.999","rx":"9.95"},"hitbox":{"px":"-0","py":"0.375","pz":"1.25","ry":"23.975","rx":"7.415"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] at @s run function aj:fine_print/animations/bring_item/zzz/frames/8_root_function