# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6115f,0.2434f,0.8918f,-0.3115f,-0.2537f,0.984f,-0.4426f,2.5174f,-0.8889f,-0.4483f,-0.4872f,1.4899f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.1073f,0.013f,-0.047f,0.0199f,0.0096f,1.1055f,0.0788f,2.316f,0.0478f,0.0783f,-1.1046f,1.3364f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.7244f,-0.0044f,-0.0759f,0.0207f,0.015f,1.6697f,-0.4374f,1.5521f,0.0745f,-0.4376f,-1.6681f,1.5088f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1073f,0.014f,-0.0467f,-0.3314f,0.0096f,1.1035f,0.1028f,1.9052f,0.0478f,0.1023f,-1.1026f,1.3129f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1073f,0.014f,-0.0467f,0.4299f,0.0096f,1.1035f,0.1028f,1.8985f,0.0478f,0.1023f,-1.1026f,1.2801f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-1.0012f,-0.3173f,0.3541f,-0.2723f,-0.0588f,0.9017f,0.6419f,2.1244f,-0.4718f,0.5611f,-0.8313f,1.1916f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9556f,0.3801f,-0.4132f,0.3506f,0.0758f,0.8956f,0.6486f,2.119f,0.5563f,0.5309f,-0.7982f,1.1647f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.1073f,0.014f,-0.0467f,0.0059f,0.0096f,1.1035f,0.1028f,1.3329f,0.0478f,0.1023f,-1.1026f,1.2105f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.1073f,0.0094f,-0.0479f,-0.1341f,0.0096f,1.1083f,-0.0058f,1.4248f,0.0478f,-0.0062f,-1.1073f,1.3201f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.1073f,0.0094f,-0.0479f,0.2095f,0.0096f,1.1083f,-0.0058f,1.1447f,0.0478f,-0.0062f,-1.1073f,1.3067f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0.021","py":"1.889","pz":"1.436","ry":"357.572","rx":"5.321"},"hitbox":{"px":"-0","py":"0.453","pz":"1.25","ry":"357.523","rx":"-0.299"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args