# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6108f,0.2451f,0.8946f,-0.313f,-0.2438f,0.9911f,-0.438f,2.5418f,-0.895f,-0.4373f,-0.4913f,1.4924f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.1097f,0.0131f,-0.0446f,0.0193f,0.0094f,1.1068f,0.0917f,2.3417f,0.0456f,0.0913f,-1.1059f,1.3369f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.7326f,0.015f,-0.0711f,0.02f,0.0146f,1.734f,0.0101f,1.5761f,0.0711f,0.0095f,-1.7327f,1.5096f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1097f,0.0136f,-0.0445f,-0.3325f,0.0094f,1.1058f,0.1032f,1.9299f,0.0456f,0.1028f,-1.1049f,1.3126f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1097f,0.0136f,-0.0445f,0.4304f,0.0094f,1.1058f,0.1032f,1.9235f,0.0456f,0.1028f,-1.1049f,1.2813f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-1.0022f,-0.3194f,0.3564f,-0.2731f,-0.059f,0.9033f,0.6435f,2.1496f,-0.4749f,0.5617f,-0.8321f,1.1912f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9588f,0.3795f,-0.4125f,0.3511f,0.0756f,0.8974f,0.65f,2.1444f,0.5554f,0.533f,-0.8005f,1.1656f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.1097f,0.0136f,-0.0445f,0.0058f,0.0094f,1.1058f,0.1032f,1.3566f,0.0456f,0.1028f,-1.1049f,1.2105f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.1097f,0.0091f,-0.0456f,-0.1348f,0.0094f,1.1106f,-0.0056f,1.4486f,0.0456f,-0.006f,-1.1097f,1.3201f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.1097f,0.0091f,-0.0456f,0.2097f,0.0094f,1.1106f,-0.0056f,1.168f,0.0456f,-0.006f,-1.1097f,1.3073f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.02","py":"1.914","pz":"1.436","ry":"357.694","rx":"5.333"},"hitbox":{"px":"-0","py":"0.475","pz":"1.25","ry":"357.646","rx":"-0.291"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args