# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6106f,0.2457f,0.8955f,-0.3135f,-0.2398f,0.9937f,-0.4362f,2.5485f,-0.8971f,-0.4329f,-0.4929f,1.4933f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.1104f,0.0131f,-0.0438f,0.0191f,0.0093f,1.1071f,0.0968f,2.349f,0.0448f,0.0964f,-1.1063f,1.3371f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.7353f,-0.0037f,-0.0714f,0.0197f,0.0145f,1.6801f,-0.4396f,1.5829f,0.07f,-0.4399f,-1.6787f,1.5098f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1104f,0.0134f,-0.0438f,-0.3329f,0.0093f,1.1065f,0.1034f,1.9369f,0.0448f,0.1029f,-1.1057f,1.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1104f,0.0134f,-0.0438f,0.4305f,0.0093f,1.1065f,0.1034f,1.9306f,0.0448f,0.1029f,-1.1057f,1.2817f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-1.0025f,-0.32f,0.3572f,-0.2734f,-0.0591f,0.9038f,0.644f,2.1568f,-0.4759f,0.5619f,-0.8324f,1.1911f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9598f,0.3793f,-0.4123f,0.3512f,0.0755f,0.898f,0.6504f,2.1516f,0.5551f,0.5337f,-0.8013f,1.1659f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.1104f,0.0134f,-0.0438f,0.0058f,0.0093f,1.1065f,0.1034f,1.3633f,0.0448f,0.1029f,-1.1057f,1.2106f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.1104f,0.009f,-0.0449f,-0.135f,0.0093f,1.1113f,-0.0056f,1.4553f,0.0448f,-0.006f,-1.1104f,1.3201f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.1104f,0.009f,-0.0449f,0.2097f,0.0093f,1.1113f,-0.0056f,1.1746f,0.0448f,-0.006f,-1.1104f,1.3076f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0.02","py":"1.921","pz":"1.437","ry":"357.734","rx":"5.336"},"hitbox":{"px":"-0","py":"0.481","pz":"1.25","ry":"357.687","rx":"-0.288"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args