# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.61f,0.2468f,0.8973f,-0.3146f,-0.232f,0.9987f,-0.4324f,2.5597f,-0.9012f,-0.4241f,-0.496f,1.4951f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.1119f,0.0132f,-0.0422f,0.0187f,0.0091f,1.1076f,0.1068f,2.3612f,0.0433f,0.1064f,-1.1068f,1.3374f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.7405f,-0.0034f,-0.0692f,0.0191f,0.0142f,1.6851f,-0.4408f,1.5942f,0.0678f,-0.441f,-1.6838f,1.5103f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1119f,0.0131f,-0.0423f,-0.3337f,0.0091f,1.1079f,0.1036f,1.9486f,0.0433f,0.1031f,-1.1071f,1.3122f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1119f,0.0131f,-0.0423f,0.4307f,0.0091f,1.1079f,0.1036f,1.9424f,0.0433f,0.1031f,-1.1071f,1.2825f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-1.0031f,-0.3214f,0.3587f,-0.274f,-0.0593f,0.9049f,0.6449f,2.1688f,-0.4779f,0.5622f,-0.8328f,1.1908f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9618f,0.3789f,-0.4118f,0.3514f,0.0754f,0.8991f,0.6512f,2.1637f,0.5545f,0.535f,-0.8028f,1.1664f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.1119f,0.0131f,-0.0423f,0.0057f,0.0091f,1.1079f,0.1036f,1.3743f,0.0433f,0.1031f,-1.1071f,1.2106f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.1119f,0.0089f,-0.0433f,-0.1355f,0.0091f,1.1127f,-0.0055f,1.4664f,0.0433f,-0.0058f,-1.1119f,1.3201f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.1119f,0.0089f,-0.0433f,0.2098f,0.0091f,1.1127f,-0.0055f,1.1854f,0.0433f,-0.0058f,-1.1119f,1.308f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0.019","py":"1.933","pz":"1.437","ry":"357.814","rx":"5.34"},"hitbox":{"px":"-0","py":"0.491","pz":"1.25","ry":"357.768","rx":"-0.282"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args