# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6085f,0.2489f,0.9016f,-0.3174f,-0.2221f,1.0064f,-0.4277f,2.5713f,-0.9086f,-0.4127f,-0.4993f,1.4972f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.1151f,0.0127f,-0.0384f,0.0174f,0.0085f,1.1093f,0.1201f,2.3742f,0.0395f,0.1197f,-1.1087f,1.3379f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.753f,-0.0028f,-0.0635f,0.0177f,0.0133f,1.697f,-0.444f,1.605f,0.0622f,-0.4442f,-1.6958f,1.5114f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1151f,0.0121f,-0.0386f,-0.3356f,0.0085f,1.111f,0.1038f,1.9602f,0.0395f,0.1034f,-1.1104f,1.3115f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1151f,0.0121f,-0.0386f,0.431f,0.0085f,1.111f,0.1038f,1.9544f,0.0395f,0.1034f,-1.1104f,1.2843f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-1.0042f,-0.3248f,0.3622f,-0.2755f,-0.0601f,0.9072f,0.6469f,2.181f,-0.4828f,0.5627f,-0.834f,1.1899f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9665f,0.3776f,-0.4105f,0.3518f,0.0751f,0.9019f,0.6528f,2.1763f,0.5527f,0.5377f,-0.8066f,1.1677f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.1151f,0.0121f,-0.0386f,0.0054f,0.0085f,1.111f,0.1038f,1.3845f,0.0395f,0.1034f,-1.1104f,1.2108f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.1151f,0.0083f,-0.0396f,-0.1366f,0.0085f,1.1158f,-0.0052f,1.4767f,0.0395f,-0.0055f,-1.1151f,1.3201f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.1151f,0.0083f,-0.0396f,0.2098f,0.0085f,1.1158f,-0.0052f,1.1951f,0.0395f,-0.0055f,-1.1151f,1.3091f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0.018","py":"1.945","pz":"1.438","ry":"358.01","rx":"5.336"},"hitbox":{"px":"-0","py":"0.499","pz":"1.25","ry":"357.967","rx":"-0.265"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args