# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.605f,0.2431f,0.91f,-0.3228f,-0.4329f,0.8888f,-0.5252f,2.5555f,-0.8365f,-0.6358f,-0.3863f,1.4473f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.1189f,0.0031f,-0.0351f,0.0153f,0.0075f,1.1106f,-0.1403f,2.3291f,0.0344f,-0.1405f,-1.1101f,1.3382f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.7688f,-0.0023f,-0.0556f,0.0155f,0.0119f,1.7117f,-0.449f,1.5576f,0.0544f,-0.4492f,-1.7109f,1.5126f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1189f,0.0107f,-0.0335f,-0.3383f,0.0075f,1.1147f,0.1034f,1.9135f,0.0344f,0.1031f,-1.1142f,1.3103f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1189f,0.0107f,-0.0335f,0.4309f,0.0075f,1.1147f,0.1034f,1.9083f,0.0344f,0.1031f,-1.1142f,1.2866f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-1.0051f,-0.3293f,0.3668f,-0.2776f,-0.0615f,0.9102f,0.6488f,2.135f,-0.4891f,0.5624f,-0.8353f,1.1884f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9723f,0.3754f,-0.4086f,0.3518f,0.0748f,0.9055f,0.654f,2.1308f,0.5498f,0.5407f,-0.8115f,1.1691f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.1189f,0.0107f,-0.0335f,0.0048f,0.0075f,1.1147f,0.1034f,1.3361f,0.0344f,0.1031f,-1.1142f,1.2112f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.1189f,0.0074f,-0.0344f,-0.1383f,0.0075f,1.1194f,-0.0046f,1.4285f,0.0344f,-0.0048f,-1.1189f,1.3202f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.1189f,0.0074f,-0.0344f,0.2096f,0.0075f,1.1194f,-0.0046f,1.1463f,0.0344f,-0.0048f,-1.1189f,1.3107f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0.016","py":"1.898","pz":"1.439","ry":"358.276","rx":"5.301"},"hitbox":{"px":"-0","py":"0.448","pz":"1.25","ry":"358.238","rx":"-0.235"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args