# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute positioned ^0.379 ^2.428 ^2.478 rotated ~70.693 ~77.233 run function aj:wander/animations/sword_swipe/zzz/frames/24_locator_soup
$execute as $(lefthand) positioned ^0.551 ^2.429 ^2.562 rotated ~109.864 ~-9.963 run function aj:wander/animations/sword_swipe/zzz/frames/24_locator_lefthand
$execute as $(sword) positioned ^-2.088 ^1.882 ^2.688 rotated ~19.125 ~0.106 run function aj:wander/animations/sword_swipe/zzz/frames/24_locator_sword
$execute as $(righthand) positioned ^-0.88 ^1.889 ^-0.796 rotated ~19.125 ~0.106 run function aj:wander/animations/sword_swipe/zzz/frames/24_locator_righthand
$execute as $(chest) positioned ^-0.399 ^2.087 ^-0.137 rotated ~66.278 ~11.693 run function aj:wander/animations/sword_swipe/zzz/frames/24_locator_chest
$execute as $(sack) positioned ^-0.062 ^-1.562 ^-0 rotated ~0 ~0 run function aj:wander/animations/sword_swipe/zzz/frames/24_locator_sack