# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(sack_top) run function animated_java:wander/variants/sack/zzz/apply_to_node_sack_top
$execute as $(sack_main) run function animated_java:wander/variants/sack/zzz/apply_to_node_sack_main