# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute positioned ^1.256 ^2.012 ^1.22 rotated ~114.44 ~1.109 run function aj:wander/animations/punch/zzz/frames/24_locator_soup
$execute as $(lefthand) positioned ^1.347 ^1.894 ^1.101 rotated ~25.112 ~-31.201 run function aj:wander/animations/punch/zzz/frames/24_locator_lefthand
$execute as $(sword) positioned ^-1.216 ^4.319 ^4.231 rotated ~356.159 ~-38.134 run function aj:wander/animations/punch/zzz/frames/24_locator_sword
$execute as $(righthand) positioned ^-1.41 ^2.042 ^1.337 rotated ~356.159 ~-38.134 run function aj:wander/animations/punch/zzz/frames/24_locator_righthand
$execute as $(chest) positioned ^-0.4 ^2.2 ^0.094 rotated ~0.938 ~49.045 run function aj:wander/animations/punch/zzz/frames/24_locator_chest
$execute as $(sack) positioned ^-0.062 ^-1.562 ^-0 rotated ~0 ~0 run function aj:wander/animations/punch/zzz/frames/24_locator_sack