# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function aj:fine_print/animations/pause_all
tag @s add aj.fine_print.animation.loop.playing
scoreboard players set @s aj.loop.frame 0
tag @s add aj.transforms_only
execute at @s run function aj:fine_print/animations/loop/set_frame {frame: 0}
tag @s remove aj.transforms_only