# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s add aj.wander.animation.jump_to_sword.playing
scoreboard players set @s aj.jump_to_sword.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:wander/animations/jump_to_sword/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only