# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "aj:fine_print"
data modify storage animated_java:temp entry.data.rig_hash set value "7d92ea1725dec7b316c53fe0fbf00c51ae781685b7b254f25109a91b069a648d"
tp @s ~ ~ ~ ~ ~
summon minecraft:interaction ^0 ^0 ^0 {Tags:["","aj.fine_print.bone.root.child","aj.fine_print.bone.root.child.locator","aj.fine_print.bone.root.decendant","aj.fine_print.bone.root.decendant.locator","aj.fine_print.bone.root.tree","aj.fine_print.entity","aj.fine_print.locator","aj.fine_print.locator.hitbox","aj.fine_print.node","aj.fine_print.node.hitbox","aj.global.bone.root.child","aj.global.bone.root.child.locator","aj.global.bone.root.decendant","aj.global.bone.root.decendant.locator","aj.global.bone.root.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.hitbox","aj.new"]}
execute as @n[ type=minecraft:interaction, tag=aj.fine_print.locator.hitbox, tag=aj.new, distance=..5 ] run function aj:fine_print/zzz/summon/as_locator/hitbox
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.hitbox set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.locators.hitbox.uuid set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.fine_print.node.mas] run function aj:fine_print/zzz/summon/as_node/mas
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.mas set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.fine_print.node.head] run function aj:fine_print/zzz/summon/as_node/head
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.head set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.fine_print.node.item_display] run function aj:fine_print/zzz/summon/as_node/item_display
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.item_display set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.fine_print.node.right_arm] run function aj:fine_print/zzz/summon/as_node/right_arm
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.right_arm set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.fine_print.node.left_arm] run function aj:fine_print/zzz/summon/as_node/left_arm
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.left_arm set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.fine_print.node.green_right_arm] run function aj:fine_print/zzz/summon/as_node/green_right_arm
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.green_right_arm set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.fine_print.node.green_left_arm] run function aj:fine_print/zzz/summon/as_node/green_left_arm
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.green_left_arm set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.fine_print.node.torso] run function aj:fine_print/zzz/summon/as_node/torso
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.torso set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.fine_print.node.right_leg] run function aj:fine_print/zzz/summon/as_node/right_leg
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.right_leg set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.fine_print.node.left_leg] run function aj:fine_print/zzz/summon/as_node/left_leg
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.left_leg set from storage animated_java:gu out
function aj:fine_print/zzz/summon/zzz/0 with storage animated_java:temp entry.data.locators.hitbox
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:temp uuids
function aj:fine_print/zzz/set_default_pose
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute if data storage animated_java:temp args.variant run function aj:fine_print/zzz/summon/variant_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function aj:fine_print/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
function aj:fine_print/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 4
execute on passengers run data modify entity @s teleport_duration set value 4
function aj:fine_print/zzz/summon/zzz/1 with storage animated_java:temp entry.data.locators.hitbox
tag @s remove aj.new
execute on passengers run tag @s remove aj.new
execute on passengers run ride @s dismount