# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function aj:wander/animations/pause_all
tag @s add aj.wander.animation.gunpowder_throw.playing
scoreboard players set @s aj.gunpowder_throw.frame 0
tag @s add aj.transforms_only
execute at @s run function aj:wander/animations/gunpowder_throw/set_frame {frame: 0}
tag @s remove aj.transforms_only