# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:fine_print rig_hash set value '7d92ea1725dec7b316c53fe0fbf00c51ae781685b7b254f25109a91b069a648d'
scoreboard objectives add aj.spawn.frame dummy
scoreboard objectives add aj.loop.frame dummy
scoreboard objectives add aj.vanish.frame dummy
scoreboard objectives add aj.bring_item.frame dummy
scoreboard objectives add aj.give_back_item.frame dummy
scoreboard objectives add aj.trade_item.frame dummy
scoreboard objectives add aj.pocket_enter.frame dummy
scoreboard objectives add aj.pocket_leave.frame dummy