# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers run function animated_java:fine_print/remove/this/as_data
execute on passengers unless data entity @s {data:{rig_hash: 'abb1651f66eefa3be866a651fd8ca34ee5b0a59e3d1e59a2f5c56b81a5aaed59'}} on vehicle run function animated_java:global/remove/outdated_rig
execute on passengers run function animated_java:fine_print/remove/this/zzz/0 with entity @s data.uuids_by_name
function animated_java:global/remove/entity_stack