# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function wander:remove_extra_aj
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:wander/remove/zzz/this/as_data
execute on passengers run kill @s
kill @s