# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.drink_potion_slow.frame matches 44.. run scoreboard players set @s aj.drink_potion_slow.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.drink_potion_slow.frame
execute at @s run function animated_java:wander/animations/drink_potion_slow/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.drink_potion_slow.frame 1