# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute positioned ^0.844 ^1.883 ^0.286 rotated ~90 ~-0 run function aj:wander/animations/angry_idle/zzz/frames/41_locator_soup
$execute as $(lefthand) positioned ^0.875 ^1.833 ^0.104 rotated ~0 ~-7.5 run function aj:wander/animations/angry_idle/zzz/frames/41_locator_lefthand
$execute as $(sword) positioned ^-0.875 ^2.559 ^3.818 rotated ~0 ~-10 run function aj:wander/animations/angry_idle/zzz/frames/41_locator_sword
$execute as $(righthand) positioned ^-0.875 ^1.918 ^0.186 rotated ~0 ~-10 run function aj:wander/animations/angry_idle/zzz/frames/41_locator_righthand
$execute as $(chest) positioned ^-0.375 ^2.558 ^0.388 rotated ~0 ~10 run function aj:wander/animations/angry_idle/zzz/frames/41_locator_chest
$execute as $(sack) positioned ^-0.062 ^-1.562 ^-0 rotated ~0 ~0 run function aj:wander/animations/angry_idle/zzz/frames/41_locator_sack