# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.whey_throw.frame matches 38.. run scoreboard players set @s aj.whey_throw.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.whey_throw.frame
execute at @s run function aj:wander/animations/whey_throw/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.whey_throw.frame 1