# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.bring_item.frame matches 261.. run scoreboard players set @s aj.bring_item.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.bring_item.frame
execute at @s run function aj:fine_print/animations/bring_item/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.bring_item.frame 1