# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:wander/animations/twirl/zzz/apply_frame {frame: 63}
scoreboard players add @s aj.twirl.frame 1