# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute store result storage aj:temp frame int 1 run scoreboard players set @s aj.drink_potion_slow.frame $(frame)
execute at @s run function animated_java:wander/animations/drink_potion_slow/zzz/apply_frame with storage aj:temp