modLoader="lowcodefml"
loaderVersion="[1,)"
license="All rights reserved"
[[mods]]
    modId="milkman"
    version="1.2"
    displayName="Milkman's Weapon Reborn"
    description="Made by Stevelocks"
    authors="Stevelocks, Roserocket, Log on a couch, Barbarian Pickle"
    displayTest="NONE"
    logoFile="pack.png"