# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:wander/animations/macarena/zzz/apply_frame {frame: 164}
scoreboard players add @s aj.macarena.frame 1