# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5098f,0.2347f,0.8276f,-0.3022f,-0.3748f,0.8054f,-0.4593f,2.5713f,-0.7743f,-0.5443f,-0.3226f,-0.0257f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0.0028f,0.0069f,0.0043f,0.0021f,0.9943f,-0.1067f,2.3722f,-0.0072f,-0.1067f,-0.9943f,-0.1153f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0f,0f,0f,-0.1998f,0f,0f,0f,1.6765f,0f,0f,0f,0.0544f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.7522f,0.356f,0.5545f,-0.3093f,0.6045f,0.7076f,0.3658f,2f,-0.2622f,0.6103f,-0.7475f,-0.0776f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.7584f,-0.3618f,-0.5422f,0.3782f,-0.6014f,0.7091f,0.368f,1.9986f,0.2513f,0.6052f,-0.7554f,-0.0726f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9849f,0.1631f,0.0576f,-0.2516f,0.1627f,0.9866f,-0.0109f,2.173f,-0.0586f,-0.0014f,-0.9983f,-0.2215f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9918f,-0.1279f,-0.0043f,0.3109f,-0.1277f,0.9916f,-0.0204f,2.1718f,0.0068f,-0.0197f,-0.9998f,-0.2174f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1f,0.0028f,0.0069f,0.002f,0.0021f,0.9943f,-0.1067f,1.4802f,-0.0072f,-0.1067f,-0.9943f,-0.051f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1f,0.0022f,0.0071f,-0.1297f,0.0021f,0.9997f,-0.0249f,1.5641f,-0.0072f,-0.0249f,-0.9997f,0.0397f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1f,0.0021f,0.0071f,0.1823f,0.0021f,1f,-0.0028f,1.3068f,-0.0072f,-0.0028f,-1f,0.0357f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"-0.143","py":"1.765","pz":"0.098","ry":"36.566","rx":"21.454"},"hitbox":{"px":"0","py":"0.688","pz":"0","ry":"0.407","rx":"-1.429"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args