# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.0174f,0.1782f,0.6778f,-0.7875f,0.289f,0.6196f,-0.1555f,1.8782f,-0.6385f,0.2755f,-0.0889f,0.4056f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.6099f,-0.1263f,0.3219f,-0.5408f,0.1352f,0.5136f,0.4577f,1.792f,-0.3183f,0.4602f,-0.4224f,0.3693f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0f,0f,0f,-0.5299f,0f,0f,0f,1.4717f,0f,0f,0f,0.2123f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.6099f,-0.1263f,0.3219f,-0.684f,0.1352f,0.5136f,0.4577f,1.6416f,-0.3183f,0.4602f,-0.4224f,0.0972f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.6099f,-0.1263f,0.3219f,-0.2647f,0.1352f,0.5136f,0.4577f,1.5487f,-0.3183f,0.4602f,-0.4224f,0.316f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.4906f,-0.1905f,0.4632f,-0.6332f,0.3115f,0.3917f,0.491f,1.7875f,-0.3922f,0.5494f,-0.1895f,0.1486f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.6833f,-0.1301f,0.0876f,-0.2901f,-0.0018f,0.3982f,0.577f,1.7115f,-0.1568f,0.5622f,-0.3885f,0.3276f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-0.6099f,-0.1263f,0.3219f,-0.4178f,0.1352f,0.5136f,0.4577f,1.3473f,-0.3183f,0.4602f,-0.4224f,-0.0553f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.6099f,0.0213f,0.3452f,-0.5461f,0.1352f,0.6587f,0.1983f,1.4249f,-0.3183f,0.2391f,-0.5771f,0.0207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.6099f,-0.0312f,0.3444f,-0.3141f,0.1352f,0.6212f,0.2957f,1.1816f,-0.3183f,0.3236f,-0.5343f,-0.0444f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"-0.534","py":"1.542","pz":"0.249","ry":"37.312","rx":"40.757"},"hitbox":{"px":"-0.446","py":"0.818","pz":"-0.227","ry":"30.882","rx":"16.429"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args