# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:wander_chest/zzz/reset_floating_entities
execute on passengers run function animated_java:wander_chest/zzz/1 with entity @s data.uuids_by_name