# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.sneak_idle.frame
scoreboard objectives remove aj.sneak_walk.frame
scoreboard objectives remove aj.swim.frame
scoreboard objectives remove aj.swim_idle.frame
scoreboard objectives remove aj.angry_run.frame
scoreboard objectives remove aj.sword_throw.frame
scoreboard objectives remove aj.ice_throw.frame
scoreboard objectives remove aj.stew_throw.frame
scoreboard objectives remove aj.sword_throw_backup.frame
scoreboard objectives remove aj.angry_run_sword.frame
scoreboard objectives remove aj.sword_swipe.frame
scoreboard objectives remove aj.give_sword1.frame
scoreboard objectives remove aj.give_sword2.frame
scoreboard objectives remove aj.punch.frame
scoreboard objectives remove aj.abduct.frame
scoreboard objectives remove aj.macarena.frame
scoreboard objectives remove aj.drink_potion_slow.frame
scoreboard objectives remove aj.drink_potion_quick.frame
scoreboard objectives remove aj.jump_despawn.frame
scoreboard objectives remove aj.jump_to_sword.frame
scoreboard objectives remove aj.jump_upward.frame
scoreboard objectives remove aj.angry_idle.frame
scoreboard objectives remove aj.twirl.frame
scoreboard objectives remove aj.gangnamstyle.frame
tellraw @a [[{"text":"\n[","color":"gray"},{"text":"AJ","color":"aqua"},"] ",[{"text":"(from ","color":"gray","italic":true},"wander",")"]," -> "],{"text":"Successfully removed known animation scoreboard objectives.","color":"red"},{"text":"\nIf you have exported multiple times you may have to manually remove some objectives from previous exports manually, as Animated Java can only remove the latest export's objectives.","color":"gray","italic":true},["\n"]]