# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.trader_dimension.root] run return 0
function #animated_java:trader_dimension/as_root/pre_tick
execute if entity @s[tag=aj.trader_dimension.animation.trees.playing] run function animated_java:trader_dimension/animations/trees/zzz/on_tick
execute if entity @s[tag=aj.trader_dimension.animation.open_chest.playing] run function animated_java:trader_dimension/animations/open_chest/zzz/on_tick
execute if entity @s[tag=aj.trader_dimension.animation.close_chest.playing] run function animated_java:trader_dimension/animations/close_chest/zzz/on_tick
execute on passengers if entity @s[tag=aj.trader_dimension.data] run function animated_java:trader_dimension/root/zzz/0
execute at @s on passengers run rotate @s ~ ~
function #animated_java:trader_dimension/as_root/post_tick