# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(leftthumb2) run function animated_java:wander/variants/pufferfish/zzz/apply_to_node_leftthumb2
$execute as $(leftthumb) run function animated_java:wander/variants/pufferfish/zzz/apply_to_node_leftthumb
$execute as $(leftpointerfinger) run function animated_java:wander/variants/pufferfish/zzz/apply_to_node_leftpointerfinger
$execute as $(leftmidfinger) run function animated_java:wander/variants/pufferfish/zzz/apply_to_node_leftmidfinger
$execute as $(leftringfinger) run function animated_java:wander/variants/pufferfish/zzz/apply_to_node_leftringfinger
$execute as $(lefthand1) run function animated_java:wander/variants/pufferfish/zzz/apply_to_node_lefthand1