# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.303f,0f,0f,0f,0.0876f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.3029f,0f,0f,0f,0.0876f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.3029f,0f,0f,0f,0.0876f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.3029f,0f,0f,0f,0.0876f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.3029f,0f,0f,0f,0.0876f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.3029f,0f,0f,0f,0.0876f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.3029f,0f,0f,0f,0.0876f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.3029f,0f,0f,0f,0.0876f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.3029f,0f,0f,0f,0.0876f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.3029f,0f,0f,0f,0.0876f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":0.0000011681629774052885,"py":0.3029453137223838,"pz":0.08758042925281448,"ry":249.52290508290992,"rx":2.9946193026801593},"hitbox":{"px":-1.0725560679075924e-17,"py":0.30293229324012994,"pz":0.08758084932360478,"ry":249.5286921230097,"rx":-2.0053773507108987}}}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:fine_print/animations/trade_item/zzz/frames/69_root_function