# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.2292f,0f,0f,0f,0.0509f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.2292f,0f,0f,0f,0.0509f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.2292f,0f,0f,0f,0.0509f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.2292f,0f,0f,0f,0.0509f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.2292f,0f,0f,0f,0.0509f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.2292f,0f,0f,0f,0.0509f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.2292f,0f,0f,0f,0.0509f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.2292f,0f,0f,0f,0.0509f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.2292f,0f,0f,0f,0.0509f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.2292f,0f,0f,0f,0.0509f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":-1.157396037459529e-7,"py":0.22921775824730398,"pz":0.050880597955812415,"ry":173.09417102199717,"rx":3.1074527029650856},"hitbox":{"px":-6.23123071514188e-18,"py":0.22920474027797794,"pz":0.0508818601369824,"ry":173.10826521125105,"rx":-1.8925274472220945}}}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:fine_print/animations/trade_item/zzz/frames/70_root_function