# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute positioned ^0.844 ^1.894 ^-0.169 rotated ~90 ~0 run function aj:wander/animations/gunpowder_throw/zzz/frames/63_locator_soup
$execute as $(lefthand) positioned ^0.875 ^1.876 ^-0.357 rotated ~0 ~2.5 run function aj:wander/animations/gunpowder_throw/zzz/frames/63_locator_lefthand
$execute as $(sword) positioned ^-0.875 ^2.612 ^3.368 rotated ~0 ~-10 run function aj:wander/animations/gunpowder_throw/zzz/frames/63_locator_sword
$execute as $(righthand) positioned ^-0.875 ^1.972 ^-0.263 rotated ~0 ~-10 run function aj:wander/animations/gunpowder_throw/zzz/frames/63_locator_righthand
$execute as $(chest) positioned ^-0.375 ^2.666 ^0.178 rotated ~0 ~2.5 run function aj:wander/animations/gunpowder_throw/zzz/frames/63_locator_chest
$execute as $(sack) positioned ^-0.062 ^-1.562 ^-0 rotated ~0 ~0 run function aj:wander/animations/gunpowder_throw/zzz/frames/63_locator_sack