# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute positioned ^0.258 ^5.336 ^1.189 rotated ~86.652 ~35.72 run function aj:wander/animations/jump_upward/zzz/frames/11_locator_soup
$execute as $(lefthand) positioned ^0.325 ^5.311 ^1.366 rotated ~161.941 ~-19.451 run function aj:wander/animations/jump_upward/zzz/frames/11_locator_lefthand
$execute as $(sword) positioned ^0.74 ^6.514 ^-2.023 rotated ~198.059 ~-19.451 run function aj:wander/animations/jump_upward/zzz/frames/11_locator_sword
$execute as $(righthand) positioned ^-0.338 ^5.286 ^1.283 rotated ~198.059 ~-19.451 run function aj:wander/animations/jump_upward/zzz/frames/11_locator_righthand
$execute as $(chest) positioned ^-0.375 ^3.938 ^0.688 rotated ~0 ~0 run function aj:wander/animations/jump_upward/zzz/frames/11_locator_chest
$execute as $(sack) positioned ^-0.062 ^-1.562 ^-0 rotated ~0 ~0 run function aj:wander/animations/jump_upward/zzz/frames/11_locator_sack