# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.wander.bone.sack_top] run function animated_java:wander/variants/sack/zzz/apply_to_bone_sack_top
execute on passengers if entity @s[tag=aj.wander.bone.sack_main] run function animated_java:wander/variants/sack/zzz/apply_to_bone_sack_main
execute on passengers if entity @s[tag=aj.wander.bone.blast_off1] run function animated_java:wander/variants/sack/zzz/apply_to_bone_blast_off1
execute on passengers if entity @s[tag=aj.wander.bone.blast_off2] run function animated_java:wander/variants/sack/zzz/apply_to_bone_blast_off2
return 1