# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$function aj:wander/animations/jump_upward/zzz/frames/$(frame) with storage animated_java:temp entry.data.uuids_by_name
function aj:wander/animations/jump_upward/zzz/zzz/1 with storage animated_java:temp entry.data.uuids_by_name
return 1