# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "aj:wander_chest"
data modify storage animated_java:temp entry.data.rig_hash set value "8b488adf21525bafdad6b8e489ee6862aed5b3d65c59a2fd9284b800debd35e1"
tp @s ~ ~ ~ ~ ~
summon minecraft:interaction ^0 ^-0.125 ^0 {Tags:["","aj.global.bone.root.child","aj.global.bone.root.child.locator","aj.global.bone.root.decendant","aj.global.bone.root.decendant.locator","aj.global.bone.root.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.hitbox","aj.new","aj.wander_chest.bone.root.child","aj.wander_chest.bone.root.child.locator","aj.wander_chest.bone.root.decendant","aj.wander_chest.bone.root.decendant.locator","aj.wander_chest.bone.root.tree","aj.wander_chest.entity","aj.wander_chest.locator","aj.wander_chest.locator.hitbox","aj.wander_chest.node","aj.wander_chest.node.hitbox"]}
execute as @n[ type=minecraft:interaction, tag=aj.wander_chest.locator.hitbox, tag=aj.new, distance=..2 ] run function aj:wander_chest/zzz/summon/as_locator/hitbox
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.hitbox set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.locators.hitbox.uuid set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.wander_chest.node.lid] run function aj:wander_chest/zzz/summon/as_node/lid
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.lid set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.wander_chest.node.base] run function aj:wander_chest/zzz/summon/as_node/base
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.base set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.wander_chest.node.freedom] run function aj:wander_chest/zzz/summon/as_node/freedom
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.freedom set from storage animated_java:gu out
function aj:wander_chest/zzz/summon/zzz/0 with storage animated_java:temp entry.data.locators.hitbox
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:temp uuids
function aj:wander_chest/zzz/set_default_pose
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute if data storage animated_java:temp args.variant run function aj:wander_chest/zzz/summon/variant_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function aj:wander_chest/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
function aj:wander_chest/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
function aj:wander_chest/zzz/summon/zzz/1 with storage animated_java:temp entry.data.locators.hitbox
tag @s remove aj.new
execute on passengers run tag @s remove aj.new