# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(nose) {transformation: [-1f,0f,0f,0f,0f,0.9989f,0.0464f,4.143f,0f,0.0464f,-0.9989f,0.202f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(glowing_eye) {transformation: [-1f,0f,0f,-0.125f,0f,0.9989f,0.0464f,4.209f,0f,0.0464f,-0.9989f,0.24f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.9989f,0.0464f,4.0283f,0f,0.0464f,-0.9989f,0.0092f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leftthumb2) {transformation: [-0.9879f,-0.1f,-0.1188f,1.0625f,-0.0547f,0.9402f,-0.3363f,1.9679f,0.1453f,-0.3257f,-0.9342f,0.3547f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leftthumb) {transformation: [-0.9879f,-0.1f,-0.1188f,1.0278f,-0.0547f,0.9402f,-0.3363f,2.1698f,0.1453f,-0.3257f,-0.9342f,0.195f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leftpointerfinger) {transformation: [-0.9879f,-0.1f,-0.1188f,1.1631f,-0.0547f,0.9402f,-0.3363f,1.8515f,0.1453f,-0.3257f,-0.9342f,0.2422f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leftmidfinger) {transformation: [-0.9879f,-0.1f,-0.1188f,1.1445f,-0.0547f,0.9402f,-0.3363f,1.7989f,0.1453f,-0.3257f,-0.9342f,0.0962f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leftringfinger) {transformation: [-0.9879f,-0.1f,-0.1188f,1.1259f,-0.0547f,0.9402f,-0.3363f,1.7464f,0.1453f,-0.3257f,-0.9342f,-0.0498f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(invisibility) {transformation: [-0.1099f,0.1096f,0.9879f,0.9706f,0.9073f,0.4169f,0.0547f,1.9546f,-0.4059f,0.9023f,-0.1453f,0.263f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(swiftness) {transformation: [-0.1188f,-0.1f,0.9879f,0.9104f,-0.3363f,0.9402f,0.0547f,1.7614f,-0.9342f,-0.3257f,-0.1453f,0.1395f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(suspicious_stew) {transformation: [-0.1408f,0.0654f,0.9879f,0.953f,0.71f,0.7021f,0.0547f,1.8474f,-0.69f,0.7091f,-0.1453f,0.1031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(log) {transformation: [-0.9879f,-0.1f,-0.1188f,0.8424f,-0.0547f,0.9402f,-0.3363f,1.9441f,0.1453f,-0.3257f,-0.9342f,0.0322f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(planks) {transformation: [-0.9879f,-0.1f,-0.1188f,0.7497f,-0.0547f,0.9402f,-0.3363f,1.939f,0.1453f,-0.3257f,-0.9342f,0.0458f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lefthand1) {transformation: [-0.9879f,-0.1f,-0.1188f,1.0681f,-0.0547f,0.9402f,-0.3363f,2.2033f,0.1453f,-0.3257f,-0.9342f,-0.0563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leftforearm) {transformation: [-0.9898f,-0.0693f,-0.1246f,0.9594f,-0.032f,0.9596f,-0.2796f,2.8804f,0.1389f,-0.2728f,-0.952f,-0.2246f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leftelbow) {transformation: [-0.9898f,0.0039f,-0.1425f,0.9601f,-0.032f,0.9681f,0.2485f,3.0619f,0.1389f,0.2505f,-0.9581f,-0.1776f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leftarm) {transformation: [-0.9898f,0.0039f,-0.1425f,0.75f,-0.032f,0.9681f,0.2485f,3.5312f,0.1389f,0.2505f,-0.9581f,0.008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(rightthumb2) {transformation: [-0.9886f,0.0716f,0.1327f,-1.0111f,0.0556f,0.9911f,-0.1208f,1.9344f,-0.1402f,-0.112f,-0.9838f,-0.019f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(rightthumb) {transformation: [-0.9886f,0.0716f,0.1327f,-0.9822f,0.0556f,0.9911f,-0.1208f,2.1671f,-0.1402f,-0.112f,-0.9838f,-0.1306f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(rightpointerfinger) {transformation: [-0.9886f,0.0716f,0.1327f,-1.1076f,0.0556f,0.9911f,-0.1208f,1.8423f,-0.1402f,-0.112f,-0.9838f,-0.1553f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(rightmidfinger) {transformation: [-0.9886f,0.0716f,0.1327f,-1.0869f,0.0556f,0.9911f,-0.1208f,1.8234f,-0.1402f,-0.112f,-0.9838f,-0.309f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(rightringfinger) {transformation: [-0.9886f,0.0716f,0.1327f,-1.0661f,0.0556f,0.9911f,-0.1208f,1.8046f,-0.1402f,-0.112f,-0.9838f,-0.4627f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hugeasssword) {transformation: [-3.8719f,0.2805f,0.5199f,-0.8118f,0.2177f,3.8819f,-0.4731f,2.0119f,-0.5491f,-0.4388f,-3.8531f,-0.2791f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(whey) {transformation: [0f,0f,0f,-0.6673f,0f,0f,0f,1.9264f,0f,0f,0f,-0.1062f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(ice) {transformation: [-0.9886f,0.0716f,0.1327f,-0.7975f,0.0556f,0.9911f,-0.1208f,1.9955f,-0.1402f,-0.112f,-0.9838f,-0.2752f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(righthand1) {transformation: [-0.9886f,0.0716f,0.1327f,-1.0226f,0.0556f,0.9911f,-0.1208f,2.2534f,-0.1402f,-0.112f,-0.9838f,-0.369f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(rightforearm) {transformation: [-0.9898f,0.0402f,0.1368f,-0.9346f,0.032f,0.9976f,-0.0614f,2.9538f,-0.1389f,-0.0564f,-0.9887f,-0.3845f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(rightelbow) {transformation: [-0.9898f,-0.0402f,0.1367f,-0.9421f,0.032f,0.8722f,0.4881f,3.1174f,-0.1389f,0.4875f,-0.862f,-0.2931f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(rightarm) {transformation: [-0.9898f,-0.0402f,0.1367f,-0.75f,0.032f,0.8722f,0.4881f,3.5312f,-0.1389f,0.4875f,-0.862f,0.008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1) {transformation: [-1.0833f,0f,0f,-0.0023f,0f,1.0814f,0.0646f,3.3777f,0f,0.0646f,-1.0814f,-0.1115f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1lid) {transformation: [-1f,0f,0f,-0.3438f,0f,0.9982f,0.0597f,2.6722f,0f,0.0597f,-0.9982f,0.2384f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest2) {transformation: [-1f,0f,0f,-0.3438f,0f,0.9982f,0.0597f,2.5162f,0f,0.0597f,-0.9982f,0.2291f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest1lid3) {transformation: [-1f,0f,0f,-0.2812f,0f,0.9982f,0.0597f,2.7104f,0f,0.0597f,-0.9982f,-0.4011f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest3) {transformation: [-1f,0f,0f,-0.2812f,0f,0.9982f,0.0597f,2.5544f,0f,0.0597f,-0.9982f,-0.4104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hugeasssword2) {transformation: [0f,2.8877f,-2.6461f,-1.2344f,-0.2336f,2.6413f,2.8825f,4.5518f,3.9097f,0.1579f,0.1723f,-0.3067f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(belt) {transformation: [-1f,0f,0f,0.0297f,0f,0.9982f,0.0597f,2.9723f,0f,0.0597f,-0.9982f,-0.0046f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torn_part) {transformation: [-1f,0f,0f,-0.0937f,0f,0.9341f,0.3571f,2.688f,0f,0.3571f,-0.9341f,-0.0268f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lowerbody) {transformation: [-1f,0f,0f,0.0039f,0f,0.9982f,0.0597f,2.1922f,0f,0.0597f,-0.9982f,0.0845f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leftfoot) {transformation: [-0.9892f,-0.0076f,-0.1465f,0.2677f,-0.0083f,1f,0.0037f,0.1445f,0.1464f,0.0049f,-0.9892f,-0.2621f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leftlowerleg) {transformation: [-0.9889f,0.025f,-0.1463f,0.3179f,-0.0071f,0.9766f,0.2148f,1.195f,0.1482f,0.2135f,-0.9656f,0.1231f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leftleg) {transformation: [-0.9889f,-0.0384f,-0.1433f,0.25f,-0.0071f,0.9771f,-0.2127f,2.2384f,0.1482f,-0.2094f,-0.9665f,-0.0695f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(rightfoot) {transformation: [-0.979f,0.002f,0.204f,-0.2446f,0.0014f,1f,-0.003f,0.1446f,-0.204f,-0.0026f,-0.979f,-0.2632f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(rightlowerleg) {transformation: [-0.979f,-0.0427f,0.1995f,-0.3227f,0.0014f,0.9763f,0.2162f,1.1945f,-0.204f,0.2119f,-0.9557f,0.1187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(rightleg) {transformation: [-0.979f,0.0445f,0.1991f,-0.25f,0.0014f,0.9774f,-0.2114f,2.2384f,-0.204f,-0.2066f,-0.9569f,-0.0695f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"soup":{"px":"0.933","py":"1.966","pz":"0.23","ry":"81.632","rx":"3.135"},"lefthand":{"px":"0.945","py":"1.881","pz":"0.059","ry":"352.752","rx":"-19.65"},"sword":{"px":"-1.383","py":"2.433","pz":"3.356","ry":"7.684","rx":"-6.938"},"righthand":{"px":"-0.893","py":"1.987","pz":"-0.271","ry":"7.684","rx":"-6.938"},"chest":{"px":"-0.375","py":"2.6","pz":"0.391","ry":"0","rx":"3.42"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] run function aj:wander/variants/blast_off/apply