# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute positioned ^0 ^196.688 ^131.563 rotated ~86.652 ~35.72 run function aj:wander/animations/jump_despawn/zzz/frames/91_locator_soup
$execute as $(lefthand) positioned ^0 ^196.688 ^131.563 rotated ~161.941 ~-19.451 run function aj:wander/animations/jump_despawn/zzz/frames/91_locator_lefthand
$execute as $(sword) positioned ^0 ^196.688 ^131.562 rotated ~198.059 ~-19.451 run function aj:wander/animations/jump_despawn/zzz/frames/91_locator_sword
$execute as $(righthand) positioned ^-0 ^196.688 ^131.563 rotated ~198.059 ~-19.451 run function aj:wander/animations/jump_despawn/zzz/frames/91_locator_righthand
$execute as $(chest) positioned ^-0 ^196.688 ^131.563 rotated ~0 ~0 run function aj:wander/animations/jump_despawn/zzz/frames/91_locator_chest
$execute as $(sack) positioned ^-0.062 ^-1.562 ^-0 rotated ~0 ~0 run function aj:wander/animations/jump_despawn/zzz/frames/91_locator_sack
execute run function aj:wander/animations/jump_despawn/zzz/frames/91_function_keyframe