# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data merge entity @s {width:1.125,height:1.125,response:1b}
function animated_java:global/util/get_entity_stack_uuids