# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [0.1616f,-0.0417f,-1.3515f,2.2398f,-1.3517f,0.0266f,-0.1624f,12.4371f,0.0314f,1.3608f,-0.0382f,-2.45f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute on vehicle unless entity @s[tag=aj.transforms_only] run function animated_java:fine_print/variants/invisible/apply
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:fine_print/animations/pocket_enter/zzz/frames/2_root_function