# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.swim.frame matches 19.. run scoreboard players set @s aj.swim.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.swim.frame
execute at @s run function animated_java:wander/animations/swim/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.swim.frame 1