# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute positioned ^0.258 ^5.121 ^3.521 rotated ~93.86 ~35.675 run function aj:wander/animations/jump_to_sword/zzz/frames/11_locator_soup
$execute as $(lefthand) positioned ^0.325 ^5.066 ^3.691 rotated ~160.491 ~-28.921 run function aj:wander/animations/jump_to_sword/zzz/frames/11_locator_lefthand
$execute as $(sword) positioned ^0.74 ^6.838 ^0.562 rotated ~199.509 ~-28.921 run function aj:wander/animations/jump_to_sword/zzz/frames/11_locator_sword
$execute as $(righthand) positioned ^-0.338 ^5.055 ^3.605 rotated ~199.509 ~-28.921 run function aj:wander/animations/jump_to_sword/zzz/frames/11_locator_righthand
$execute as $(chest) positioned ^-0.375 ^3.831 ^2.784 rotated ~0 ~10 run function aj:wander/animations/jump_to_sword/zzz/frames/11_locator_chest
$execute as $(sack) positioned ^-0.062 ^-1.562 ^-0 rotated ~0 ~0 run function aj:wander/animations/jump_to_sword/zzz/frames/11_locator_sack