# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data remove storage animated_java:temp args
$data modify storage animated_java:temp args merge value {name:'$(name)', command:'$(command)'}
execute at @s on passengers run function animated_java:trader_dimension/zzz/at_locator/as_data with storage animated_java:temp args