# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:trader_dimension rig_hash set value 'c6a3982a9a656d98d0487f03121852fee25f710dd7b8e0dd04318ff5885b578e'
scoreboard objectives add aj.trees.frame dummy
scoreboard objectives add aj.open_chest.frame dummy
scoreboard objectives add aj.close_chest.frame dummy