# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players remove @s aj.tween_duration 1
execute if score @s aj.tween_duration matches 1.. run return 1
execute if score @s aj.tween_duration matches 0 on passengers run function animated_java:fine_print/animations/trade_item/zzz/zzz/0 with entity @s data.uuids_by_name
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.trade_item.frame
function animated_java:fine_print/animations/trade_item/zzz/apply_frame with storage animated_java:temp args
execute if score @s aj.trade_item.frame matches 77.. run return run function animated_java:fine_print/animations/trade_item/pause
scoreboard players add @s aj.trade_item.frame 1