# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
execute if score @s aj.punch.frame matches 24.. run scoreboard players set @s aj.punch.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.punch.frame
execute at @s run function aj:wander/animations/punch/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.punch.frame 1