# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function wander:remove_extra_aj
execute on passengers run function animated_java:wander/remove/as_data
function animated_java:wander/remove/this/without_on_remove_function