# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(knob) {transformation: [-10f,0f,0f,-12.5f,0f,-7.0711f,7.0711f,6.9963f,0f,7.0711f,7.0711f,-2.5088f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lid) {transformation: [-10.0133f,0f,0f,-12.5f,0f,-7.0805f,7.0805f,6.9963f,0f,7.0805f,7.0805f,-2.5088f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lid2) {transformation: [-8.6733f,0f,0f,-12.5f,0f,-6.133f,6.133f,6.9963f,0f,6.133f,6.133f,-2.5088f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lid3) {transformation: [-9.34f,0f,0f,-12.5f,0f,-6.6044f,6.6044f,6.9963f,0f,6.6044f,6.6044f,-2.5088f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lid4) {transformation: [-8.0267f,0f,0f,-12.5f,0f,-5.6757f,5.6757f,6.9963f,0f,5.6757f,5.6757f,-2.5088f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lid5) {transformation: [-8.6667f,0f,0f,-12.5f,0f,-6.1283f,6.1283f,6.9963f,0f,6.1283f,6.1283f,-2.5088f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(base) {transformation: [-10f,0f,0f,-12.5f,0f,-10f,0f,-2f,0f,0f,10f,-3.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(base2) {transformation: [-8.6667f,0f,0f,-12.5f,0f,-8.6667f,0f,-2f,0f,0f,8.6667f,-3.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(base3) {transformation: [-10f,0f,0f,-12.5f,0f,-10f,0f,-2f,0f,0f,10f,-3.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(base4) {transformation: [-8.6667f,0f,0f,-12.5f,0f,-8.6667f,0f,-2f,0f,0f,8.6667f,-3.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(base5) {transformation: [-8.6667f,0f,0f,-12.5f,0f,-8.6667f,0f,-2f,0f,0f,8.6667f,-3.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":0,"py":0,"pz":0,"ry":0,"rx":0}}}