# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_knob) {transformation: [-10f,0f,0f,-12.5f,0f,-10f,0f,7f,0f,0f,10f,-2.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lid) {transformation: [-10.0133f,0f,0f,-12.5f,0f,-10.0133f,0f,7f,0f,0f,10.0133f,-2.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lid2) {transformation: [-8.6733f,0f,0f,-12.5f,0f,-8.6733f,0f,7f,0f,0f,8.6733f,-2.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lid3) {transformation: [-9.34f,0f,0f,-12.5f,0f,-9.34f,0f,7f,0f,0f,9.34f,-2.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lid4) {transformation: [-8.0267f,0f,0f,-12.5f,0f,-8.0267f,0f,7f,0f,0f,8.0267f,-2.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lid5) {transformation: [-8.6667f,0f,0f,-12.5f,0f,-8.6667f,0f,7f,0f,0f,8.6667f,-2.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute on vehicle unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^0 rotated ~0 ~0 in trader_dimension:pocket run function animated_java:trader_dimension/animations/close_chest/zzz/frames/120_locator_commands