# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.wander.bone.hugeasssword] run function animated_java:wander/variants/sword_hand/zzz/apply_to_bone_hugeasssword
execute on passengers if entity @s[tag=aj.wander.bone.hugeasssword2] run function animated_java:wander/variants/sword_hand/zzz/apply_to_bone_hugeasssword2
execute on passengers if entity @s[tag=aj.wander.bone.blast_off1] run function animated_java:wander/variants/sword_hand/zzz/apply_to_bone_blast_off1
execute on passengers if entity @s[tag=aj.wander.bone.blast_off2] run function animated_java:wander/variants/sword_hand/zzz/apply_to_bone_blast_off2
return 1