# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:wander/animations/sneak_walk/zzz/apply_frame {frame: 18}
scoreboard players add @s aj.sneak_walk.frame 1