# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data remove storage aj:temp args
$execute store result storage aj:temp args.frame int 1 run scoreboard players set @s aj.jump_upward.frame $(frame)
execute at @s run function animated_java:wander/animations/jump_upward/zzz/set_frame with storage aj:temp args