# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:wander_chest rig_hash set value '8b488adf21525bafdad6b8e489ee6862aed5b3d65c59a2fd9284b800debd35e1'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.open.frame dummy