# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.wander.bone.leftthumb2] run function animated_java:wander/variants/item_off/zzz/apply_to_bone_leftthumb2
execute on passengers if entity @s[tag=aj.wander.bone.leftthumb] run function animated_java:wander/variants/item_off/zzz/apply_to_bone_leftthumb
execute on passengers if entity @s[tag=aj.wander.bone.leftpointerfinger] run function animated_java:wander/variants/item_off/zzz/apply_to_bone_leftpointerfinger
execute on passengers if entity @s[tag=aj.wander.bone.leftmidfinger] run function animated_java:wander/variants/item_off/zzz/apply_to_bone_leftmidfinger
execute on passengers if entity @s[tag=aj.wander.bone.leftringfinger] run function animated_java:wander/variants/item_off/zzz/apply_to_bone_leftringfinger
execute on passengers if entity @s[tag=aj.wander.bone.invisibility] run function animated_java:wander/variants/item_off/zzz/apply_to_bone_invisibility
execute on passengers if entity @s[tag=aj.wander.bone.swiftness] run function animated_java:wander/variants/item_off/zzz/apply_to_bone_swiftness
execute on passengers if entity @s[tag=aj.wander.bone.suspicious_stew] run function animated_java:wander/variants/item_off/zzz/apply_to_bone_suspicious_stew
execute on passengers if entity @s[tag=aj.wander.bone.log] run function animated_java:wander/variants/item_off/zzz/apply_to_bone_log
execute on passengers if entity @s[tag=aj.wander.bone.planks] run function animated_java:wander/variants/item_off/zzz/apply_to_bone_planks
execute on passengers if entity @s[tag=aj.wander.bone.lefthand1] run function animated_java:wander/variants/item_off/zzz/apply_to_bone_lefthand1
execute on passengers if entity @s[tag=aj.wander.bone.ice] run function animated_java:wander/variants/item_off/zzz/apply_to_bone_ice
execute on passengers if entity @s[tag=aj.wander.bone.sack_top] run function animated_java:wander/variants/item_off/zzz/apply_to_bone_sack_top
execute on passengers if entity @s[tag=aj.wander.bone.sack_main] run function animated_java:wander/variants/item_off/zzz/apply_to_bone_sack_main
execute on passengers if entity @s[tag=aj.wander.bone.blast_off1] run function animated_java:wander/variants/item_off/zzz/apply_to_bone_blast_off1
execute on passengers if entity @s[tag=aj.wander.bone.blast_off2] run function animated_java:wander/variants/item_off/zzz/apply_to_bone_blast_off2
return 1