# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [0.1385f,0.9039f,0.4046f,-0.2886f,0.8487f,-0.3189f,0.4219f,1.3967f,0.5104f,0.2849f,-0.8113f,0.8722f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.4702f,0.5667f,0.6766f,-0.1748f,0.1612f,-0.6986f,0.6971f,1.5568f,0.8677f,0.4368f,0.2371f,0.5512f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0f,0f,0f,-0.555f,0f,0f,0f,1.7863f,0f,0f,0f,0.3026f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.4702f,0.5667f,0.6766f,-0.5342f,0.1612f,-0.6986f,0.6971f,1.8691f,0.8677f,0.4368f,0.2371f,0.6586f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.4702f,0.5667f,0.6766f,-0.211f,0.1612f,-0.6986f,0.6971f,1.7583f,0.8677f,0.4368f,0.2371f,0.062f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.4702f,0.5667f,0.6766f,-0.3169f,0.1612f,-0.6986f,0.6971f,1.8162f,0.8677f,0.4368f,0.2371f,0.7213f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.4702f,0.5667f,0.6766f,-0.0524f,0.1612f,-0.6986f,0.6971f,1.7256f,0.8677f,0.4368f,0.2371f,0.2332f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-0.4702f,0.5667f,0.6766f,-0.6601f,0.1612f,-0.6986f,0.6971f,2.203f,0.8677f,0.4368f,0.2371f,0.1683f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.4702f,0.5667f,0.6766f,-0.7392f,0.1612f,-0.6986f,0.6971f,2.102f,0.8677f,0.4368f,0.2371f,0.2954f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.4702f,0.5667f,0.6766f,-0.7339f,0.1612f,-0.6986f,0.6971f,2.2263f,0.8677f,0.4368f,0.2371f,-0.085f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"-0.472","py":"1.732","pz":"0.358","ry":"109.314","rx":"44.196"},"hitbox":{"px":"-1.131","py":"2.736","pz":"-0.186","ry":"109.314","rx":"44.196"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] at @s run function aj:fine_print/animations/vanish/zzz/frames/11_root_function