# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [0.232f,0.8921f,0.3877f,-0.1023f,0.8122f,-0.397f,0.4274f,1.1924f,0.5352f,0.2158f,-0.8167f,0.7851f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.4054f,0.5363f,0.7403f,0.0046f,0.1558f,-0.7574f,0.6341f,1.358f,0.9008f,0.3724f,0.2235f,0.4645f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0f,0f,0f,-0.3709f,0f,0f,0f,1.6258f,0f,0f,0f,0.2492f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.4054f,0.5363f,0.7403f,-0.3233f,0.1558f,-0.7574f,0.6341f,1.6907f,0.9008f,0.3724f,0.2235f,0.6064f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.4054f,0.5363f,0.7403f,-0.0446f,0.1558f,-0.7574f,0.6341f,1.5836f,0.9008f,0.3724f,0.2235f,-0.0129f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.4054f,0.5363f,0.7403f,-0.1074f,0.1558f,-0.7574f,0.6341f,1.6192f,0.9008f,0.3724f,0.2235f,0.6535f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.4054f,0.5363f,0.7403f,0.1207f,0.1558f,-0.7574f,0.6341f,1.5316f,0.9008f,0.3724f,0.2235f,0.1468f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-0.4054f,0.5363f,0.7403f,-0.4517f,0.1558f,-0.7574f,0.6341f,2.0547f,0.9008f,0.3724f,0.2235f,0.1387f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.4054f,0.5363f,0.7403f,-0.5307f,0.1558f,-0.7574f,0.6341f,1.9542f,0.9008f,0.3724f,0.2235f,0.2662f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.4054f,0.5363f,0.7403f,-0.5381f,0.1558f,-0.7574f,0.6341f,2.0949f,0.9008f,0.3724f,0.2235f,-0.1083f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"-0.289","py":"1.563","pz":"0.297","ry":"106.799","rx":"39.352"},"hitbox":{"px":"-0.901","py":"2.636","pz":"-0.164","ry":"106.799","rx":"39.352"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] at @s run function aj:fine_print/animations/vanish/zzz/frames/12_root_function