# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.672f,0.5487f,0.4973f,-0.3985f,0.6596f,0.7488f,0.0653f,3.2286f,-0.3365f,0.3719f,-0.8651f,0.9021f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.8824f,0.4587f,-0.1045f,-0.226f,0.1139f,0.4239f,0.8985f,3.2153f,0.4564f,0.781f,-0.4263f,0.5679f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0f,0f,0f,-0.4318f,0f,0f,0f,2.8696f,0f,0f,0f,0.2562f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.8824f,0.4587f,-0.1045f,-0.6738f,0.1139f,0.4239f,0.8985f,3.092f,0.4564f,0.781f,-0.4263f,0.4177f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.8824f,0.4587f,-0.1045f,-0.0671f,0.1139f,0.4239f,0.8985f,3.0137f,0.4564f,0.781f,-0.4263f,0.1039f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.8824f,0.4587f,-0.1045f,-0.5512f,0.1139f,0.4239f,0.8985f,3.2774f,0.4564f,0.781f,-0.4263f,0.4851f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.8824f,0.4587f,-0.1045f,-0.0548f,0.1139f,0.4239f,0.8985f,3.2133f,0.4564f,0.781f,-0.4263f,0.2284f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-0.8824f,0.4587f,-0.1045f,-0.6392f,0.1139f,0.4239f,0.8985f,2.8646f,0.4564f,0.781f,-0.4263f,-0.1434f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.8824f,0.4587f,-0.1045f,-0.708f,0.1139f,0.4239f,0.8985f,2.8297f,0.4564f,0.781f,-0.4263f,0.0199f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.8824f,0.4587f,-0.1045f,-0.5469f,0.1139f,0.4239f,0.8985f,2.6881f,0.4564f,0.781f,-0.4263f,-0.318f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"-0.385","py":"2.944","pz":"0.328","ry":"346.225","rx":"63.964"},"hitbox":{"px":"-1","py":"2.5","pz":"-0.75","ry":"346.225","rx":"63.964"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] at @s run function aj:fine_print/animations/vanish/zzz/frames/5_root_function