# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(hugeasssword) run function animated_java:wander/variants/sword_none/zzz/apply_to_node_hugeasssword
$execute as $(hugeasssword2) run function animated_java:wander/variants/sword_none/zzz/apply_to_node_hugeasssword2