# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers run function animated_java:wander/remove/this/as_data
execute on passengers unless data entity @s {data:{rig_hash: '04e45d415bb8da187815f2d027452ba1c9dc7e11bef6a55bd7bb2c5c027e2509'}} on vehicle run function animated_java:global/remove/outdated_rig
execute on passengers run function animated_java:wander/remove/this/zzz/0 with entity @s data.uuids_by_name
function animated_java:global/remove/entity_stack