# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute store result storage aj:temp frame int 1 run scoreboard players set @s aj.close_chest.frame $(frame)
execute at @s run function animated_java:trader_dimension/animations/close_chest/zzz/apply_frame with storage aj:temp