# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
particle minecraft:totem_of_undying ~ ~ ~ 0 0 0 0.3 40 normal @a
particle minecraft:gust ~ ~ ~ 0 0 0 0.0 1 normal @a