# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5684f,0.2212f,0.8426f,-0.3057f,-0.4264f,0.8067f,-0.4994f,2.4512f,-0.7596f,-0.6183f,-0.3502f,0.2676f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0394f,0.002f,-0.0409f,0.0076f,0.0083f,1.0273f,-0.1628f,2.2377f,0.0401f,-0.163f,-1.0265f,0.1704f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.0394f,0.0004f,-0.041f,0.0112f,0.0083f,1.0204f,-0.2016f,1.7453f,0.0401f,-0.2018f,-1.0196f,0.3649f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.0394f,0.0057f,-0.0406f,-0.3193f,0.0083f,1.038f,-0.0667f,1.851f,0.0401f,-0.067f,-1.0373f,0.2081f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0394f,0.0057f,-0.0406f,0.3952f,0.0083f,1.038f,-0.0667f,1.8453f,0.0401f,-0.067f,-1.0373f,0.1805f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9335f,0.4295f,0.1614f,-0.2649f,0.4434f,0.9386f,0.0669f,2.0368f,-0.118f,0.1289f,-1.0254f,0.0636f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9424f,-0.3522f,-0.2642f,0.3198f,-0.3766f,0.9682f,0.0528f,2.0321f,0.228f,0.1435f,-1.0047f,0.041f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0394f,0.0057f,-0.0406f,0.0012f,0.0083f,1.038f,-0.0667f,1.3079f,0.0401f,-0.067f,-1.0373f,0.1979f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0394f,-0.0013f,-0.041f,-0.1316f,0.0083f,1.0114f,-0.2427f,1.3741f,0.0401f,-0.2429f,-1.0106f,0.2829f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0394f,-0.0013f,-0.041f,0.193f,0.0083f,1.0114f,-0.2427f,1.1745f,0.0401f,-0.2429f,-1.0106f,0.3058f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.011","py":"1.857","pz":"0.325","ry":"357.76","rx":"-3.677"},"hitbox":{"px":"-0","py":"0.493","pz":"0.336","ry":"357.731","rx":"-7.327"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] at @s run function aj:fine_print/animations/trade_item/zzz/frames/29_root_function