# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5922f,0.2163f,0.9122f,-0.3526f,-0.8619f,0.2988f,-0.6304f,2.4395f,-0.3688f,-1.0457f,0.0086f,0.0693f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.108f,-0.0245f,-0.0362f,-0.0128f,0.0089f,0.7727f,-0.7952f,2.2025f,0.0428f,-0.7949f,-0.7719f,0.1184f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.108f,-0.0214f,-0.0381f,0.0015f,0.0089f,0.8353f,-0.7292f,1.8512f,0.0428f,-0.729f,-0.8344f,0.5598f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.108f,-0.0163f,-0.0405f,-0.3529f,0.0089f,0.9233f,-0.614f,1.859f,0.0428f,-0.6138f,-0.9225f,0.3619f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.108f,-0.0163f,-0.0405f,0.4088f,0.0089f,0.9233f,-0.614f,1.8529f,0.0428f,-0.6138f,-0.9225f,0.3325f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-1.0331f,-0.2274f,0.3325f,-0.2987f,-0.2452f,1.0811f,-0.0225f,1.9549f,-0.3196f,-0.0945f,-1.0576f,0.1291f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9998f,0.2384f,-0.4161f,0.3245f,0.2637f,1.0769f,-0.0167f,1.9499f,0.4005f,-0.114f,-1.0277f,0.1051f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.108f,-0.0163f,-0.0405f,0.0005f,0.0089f,0.9233f,-0.614f,1.3581f,0.0428f,-0.6138f,-0.9225f,0.6381f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.108f,-0.0262f,-0.0349f,-0.1438f,0.0089f,0.7329f,-0.832f,1.248f,0.0428f,-0.8316f,-0.7322f,0.6957f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.108f,-0.0262f,-0.0349f,0.2055f,0.0089f,0.7329f,-0.832f,1.3926f,0.0428f,-0.8316f,-0.7322f,0.73f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"-0.002","py":"1.933","pz":"0.464","ry":"357.484","rx":"-33.621"},"hitbox":{"px":"-0","py":"0.493","pz":"0.805","ry":"357.72","rx":"-8.622"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args