# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5731f,0.222f,0.8038f,-0.29f,-0.1211f,0.9428f,-0.3467f,2.3621f,-0.825f,-0.2925f,-0.5075f,0.6044f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0099f,0.0203f,-0.0589f,0.0088f,0.0081f,0.9912f,0.2029f,2.1966f,0.0618f,0.2021f,-0.9895f,0.4363f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.0099f,-0.0003f,-0.0623f,0.0147f,0.0081f,1.0025f,-0.1368f,1.7072f,0.0618f,-0.1371f,-1.0006f,0.5966f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.0099f,0.0078f,-0.0619f,-0.3097f,0.0081f,1.0118f,-0.0048f,1.8197f,0.0618f,-0.0053f,-1.0099f,0.4576f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0099f,0.0078f,-0.0619f,0.3846f,0.0081f,1.0118f,-0.0048f,1.8141f,0.0618f,-0.0053f,-1.0099f,0.4151f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9775f,0.2087f,0.1569f,-0.2591f,0.1981f,0.9889f,-0.0811f,2.0083f,-0.17f,-0.0476f,-0.9963f,0.3269f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.8865f,-0.152f,-0.4634f,0.3089f,-0.1293f,1.0003f,-0.0808f,2.0038f,0.4703f,-0.0115f,-0.8958f,0.2921f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0099f,0.0078f,-0.0619f,-0.0001f,0.0081f,1.0118f,-0.0048f,1.2921f,0.0618f,-0.0053f,-1.0099f,0.4094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0099f,0.0055f,-0.0621f,-0.1263f,0.0081f,1.0109f,-0.0419f,1.3979f,0.0618f,-0.0423f,-1.009f,0.5075f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0099f,0.0055f,-0.0621f,0.1884f,0.0081f,1.0109f,-0.0419f,1.1157f,0.0618f,-0.0423f,-1.009f,0.5095f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0.014","py":"1.818","pz":"0.564","ry":"356.495","rx":"-0.272"},"hitbox":{"px":"-0","py":"0.495","pz":"0.515","ry":"356.455","rx":"-5.272"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args