# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.581f,0.1994f,0.8014f,-0.2912f,-0.3305f,0.8418f,-0.4491f,2.3928f,-0.7568f,-0.5207f,-0.4191f,0.5702f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0068f,0.0042f,-0.0765f,0.0077f,0.0081f,1.0085f,-0.0505f,2.1956f,0.0762f,-0.051f,-1.0056f,0.4433f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.0068f,-0.0023f,-0.0766f,0.0159f,0.0081f,1.0005f,-0.1364f,1.7073f,0.0762f,-0.1366f,-0.9976f,0.6032f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.0068f,0.0077f,-0.0762f,-0.3098f,0.0081f,1.0097f,-0.0047f,1.8195f,0.0762f,-0.0053f,-1.0069f,0.4691f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0068f,0.0077f,-0.0762f,0.3824f,0.0081f,1.0097f,-0.0047f,1.8139f,0.0762f,-0.0053f,-1.0069f,0.4167f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9783f,0.2057f,0.1423f,-0.2613f,0.1949f,0.9869f,-0.087f,2.0078f,-0.1568f,-0.0568f,-0.9959f,0.338f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.876f,-0.1495f,-0.4795f,0.3051f,-0.1268f,0.9986f,-0.0796f,2.0032f,0.4859f,-0.0088f,-0.8851f,0.2951f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0068f,0.0077f,-0.0762f,-0.0016f,0.0081f,1.0097f,-0.0047f,1.293f,0.0762f,-0.0053f,-1.0069f,0.4166f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0068f,0.005f,-0.0765f,-0.1261f,0.0081f,1.0089f,-0.0406f,1.3989f,0.0762f,-0.0411f,-1.006f,0.5163f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0068f,0.005f,-0.0765f,0.1879f,0.0081f,1.0089f,-0.0406f,1.1166f,0.0762f,-0.0411f,-1.006f,0.5137f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.014","py":"1.818","pz":"0.571","ry":"355.67","rx":"-0.265"},"hitbox":{"px":"-0","py":"0.498","pz":"0.522","ry":"355.63","rx":"-5.265"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args