# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6108f,0.2034f,0.7707f,-0.283f,-0.1308f,0.9323f,-0.3497f,2.3633f,-0.7863f,-0.3131f,-0.5406f,0.6412f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9978f,0.0292f,-0.1102f,0.0047f,0.008f,0.9863f,0.1891f,2.1972f,0.1138f,0.187f,-0.9801f,0.461f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-0.9978f,-0.0075f,-0.1138f,0.0189f,0.008f,0.9951f,-0.1354f,1.7115f,0.1138f,-0.1354f,-0.9886f,0.6195f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.9978f,0.0075f,-0.1138f,-0.3099f,0.008f,1.0042f,-0.0043f,1.8231f,0.1138f,-0.0052f,-0.9978f,0.4985f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.9978f,0.0075f,-0.1138f,0.3761f,0.008f,1.0042f,-0.0043f,1.8176f,0.1138f,-0.0052f,-0.9978f,0.4203f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9787f,0.2007f,0.1022f,-0.2666f,0.1905f,0.9808f,-0.1019f,2.0104f,-0.1202f,-0.0799f,-0.9938f,0.3664f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.8484f,-0.1444f,-0.5176f,0.2946f,-0.1262f,0.9938f,-0.0704f,2.0059f,0.5223f,0.0055f,-0.8577f,0.3024f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-0.9978f,0.0075f,-0.1138f,-0.0055f,0.008f,1.0042f,-0.0043f,1.2996f,0.1138f,-0.0052f,-0.9978f,0.4345f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.9978f,0.0025f,-0.114f,-0.1256f,0.008f,1.0031f,-0.0481f,1.4026f,0.1138f,-0.0487f,-0.9966f,0.5379f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.9978f,0.0025f,-0.114f,0.1865f,0.008f,1.0031f,-0.0481f,1.1262f,0.1138f,-0.0487f,-0.9966f,0.5237f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.016","py":"1.821","pz":"0.588","ry":"353.493","rx":"-0.248"},"hitbox":{"px":"-0","py":"0.509","pz":"0.539","ry":"353.453","rx":"-5.248"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args