# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6179f,0.2176f,0.7591f,-0.2789f,-0.0033f,0.9631f,-0.2788f,2.3411f,-0.7897f,-0.1743f,-0.5928f,0.6707f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9951f,0.0484f,-0.1138f,0.0039f,0.008f,0.9459f,0.3327f,2.1987f,0.1234f,0.3292f,-0.939f,0.4655f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-0.9951f,-0.0088f,-0.1233f,0.0196f,0.008f,0.9935f,-0.1351f,1.7137f,0.1234f,-0.135f,-0.9859f,0.6235f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.9951f,0.0074f,-0.1234f,-0.3098f,0.008f,1.0027f,-0.0043f,1.8252f,0.1234f,-0.0052f,-0.9951f,0.506f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.9951f,0.0074f,-0.1234f,0.3743f,0.008f,1.0027f,-0.0043f,1.8197f,0.1234f,-0.0052f,-0.9951f,0.4212f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9782f,0.2003f,0.0913f,-0.2679f,0.1905f,0.9787f,-0.1058f,2.0122f,-0.1102f,-0.0859f,-0.9929f,0.3737f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.8413f,-0.1433f,-0.5264f,0.2918f,-0.1277f,0.9923f,-0.0661f,2.0077f,0.5304f,0.0116f,-0.8509f,0.3043f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-0.9951f,0.0074f,-0.1234f,-0.0065f,0.008f,1.0027f,-0.0043f,1.3024f,0.1234f,-0.0052f,-0.9951f,0.4391f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.9951f,0.0014f,-0.1236f,-0.1254f,0.008f,1.0013f,-0.0533f,1.4038f,0.1234f,-0.0539f,-0.9936f,0.5432f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.9951f,0.0014f,-0.1236f,0.186f,0.008f,1.0013f,-0.0533f,1.1308f,0.1234f,-0.0539f,-0.9936f,0.5261f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.017","py":"1.823","pz":"0.592","ry":"352.93","rx":"-0.243"},"hitbox":{"px":"-0","py":"0.513","pz":"0.543","ry":"352.89","rx":"-5.243"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args