# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6234f,0.2144f,0.7536f,-0.2777f,-0.0133f,0.96f,-0.2842f,2.3445f,-0.7834f,-0.187f,-0.5949f,0.6747f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9926f,0.0496f,-0.1218f,0.0033f,0.008f,0.9483f,0.3212f,2.2003f,0.1313f,0.3174f,-0.9405f,0.4692f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-0.9926f,-0.0098f,-0.1311f,0.0202f,0.008f,0.9921f,-0.1348f,1.716f,0.1313f,-0.1347f,-0.9835f,0.6268f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.9926f,0.0074f,-0.1313f,-0.3097f,0.008f,1.0012f,-0.0042f,1.8274f,0.1313f,-0.0052f,-0.9926f,0.5122f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.9926f,0.0074f,-0.1313f,0.3728f,0.008f,1.0012f,-0.0042f,1.8219f,0.1313f,-0.0052f,-0.9926f,0.4219f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9776f,0.2005f,0.0819f,-0.2688f,0.1912f,0.9768f,-0.1091f,2.0141f,-0.1018f,-0.0909f,-0.9919f,0.3797f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.8355f,-0.1425f,-0.5331f,0.2895f,-0.1298f,0.9909f,-0.0615f,2.0096f,0.5363f,0.0178f,-0.8453f,0.3059f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-0.9926f,0.0074f,-0.1313f,-0.0074f,0.008f,1.0012f,-0.0042f,1.3054f,0.1313f,-0.0052f,-0.9926f,0.4428f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.9926f,0.0001f,-0.1315f,-0.1253f,0.008f,0.9995f,-0.0592f,1.4049f,0.1313f,-0.0598f,-0.9908f,0.5473f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.9926f,0.0001f,-0.1315f,0.1856f,0.008f,0.9995f,-0.0592f,1.1356f,0.1313f,-0.0598f,-0.9908f,0.528f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.017","py":"1.825","pz":"0.595","ry":"352.465","rx":"-0.24"},"hitbox":{"px":"-0","py":"0.517","pz":"0.547","ry":"352.426","rx":"-5.24"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args