# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6296f,0.1943f,0.7507f,-0.2783f,-0.1241f,0.9292f,-0.3446f,2.3675f,-0.7654f,-0.3105f,-0.5615f,0.6622f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9887f,0.0353f,-0.137f,0.0025f,0.0079f,0.9795f,0.195f,2.2033f,0.1413f,0.192f,-0.9699f,0.4738f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-0.9887f,-0.0112f,-0.1411f,0.021f,0.0079f,0.9897f,-0.1344f,1.7202f,0.1413f,-0.1342f,-0.9796f,0.6308f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.9887f,0.0073f,-0.1413f,-0.3092f,0.0079f,0.9988f,-0.0041f,1.8313f,0.1413f,-0.0052f,-0.9887f,0.5199f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.9887f,0.0073f,-0.1413f,0.3705f,0.0079f,0.9988f,-0.0041f,1.8258f,0.1413f,-0.0052f,-0.9887f,0.4228f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9756f,0.2024f,0.0688f,-0.2699f,0.1939f,0.9732f,-0.1135f,2.0176f,-0.09f,-0.0975f,-0.9899f,0.3874f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.8281f,-0.142f,-0.5401f,0.2862f,-0.1354f,0.9882f,-0.0521f,2.0131f,0.5418f,0.0301f,-0.8385f,0.3079f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-0.9887f,0.0073f,-0.1413f,-0.0084f,0.0079f,0.9988f,-0.0041f,1.3106f,0.1413f,-0.0052f,-0.9887f,0.4475f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.9887f,-0.0023f,-0.1415f,-0.1251f,0.0079f,0.9962f,-0.0718f,1.4063f,0.1413f,-0.0722f,-0.9861f,0.5522f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.9887f,-0.0023f,-0.1415f,0.1849f,0.0079f,0.9962f,-0.0718f,1.1446f,0.1413f,-0.0722f,-0.9861f,0.5301f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0.017","py":"1.829","pz":"0.599","ry":"351.866","rx":"-0.235"},"hitbox":{"px":"-0","py":"0.524","pz":"0.551","ry":"351.826","rx":"-5.235"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args