# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6339f,0.1743f,0.7651f,-0.2847f,-0.2593f,0.8818f,-0.4157f,2.412f,-0.7407f,-0.4579f,-0.5093f,0.6366f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9983f,0.0133f,-0.1442f,0.0024f,0.008f,1.008f,0.0377f,2.2248f,0.1446f,0.0361f,-0.9977f,0.4733f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-0.9983f,-0.0116f,-0.1443f,0.0214f,0.008f,0.9996f,-0.1358f,1.7368f,0.1446f,-0.1355f,-0.9891f,0.6318f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.9983f,0.0073f,-0.1446f,-0.3124f,0.008f,1.0087f,-0.0041f,1.849f,0.1446f,-0.0052f,-0.9983f,0.5204f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.9983f,0.0073f,-0.1446f,0.374f,0.008f,1.0087f,-0.0041f,1.8435f,0.1446f,-0.0052f,-0.9983f,0.421f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9848f,0.2087f,0.0649f,-0.2729f,0.2004f,0.9818f,-0.1159f,2.0372f,-0.0872f,-0.1003f,-1f,0.3865f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.8367f,-0.1446f,-0.5447f,0.2886f,-0.1437f,0.9975f,-0.0441f,2.0327f,0.5449f,0.041f,-0.8479f,0.3052f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-0.9983f,0.0073f,-0.1446f,-0.0087f,0.008f,1.0087f,-0.0041f,1.3231f,0.1446f,-0.0052f,-0.9983f,0.4467f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.9983f,-0.0041f,-0.1447f,-0.1265f,0.008f,1.0052f,-0.0839f,1.4166f,0.1446f,-0.0842f,-0.9948f,0.5519f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.9983f,-0.0041f,-0.1447f,0.1867f,0.008f,1.0052f,-0.0839f,1.1586f,0.1446f,-0.0842f,-0.9948f,0.5295f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0.018","py":"1.847","pz":"0.6","ry":"351.758","rx":"-0.234"},"hitbox":{"px":"-0","py":"0.529","pz":"0.551","ry":"351.718","rx":"-5.234"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args