# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6361f,0.171f,0.7762f,-0.2887f,-0.3013f,0.868f,-0.4382f,2.4358f,-0.7355f,-0.5035f,-0.4918f,0.6259f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0078f,0.0065f,-0.1433f,0.0026f,0.0081f,1.0179f,-0.0109f,2.2412f,0.1432f,-0.012f,-1.0078f,0.4709f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.0078f,-0.0113f,-0.143f,0.0214f,0.0081f,1.0087f,-0.137f,1.7488f,0.1432f,-0.1368f,-0.9985f,0.631f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.0078f,0.0074f,-0.1433f,-0.3151f,0.0081f,1.0179f,-0.0042f,1.862f,0.1432f,-0.0053f,-1.0078f,0.5177f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0078f,0.0074f,-0.1433f,0.3777f,0.0081f,1.0179f,-0.0042f,1.8564f,0.1432f,-0.0053f,-1.0078f,0.4192f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9931f,0.2133f,0.067f,-0.275f,0.2048f,0.9903f,-0.1162f,2.0519f,-0.0896f,-0.0999f,-1.0091f,0.3827f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.8467f,-0.1472f,-0.5455f,0.2919f,-0.1484f,1.0062f,-0.0411f,2.0473f,0.5452f,0.0454f,-0.8585f,0.3021f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0078f,0.0074f,-0.1433f,-0.0085f,0.0081f,1.0179f,-0.0042f,1.3313f,0.1432f,-0.0053f,-1.0078f,0.4442f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0078f,-0.0045f,-0.1434f,-0.1277f,0.0081f,1.014f,-0.089f,1.4245f,0.1432f,-0.0892f,-1.0039f,0.5497f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0078f,-0.0045f,-0.1434f,0.1884f,0.0081f,1.014f,-0.089f,1.1664f,0.1432f,-0.0892f,-1.0039f,0.5281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.018","py":"1.86","pz":"0.599","ry":"351.909","rx":"-0.235"},"hitbox":{"px":"-0","py":"0.53","pz":"0.549","ry":"351.869","rx":"-5.235"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args