# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6069f,0.2201f,0.8532f,-0.3087f,-0.3172f,0.912f,-0.4608f,2.5077f,-0.8221f,-0.5143f,-0.452f,0.5672f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0677f,0.0078f,-0.0684f,0.0091f,0.0086f,1.0698f,-0.0121f,2.3031f,0.0683f,-0.0127f,-1.0676f,0.4285f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.0677f,-0.0008f,-0.0689f,0.0158f,0.0086f,1.06f,-0.1447f,1.7857f,0.0683f,-0.1449f,-1.0578f,0.598f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.0677f,0.0082f,-0.0684f,-0.3276f,0.0086f,1.0698f,-0.0051f,1.9046f,0.0683f,-0.0056f,-1.0677f,0.452f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0677f,0.0082f,-0.0684f,0.4064f,0.0086f,1.0698f,-0.0051f,1.8987f,0.0683f,-0.0056f,-1.0677f,0.405f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-1.0312f,0.2416f,0.1516f,-0.2746f,0.2304f,1.0407f,-0.092f,2.1041f,-0.1683f,-0.056f,-1.0551f,0.3136f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9402f,-0.171f,-0.481f,0.326f,-0.1683f,1.0556f,-0.0462f,2.0993f,0.482f,0.035f,-0.9545f,0.2752f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0677f,0.0082f,-0.0684f,-0.0004f,0.0086f,1.0698f,-0.0051f,1.3468f,0.0683f,-0.0056f,-1.0677f,0.4001f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0677f,0.0022f,-0.0688f,-0.1339f,0.0086f,1.0653f,-0.0983f,1.4437f,0.0683f,-0.0986f,-1.0631f,0.5008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0677f,0.0022f,-0.0688f,0.1992f,0.0086f,1.0653f,-0.0983f,1.1747f,0.0683f,-0.0986f,-1.0631f,0.5041f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.015","py":"1.903","pz":"0.564","ry":"356.335","rx":"-0.271"},"hitbox":{"px":"-0","py":"0.504","pz":"0.512","ry":"356.295","rx":"-5.27"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args