# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.6279f,0.2023f,0.8325f,-0.3045f,-0.3125f,0.9069f,-0.4561f,2.4775f,-0.7977f,-0.5145f,-0.4766f,0.5519f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0573f,0.0074f,-0.1013f,0.0065f,0.0082f,1.0621f,-0.0089f,2.2749f,0.1012f,-0.0097f,-1.0573f,0.4037f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.0573f,-0.0053f,-0.1014f,0.0184f,0.0082f,1.0528f,-0.1405f,1.7607f,0.1012f,-0.1406f,-1.048f,0.5702f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.0573f,0.008f,-0.1012f,-0.3269f,0.0082f,1.0622f,-0.0019f,1.8791f,0.1012f,-0.0027f,-1.0574f,0.4363f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.0573f,0.008f,-0.1012f,0.4f,0.0082f,1.0622f,-0.0019f,1.8735f,0.1012f,-0.0027f,-1.0574f,0.3668f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-1.0281f,0.2379f,0.1213f,-0.2786f,0.2316f,1.0345f,-0.0666f,2.0776f,-0.1331f,-0.038f,-1.0531f,0.298f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9222f,-0.1734f,-0.4976f,0.3162f,-0.1656f,1.0476f,-0.0581f,2.073f,0.5003f,0.0272f,-0.9366f,0.2411f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.0573f,0.008f,-0.1012f,-0.0038f,0.0082f,1.0622f,-0.0019f,1.3255f,0.1012f,-0.0027f,-1.0574f,0.3731f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0573f,-0.0008f,-0.1015f,-0.1332f,0.0082f,1.058f,-0.0944f,1.4214f,0.1012f,-0.0948f,-1.0531f,0.4774f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.0573f,-0.0008f,-0.1015f,0.1975f,0.0082f,1.058f,-0.0944f,1.1543f,0.1012f,-0.0948f,-1.0531f,0.4694f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.016","py":"1.877","pz":"0.537","ry":"354.532","rx":"-0.101"},"hitbox":{"px":"-0","py":"0.489","pz":"0.481","ry":"354.493","rx":"-5.101"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args