# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5733f,-0.4281f,-0.5117f,0.1418f,-0.2456f,0.7627f,-0.3628f,2.1002f,0.6203f,-0.0936f,-0.6166f,0.5766f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.2259f,0.014f,-0.85f,-0.0256f,-0.0014f,0.8795f,0.0141f,1.9373f,0.8501f,-0.0023f,0.2259f,0.3421f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0.2259f,-0.0914f,-0.8452f,0.0976f,-0.0014f,0.8745f,-0.095f,1.5082f,0.8501f,0.0257f,0.2244f,0.3086f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0.2259f,0.0197f,-0.8499f,0.0376f,-0.0014f,0.8794f,0.02f,1.6071f,0.8501f,-0.0038f,0.2259f,0.6092f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0.2259f,0.0197f,-0.8499f,-0.1177f,-0.0014f,0.8794f,0.02f,1.608f,0.8501f,-0.0038f,0.2259f,0.0247f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [0.0355f,0.1681f,-0.8627f,-0.0777f,0.1888f,0.8418f,0.1718f,1.7746f,0.8584f,-0.1921f,-0.0021f,0.5889f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [0.4921f,-0.1287f,-0.7176f,-0.2047f,-0.0896f,0.8486f,-0.2136f,1.7753f,0.7236f,0.1926f,0.4616f,0.1107f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [0.2259f,0.0197f,-0.8499f,-0.0698f,-0.0014f,0.8794f,0.02f,1.152f,0.8501f,-0.0038f,0.2259f,0.3525f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [0.2259f,-0.0545f,-0.8484f,0.035f,-0.0014f,0.8778f,-0.0567f,1.2284f,0.8501f,0.0159f,0.2253f,0.4443f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [0.2259f,-0.0545f,-0.8484f,-0.022f,-0.0014f,0.8778f,-0.0567f,1.0094f,0.8501f,0.0159f,0.2253f,0.1746f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0.073","py":"1.605","pz":"0.315","ry":"255.118","rx":"1.301"},"hitbox":{"px":"-0","py":"0.457","pz":"0.333","ry":"255.126","rx":"-3.699"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] at @s run function aj:fine_print/animations/trade_item/zzz/frames/63_root_function