# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [0.0122f,-0.2964f,-0.6381f,0.2221f,-0.1964f,0.6114f,-0.2877f,1.7578f,0.6756f,0.1831f,-0.0721f,0.3533f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.6015f,0.0096f,-0.3652f,-0.005f,-0.0034f,0.7036f,0.0129f,1.6283f,0.3653f,-0.0093f,0.6014f,0.3108f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0.6015f,-0.0357f,-0.3635f,0.0463f,-0.0034f,0.6998f,-0.0744f,1.2848f,0.3653f,0.0653f,0.5979f,0.2233f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0.6015f,0.012f,-0.3651f,0.1785f,-0.0034f,0.7035f,0.0176f,1.3635f,0.3653f,-0.0133f,0.6013f,0.4299f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0.6015f,0.012f,-0.3651f,-0.235f,-0.0034f,0.7035f,0.0176f,1.3658f,0.3653f,-0.0133f,0.6013f,0.1788f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [0.4968f,0.0435f,-0.4965f,0.1013f,0.1492f,0.6559f,0.2068f,1.4978f,0.4755f,-0.2512f,0.4538f,0.4821f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [0.6828f,-0.0061f,-0.17f,-0.237f,-0.0519f,0.6623f,-0.2322f,1.4997f,0.162f,0.2378f,0.6422f,0.2766f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [0.6015f,0.012f,-0.3651f,-0.0271f,-0.0034f,0.7035f,0.0176f,1.0001f,0.3653f,-0.0133f,0.6013f,0.3415f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [0.6015f,-0.0198f,-0.3648f,0.0844f,-0.0034f,0.7023f,-0.0438f,1.0609f,0.3653f,0.0392f,0.6002f,0.3363f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [0.6015f,-0.0198f,-0.3648f,-0.0986f,-0.0034f,0.7023f,-0.0438f,0.8864f,0.3653f,0.0392f,0.6002f,0.2124f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.036","py":"1.362","pz":"0.241","ry":"211.264","rx":"1.434"},"hitbox":{"px":"-0","py":"0.444","pz":"0.292","ry":"211.288","rx":"-3.566"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] at @s run function aj:fine_print/animations/trade_item/zzz/frames/64_root_function