# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [0.3761f,-0.0336f,-0.3278f,0.134f,-0.1393f,0.4346f,-0.2043f,1.3615f,0.2986f,0.2449f,0.3175f,0.1554f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.472f,-0.0008f,0.1648f,0.0081f,-0.0025f,0.4999f,0.0096f,1.2696f,-0.1648f,-0.0098f,0.472f,0.2608f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0.472f,0.0196f,0.1637f,-0.0167f,-0.0025f,0.4972f,-0.0525f,1.0255f,-0.1648f,0.0487f,0.4695f,0.1933f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0.472f,-0.0019f,0.1648f,0.1564f,-0.0025f,0.4998f,0.0129f,1.0814f,-0.1648f,-0.013f,0.4719f,0.2141f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0.472f,-0.0019f,0.1648f,-0.1682f,-0.0025f,0.4998f,0.0129f,1.0831f,-0.1648f,-0.013f,0.4719f,0.3275f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [0.4852f,-0.1201f,0.0125f,0.1501f,0.1061f,0.4487f,0.1935f,1.1768f,-0.0577f,-0.1851f,0.4609f,0.28f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [0.4053f,0.1371f,0.2588f,-0.1155f,-0.0207f,0.4541f,-0.2082f,1.1782f,-0.2921f,0.158f,0.3738f,0.3727f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [0.472f,-0.0019f,0.1648f,0.015f,-0.0025f,0.4998f,0.0129f,0.8233f,-0.1648f,-0.013f,0.4719f,0.2871f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [0.472f,0.0124f,0.1644f,0.0626f,-0.0025f,0.499f,-0.0307f,0.8664f,-0.1648f,0.0282f,0.4712f,0.2236f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [0.472f,0.0124f,0.1644f,-0.0881f,-0.0025f,0.499f,-0.0307f,0.7424f,-0.1648f,0.0282f,0.4712f,0.2681f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"-0.012","py":"1.081","pz":"0.207","ry":"160.745","rx":"1.475"},"hitbox":{"px":"-0","py":"0.428","pz":"0.25","ry":"160.77","rx":"-3.525"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] at @s run function aj:fine_print/animations/trade_item/zzz/frames/65_root_function