# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5877f,0.2146f,0.9063f,-0.3545f,-0.8614f,0.2822f,-0.6254f,2.3869f,-0.3541f,-1.0427f,0.0172f,-0.4064f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.1004f,-0.0248f,-0.0356f,-0.0168f,0.0088f,0.7562f,-0.8005f,2.1524f,0.0425f,-0.8002f,-0.7554f,-0.3543f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-1.1004f,-0.023f,-0.0368f,-0.002f,0.0088f,0.7963f,-0.7607f,1.8235f,0.0425f,-0.7604f,-0.7955f,0.0993f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.1004f,-0.018f,-0.0395f,-0.354f,0.0088f,0.8888f,-0.6502f,1.8218f,0.0425f,-0.65f,-0.888f,-0.0973f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.1004f,-0.018f,-0.0395f,0.4026f,0.0088f,0.8888f,-0.6502f,1.8158f,0.0425f,-0.65f,-0.888f,-0.1265f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-1.053f,0.0137f,0.3223f,-0.3004f,-0.0038f,1.0997f,-0.059f,1.9067f,-0.3226f,-0.0575f,-1.0514f,-0.3326f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-1.0219f,0.0054f,-0.4106f,0.3186f,0.0282f,1.0995f,-0.0557f,1.9018f,0.4097f,-0.0622f,-1.0204f,-0.3565f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1.1004f,-0.018f,-0.0395f,-0.002f,0.0088f,0.8888f,-0.6502f,1.3377f,0.0425f,-0.65f,-0.888f,0.1989f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.1004f,-0.0277f,-0.0334f,-0.1449f,0.0088f,0.687f,-0.8607f,1.2403f,0.0425f,-0.8603f,-0.6862f,0.2648f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.1004f,-0.0277f,-0.0334f,0.2015f,0.0088f,0.687f,-0.8607f,1.3719f,0.0425f,-0.8603f,-0.6862f,0.2888f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"-0.005","py":"1.9","pz":"0","ry":"357.454","rx":"-36.186"},"hitbox":{"px":"-0","py":"0.493","pz":"0.427","ry":"357.685","rx":"-12.849"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args