# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(whey) run function animated_java:wander/variants/whey_on/zzz/apply_to_node_whey