# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute positioned ^0.591 ^2.073 ^0.877 rotated ~83.71 ~-2.985 run function aj:wander/animations/gangnamstyle/zzz/frames/248_locator_soup
$execute as $(lefthand) positioned ^0.599 ^1.999 ^0.701 rotated ~352.937 ~-14.509 run function aj:wander/animations/gangnamstyle/zzz/frames/248_locator_lefthand
$execute as $(sword) positioned ^0.524 ^2.226 ^3.836 rotated ~339.307 ~-3.235 run function aj:wander/animations/gangnamstyle/zzz/frames/248_locator_sword
$execute as $(righthand) positioned ^-0.777 ^2.018 ^0.392 rotated ~339.307 ~-3.235 run function aj:wander/animations/gangnamstyle/zzz/frames/248_locator_righthand
$execute as $(chest) positioned ^-0.381 ^2.753 ^0.333 rotated ~3.767 ~-0.439 run function aj:wander/animations/gangnamstyle/zzz/frames/248_locator_chest
$execute as $(sack) positioned ^0 ^-0.438 ^0 rotated ~0 ~0 run function aj:wander/animations/gangnamstyle/zzz/frames/248_locator_sack