# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute positioned ^0 ^0 ^0 rotated ~90 ~0 run function aj:wander/animations/invisible/zzz/frames/2_locator_soup
$execute as $(lefthand) positioned ^0 ^0 ^-0 rotated ~0 ~0 run function aj:wander/animations/invisible/zzz/frames/2_locator_lefthand
$execute as $(sword) positioned ^-0 ^0 ^0 rotated ~0 ~0 run function aj:wander/animations/invisible/zzz/frames/2_locator_sword
$execute as $(righthand) positioned ^-0 ^0 ^-0 rotated ~0 ~0 run function aj:wander/animations/invisible/zzz/frames/2_locator_righthand
$execute as $(chest) positioned ^-0 ^0 ^0 rotated ~0 ~0 run function aj:wander/animations/invisible/zzz/frames/2_locator_chest
$execute as $(sack) positioned ^-0.062 ^-1.562 ^-0 rotated ~0 ~0 run function aj:wander/animations/invisible/zzz/frames/2_locator_sack