# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:wander/animations/sneak_idle/zzz/apply_frame {frame: 72}
scoreboard players add @s aj.sneak_idle.frame 1