# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp uuid set from entity @s data.locators.lefthand.uuid
function animated_java:wander/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.righthand.uuid
function animated_java:wander/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.chest.uuid
function animated_java:wander/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.sack.uuid
function animated_java:wander/zzz/execute with storage aj:temp