# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players remove @s aj.tween_duration 1
execute if score @s aj.tween_duration matches 1.. run return 1
execute if score @s aj.tween_duration matches 0 on passengers run function animated_java:wander/animations/gangnamstyle/zzz/zzz/0 with entity @s data.uuids_by_name
execute if score @s aj.gangnamstyle.frame matches -1 run function animated_java:wander/animations/gangnamstyle/zzz/function_keyframe_loop_patch
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.gangnamstyle.frame
function animated_java:wander/animations/gangnamstyle/zzz/apply_frame with storage animated_java:temp args
execute if score @s aj.gangnamstyle.frame matches 246.. run return run scoreboard players set @s aj.gangnamstyle.frame -1
scoreboard players add @s aj.gangnamstyle.frame 1