# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute positioned ^0.437 ^2.162 ^3.073 rotated ~37.97 ~62.257 run function aj:wander/animations/sneak_walk/zzz/frames/19_locator_soup
$execute as $(lefthand) positioned ^0.626 ^2.146 ^3.098 rotated ~94.082 ~-16.345 run function aj:wander/animations/sneak_walk/zzz/frames/19_locator_lefthand
$execute as $(sword) positioned ^-4.409 ^1.54 ^0.623 rotated ~56.28 ~6.823 run function aj:wander/animations/sneak_walk/zzz/frames/19_locator_sword
$execute as $(righthand) positioned ^-1.364 ^1.978 ^-1.409 rotated ~56.28 ~6.823 run function aj:wander/animations/sneak_walk/zzz/frames/19_locator_righthand
$execute as $(chest) positioned ^-0.371 ^1.774 ^-0.238 rotated ~70.285 ~74.281 run function aj:wander/animations/sneak_walk/zzz/frames/19_locator_chest
$execute as $(sack) positioned ^-0.062 ^-1.562 ^-0 rotated ~0 ~0 run function aj:wander/animations/sneak_walk/zzz/frames/19_locator_sack