# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.5146f,0.2291f,0.8263f,-0.3062f,-0.2914f,0.8595f,-0.4199f,2.5625f,-0.8064f,-0.4569f,-0.3755f,0.1125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,2.375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0f,0f,0f,0.0116f,0f,0f,0f,1.9324f,0f,0f,0f,0.1563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.9914f,-0.1305f,0f,-0.3125f,-0.1305f,0.9914f,0f,2f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.9914f,-0.1305f,0f,0.375f,-0.1305f,0.9914f,0f,2f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9914f,0.13f,0.0114f,-0.2562f,0.1305f,0.9877f,0.0864f,2.1875f,0f,0.0872f,-0.9962f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9914f,-0.13f,-0.0114f,0.3063f,-0.1305f,0.9877f,0.0864f,2.1875f,0f,0.0872f,-0.9962f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.4813f,0f,0f,-1f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1f,0f,0f,-0.1312f,0f,1f,0f,1.5625f,0f,0f,-1f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1f,0f,0f,0.1813f,0f,1f,0f,1.3125f,0f,0f,-1f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":-0.0026734808206842486,"py":2.040789435068766,"pz":0.12499999999999999,"ry":0,"rx":8.827812596100317e-32},"hitbox":{"px":0,"py":0.6875,"pz":0,"ry":0,"rx":0}}}