# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(lid) run function aj:wander_chest/variants/default/zzz/apply_to_node_lid
$execute as $(base) run function aj:wander_chest/variants/default/zzz/apply_to_node_base
$execute as $(freedom) run function aj:wander_chest/variants/default/zzz/apply_to_node_freedom