# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
summon minecraft:item_display ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.wander.locator', 'aj.wander.locator']}
execute as @e[type=minecraft:item_display,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:wander/zzz/2
data modify entity @s data.locators.lefthand.uuid set from storage aj:uuid main.out
summon minecraft:item_display ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.wander.locator', 'aj.wander.locator']}
execute as @e[type=minecraft:item_display,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:wander/zzz/3
data modify entity @s data.locators.righthand.uuid set from storage aj:uuid main.out
summon minecraft:item_display ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.wander.locator', 'aj.wander.locator']}
execute as @e[type=minecraft:item_display,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:wander/zzz/4
data modify entity @s data.locators.chest.uuid set from storage aj:uuid main.out
summon minecraft:item_display ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.wander.locator', 'aj.wander.locator']}
execute as @e[type=minecraft:item_display,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:wander/zzz/5
data modify entity @s data.locators.sack.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.nose] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_nose set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.glowing_eye] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_glowing_eye set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.leftthumb2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leftthumb2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.leftthumb] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leftthumb set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.leftpointerfinger] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leftpointerfinger set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.leftmidfinger] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leftmidfinger set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.leftringfinger] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leftringfinger set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.invisibility] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_invisibility set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.swiftness] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_swiftness set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.suspicious_stew] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_suspicious_stew set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.log] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_log set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.planks] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_planks set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.lefthand1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_lefthand1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.leftforearm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leftforearm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.leftelbow] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leftelbow set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.leftarm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leftarm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.rightthumb2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rightthumb2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.rightthumb] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rightthumb set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.rightpointerfinger] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rightpointerfinger set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.rightmidfinger] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rightmidfinger set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.rightringfinger] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rightringfinger set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.hugeasssword] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_hugeasssword set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.ice] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ice set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.righthand1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_righthand1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.rightforearm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rightforearm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.rightelbow] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rightelbow set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.rightarm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rightarm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.chest1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_chest1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.chest1lid] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_chest1lid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.chest2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_chest2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.chest1lid3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_chest1lid3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.chest3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_chest3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.hugeasssword2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_hugeasssword2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.belt] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_belt set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.torn_part] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_torn_part set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.lowerbody] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_lowerbody set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.leftfoot] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leftfoot set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.leftlowerleg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leftlowerleg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.leftleg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leftleg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.rightfoot] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rightfoot set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.rightlowerleg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rightlowerleg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.rightleg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rightleg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.sack_top] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_sack_top set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wander.node.sack_main] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_sack_main set from storage aj:uuid main.out