# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute positioned ^1.015 ^1.115 ^2.436 rotated ~80.987 ~59.785 run function aj:wander/animations/sneak_idle/zzz/frames/73_locator_soup
$execute as $(lefthand) positioned ^1.169 ^1.054 ^2.34 rotated ~47.276 ~-25.848 run function aj:wander/animations/sneak_idle/zzz/frames/73_locator_lefthand
$execute as $(sword) positioned ^-4.409 ^1.509 ^0.623 rotated ~56.28 ~6.823 run function aj:wander/animations/sneak_idle/zzz/frames/73_locator_sword
$execute as $(righthand) positioned ^-1.364 ^1.947 ^-1.409 rotated ~56.28 ~6.823 run function aj:wander/animations/sneak_idle/zzz/frames/73_locator_righthand
$execute as $(chest) positioned ^-0.371 ^1.743 ^-0.238 rotated ~70.285 ~74.281 run function aj:wander/animations/sneak_idle/zzz/frames/73_locator_chest
$execute as $(sack) positioned ^-0.062 ^-1.562 ^-0 rotated ~0 ~0 run function aj:wander/animations/sneak_idle/zzz/frames/73_locator_sack