# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp entry.data.locators.lefthand
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp entry.data.locators.sword
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp entry.data.locators.righthand
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp entry.data.locators.chest
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp entry.data.locators.sack
execute unless data storage animated_java:temp {entry:{data:{rig_hash: '661f740e1e90f6e946d52d6d812f489ff58d3a896b955b0de9870e73c7b221d9'}}} run function animated_java:global/remove/outdated_rig
function aj:wander/remove/this/zzz/0 with storage animated_java:temp entry.data.uuids_by_name
function animated_java:global/remove/entity_stack