# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp entry.data.locators.soup merge value { px: 0.844, py: 1.963, pz: 0.062, ry: 90, rx: 0 }
execute at @s run function aj:wander/zzz/set_default_pose/as_locator_lefthand with storage animated_java:temp entry.data.locators.lefthand
execute at @s run function aj:wander/zzz/set_default_pose/as_locator_sword with storage animated_java:temp entry.data.locators.sword
execute at @s run function aj:wander/zzz/set_default_pose/as_locator_righthand with storage animated_java:temp entry.data.locators.righthand
execute at @s run function aj:wander/zzz/set_default_pose/as_locator_chest with storage animated_java:temp entry.data.locators.chest
execute at @s run function aj:wander/zzz/set_default_pose/as_locator_sack with storage animated_java:temp entry.data.locators.sack