# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.trees.frame dummy
scoreboard objectives add aj.open_chest.frame dummy
scoreboard objectives add aj.close_chest.frame dummy