# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(blast_off1) run function animated_java:wander/variants/blast_off/zzz/apply_to_node_blast_off1
$execute as $(blast_off2) run function animated_java:wander/variants/blast_off/zzz/apply_to_node_blast_off2