# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.3396f,0.2271f,0.9127f,0.0014f,-0.1106f,0.954f,-0.2785f,2.4789f,-0.934f,-0.1956f,-0.2989f,0.37f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.981f,-0.0891f,0.1726f,0.338f,-0.0454f,0.9692f,0.2421f,2.3383f,-0.1889f,0.2296f,-0.9548f,0.2773f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0f,0f,0f,0.347f,0f,0f,0f,1.819f,0f,0f,0f,0.3108f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.9791f,-0.0512f,0.197f,0.0663f,-0.0018f,0.97f,0.2431f,1.9625f,-0.2035f,0.2377f,-0.9498f,0.1248f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.9791f,-0.0512f,0.197f,0.7375f,-0.0018f,0.97f,0.2431f,1.9896f,-0.2035f,0.2377f,-0.9498f,0.271f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9796f,0.0218f,0.1997f,0.1291f,0.0875f,0.9412f,0.3264f,2.1769f,-0.1808f,0.3372f,-0.9239f,0.0611f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9564f,-0.2321f,0.1774f,0.6783f,-0.1655f,0.9309f,0.3255f,2.199f,-0.2407f,0.2819f,-0.9287f,0.1807f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-0.9764f,-0.0891f,0.197f,0.4237f,-0.0393f,0.9692f,0.2431f,1.4797f,-0.2126f,0.2296f,-0.9498f,0.0424f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.9764f,-0.0939f,0.1947f,0.2712f,-0.0393f,0.9628f,0.2672f,1.5457f,-0.2126f,0.2532f,-0.9438f,0.1132f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.9764f,-0.0919f,0.1957f,0.6011f,-0.0393f,0.9655f,0.2573f,1.3143f,-0.2126f,0.2435f,-0.9463f,0.1109f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.348","py":"1.933","pz":"0.307","ry":"11.717","rx":"14.071"},"hitbox":{"px":"0.465","py":"0.688","pz":"0","ry":"12.051","rx":"5.875"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args