# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.4538f,0.2479f,0.8559f,-0.1643f,-0.281f,0.8717f,-0.4015f,2.5556f,-0.8457f,-0.4227f,-0.3259f,0.1238f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9975f,-0.014f,0.0688f,0.1515f,-0.0126f,0.9997f,0.0209f,2.3744f,-0.069f,0.02f,-0.9974f,0.029f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0f,0f,0f,0.1348f,0f,0f,0f,1.855f,0f,0f,0f,0.1736f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.9935f,0.0893f,0.0704f,-0.1549f,0.0909f,0.9956f,0.0209f,1.9956f,-0.0682f,0.0272f,-0.9973f,-0.0006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.9935f,0.0893f,0.0704f,0.5308f,0.0909f,0.9956f,0.0209f,2.0042f,-0.0682f,0.0272f,-0.9973f,0.048f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9907f,0.1097f,0.0803f,-0.0926f,0.118f,0.9872f,0.1074f,2.1863f,-0.0675f,0.1159f,-0.991f,-0.1175f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9871f,-0.1497f,0.0576f,0.4684f,-0.143f,0.9839f,0.1071f,2.1934f,-0.0727f,0.0975f,-0.9926f,-0.0778f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-0.9974f,-0.014f,0.0704f,0.1663f,-0.0126f,0.9997f,0.0209f,1.4816f,-0.0707f,0.02f,-0.9973f,-0.0201f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.9974f,-0.0144f,0.0703f,0.0277f,-0.0126f,0.9996f,0.0261f,1.5597f,-0.0707f,0.0251f,-0.9972f,0.0653f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.9974f,-0.0144f,0.0703f,0.3429f,-0.0126f,0.9996f,0.0265f,1.3138f,-0.0707f,0.0255f,-0.9972f,0.0815f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0.147","py":"1.965","pz":"0.145","ry":"4.038","rx":"1.2"},"hitbox":{"px":"0.175","py":"0.688","pz":"0","ry":"4.042","rx":"0.856"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args