# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mas) {transformation: [-0.2629f,0.2124f,0.9412f,0.0848f,-0.0219f,0.9739f,-0.2259f,2.4269f,-0.9646f,-0.08f,-0.2514f,0.4641f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9616f,-0.136f,0.2384f,0.4316f,-0.0478f,0.9383f,0.3425f,2.3042f,-0.2703f,0.3179f,-0.9088f,0.385f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0f,0f,0f,0.4582f,0f,0f,0f,1.7847f,0f,0f,0f,0.3682f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.9672f,-0.0986f,0.2339f,0.1817f,-0.013f,0.9395f,0.3423f,1.9369f,-0.2535f,0.328f,-0.91f,0.1827f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.9672f,-0.0986f,0.2339f,0.8436f,-0.013f,0.9395f,0.3423f,1.9708f,-0.2535f,0.328f,-0.91f,0.3656f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_right_arm) {transformation: [-0.9722f,-0.0295f,0.2322f,0.2396f,0.0735f,0.9033f,0.4226f,2.1583f,-0.2223f,0.4279f,-0.8761f,0.1435f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green_left_arm) {transformation: [-0.9367f,-0.2799f,0.2103f,0.7812f,-0.1714f,0.8905f,0.4215f,2.1861f,-0.3053f,0.3587f,-0.8821f,0.2931f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-0.9627f,-0.136f,0.2339f,0.5604f,-0.0494f,0.9383f,0.3423f,1.4762f,-0.266f,0.3179f,-0.91f,0.0724f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.9627f,-0.1132f,0.2457f,0.403f,-0.0494f,0.9665f,0.2519f,1.5362f,-0.266f,0.2304f,-0.936f,0.1376f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.9627f,-0.119f,0.243f,0.7335f,-0.0494f,0.9603f,0.2747f,1.3093f,-0.266f,0.2525f,-0.9303f,0.1586f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0.455","py":"1.898","pz":"0.376","ry":"14.415","rx":"20.015"},"hitbox":{"px":"0.621","py":"0.688","pz":"0","ry":"15.026","rx":"8.454"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args