# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.wander.animation.sword_throw_backup.playing
scoreboard players set @s aj.sword_throw_backup.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:wander/animations/sword_throw_backup/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only