# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lid) {transformation: [-1f,0f,0f,0f,0f,0.1999f,-0.9798f,1.1606f,0f,-0.9798f,-0.1999f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(base) {transformation: [-1f,0f,0f,-0.5f,0f,-1f,0f,0.5981f,0f,0f,1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(freedom) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.5981f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":0,"py":0.6605598543468366,"pz":0,"ry":0,"rx":0},"hitbox":{"px":0,"py":0.4730598543468366,"pz":0,"ry":0,"rx":0}}}