# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lid) {transformation: [-1f,0f,0f,0f,0f,0.6221f,-0.783f,1.1863f,0f,-0.783f,-0.6221f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(base) {transformation: [-1f,0f,0f,-0.5f,0f,-1f,0f,0.6238f,0f,0f,1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(freedom) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.6238f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":0,"py":0.6863336367774238,"pz":0,"ry":0,"rx":0},"hitbox":{"px":0,"py":0.49883363677742376,"pz":0,"ry":0,"rx":0}}}