# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute positioned ^1.429 ^0.05 ^2.405 rotated ~58.495 ~39.559 run function aj:wander/animations/swim/zzz/frames/19_locator_soup
$execute as $(lefthand) positioned ^1.579 ^-0.067 ^2.388 rotated ~77.216 ~-48.905 run function aj:wander/animations/swim/zzz/frames/19_locator_lefthand
$execute as $(sword) positioned ^-1.461 ^-0.097 ^2.342 rotated ~282.784 ~-48.905 run function aj:wander/animations/swim/zzz/frames/19_locator_sword
$execute as $(righthand) positioned ^-1.514 ^-0.03 ^2.341 rotated ~282.784 ~-48.905 run function aj:wander/animations/swim/zzz/frames/19_locator_righthand
$execute as $(chest) positioned ^-0.375 ^-0.824 ^0.491 rotated ~180 ~85 run function aj:wander/animations/swim/zzz/frames/19_locator_chest
$execute as $(sack) positioned ^-0.062 ^-1.562 ^-0 rotated ~0 ~0 run function aj:wander/animations/swim/zzz/frames/19_locator_sack