# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute at @s on passengers run function animated_java:fine_print/zzz/zzz/set_default_pose/as_locator_locator with entity @s data.locators.locator
execute at @s on passengers run function animated_java:fine_print/zzz/zzz/set_default_pose/as_locator_hitbox with entity @s data.locators.hitbox