# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score bad_omen wander.data matches 1 run function wander:ai/slaughter/set_variants