# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute positioned ^0.537 ^2.721 ^-0.192 rotated ~131.145 ~-0.578 run function aj:wander/animations/macarena/zzz/frames/165_locator_soup
$execute as $(lefthand) positioned ^0.631 ^2.567 ^-0.254 rotated ~40.525 ~-46.998 run function aj:wander/animations/macarena/zzz/frames/165_locator_lefthand
$execute as $(sword) positioned ^2.231 ^4.165 ^0.987 rotated ~298.065 ~-22.388 run function aj:wander/animations/macarena/zzz/frames/165_locator_sword
$execute as $(righthand) positioned ^-0.778 ^2.761 ^-0.617 rotated ~298.065 ~-22.388 run function aj:wander/animations/macarena/zzz/frames/165_locator_righthand
$execute as $(chest) positioned ^-0.471 ^2.674 ^0.068 rotated ~15.926 ~8.336 run function aj:wander/animations/macarena/zzz/frames/165_locator_chest
$execute as $(sack) positioned ^-0.062 ^-1.562 ^-0 rotated ~0 ~0 run function aj:wander/animations/macarena/zzz/frames/165_locator_sack