# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:wander/animations/angry_run_sword/zzz/apply_frame {frame: 12}
scoreboard players add @s aj.angry_run_sword.frame 1