# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lid) {transformation: [-0.996f,0f,0.089f,0.0389f,0f,1f,0f,1.2015f,-0.089f,0f,-0.996f,-0.4358f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(base) {transformation: [-0.996f,0f,-0.089f,-0.4535f,0f,-1f,0f,0.639f,-0.089f,0f,0.996f,-0.5425f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(freedom) {transformation: [-0.996f,0f,0.089f,0f,0f,1f,0f,0.639f,-0.089f,0f,-0.996f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0","py":"0.701","pz":"0","ry":"5.106","rx":"0"},"hitbox":{"px":"0","py":"0.514","pz":"0","ry":"5.106","rx":"0"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args