# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lid) {transformation: [-0.9973f,0f,0.0737f,0.0323f,0f,1f,0f,1.1646f,-0.0737f,0f,-0.9973f,-0.4363f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(base) {transformation: [-0.9973f,0f,-0.0737f,-0.4618f,0f,-1f,0f,0.6021f,-0.0737f,0f,0.9973f,-0.5355f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(freedom) {transformation: [-0.9973f,0f,0.0737f,0f,0f,1f,0f,0.6021f,-0.0737f,0f,-0.9973f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0","py":"0.665","pz":"0","ry":"4.227","rx":"0"},"hitbox":{"px":"0","py":"0.477","pz":"0","ry":"4.227","rx":"0"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args