# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lid) {transformation: [-0.9983f,0f,0.0581f,0.0254f,0f,1f,0f,1.1482f,-0.0581f,0f,-0.9983f,-0.4368f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(base) {transformation: [-0.9983f,0f,-0.0581f,-0.4701f,0f,-1f,0f,0.5857f,-0.0581f,0f,0.9983f,-0.5282f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(freedom) {transformation: [-0.9983f,0f,0.0581f,0f,0f,1f,0f,0.5857f,-0.0581f,0f,-0.9983f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0","py":"0.648","pz":"0","ry":"3.332","rx":"0"},"hitbox":{"px":"0","py":"0.461","pz":"0","ry":"3.332","rx":"0"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args