# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lid) {transformation: [-0.9986f,0f,0.0536f,0.0234f,0f,1f,0f,1.1445f,-0.0536f,0f,-0.9986f,-0.4369f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(base) {transformation: [-0.9986f,0f,-0.0536f,-0.4725f,0f,-1f,0f,0.582f,-0.0536f,0f,0.9986f,-0.5261f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(freedom) {transformation: [-0.9986f,0f,0.0536f,0f,0f,1f,0f,0.582f,-0.0536f,0f,-0.9986f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0","py":"0.645","pz":"0","ry":"3.071","rx":"0"},"hitbox":{"px":"0","py":"0.457","pz":"0","ry":"3.071","rx":"0"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args