# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lid) {transformation: [-0.9992f,0f,-0.0388f,-0.017f,0f,1f,0f,1.1351f,0.0388f,0f,-0.9992f,-0.4372f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(base) {transformation: [-0.9992f,0f,0.0388f,-0.519f,0f,-1f,0f,0.5726f,0.0388f,0f,0.9992f,-0.4802f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(freedom) {transformation: [-0.9992f,0f,-0.0388f,0f,0f,1f,0f,0.5726f,0.0388f,0f,-0.9992f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0","py":"0.635","pz":"0","ry":"357.778","rx":"0"},"hitbox":{"px":"0","py":"0.448","pz":"0","ry":"357.778","rx":"0"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args