# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lid) {transformation: [-0.999f,0f,-0.0439f,-0.0192f,0f,1f,0f,1.138f,0.0439f,0f,-0.999f,-0.4371f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(base) {transformation: [-0.999f,0f,0.0439f,-0.5215f,0f,-1f,0f,0.5755f,0.0439f,0f,0.999f,-0.4776f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(freedom) {transformation: [-0.999f,0f,-0.0439f,0f,0f,1f,0f,0.5755f,0.0439f,0f,-0.999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0","py":"0.638","pz":"0","ry":"357.485","rx":"0"},"hitbox":{"px":"0","py":"0.451","pz":"0","ry":"357.485","rx":"0"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args