# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lid) {transformation: [-0.9996f,0f,0.0296f,0.013f,0f,1f,0f,1.2446f,-0.0296f,0f,-0.9996f,-0.4373f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(base) {transformation: [-0.9996f,0f,-0.0296f,-0.485f,0f,-1f,0f,0.6821f,-0.0296f,0f,0.9996f,-0.5146f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(freedom) {transformation: [-0.9996f,0f,0.0296f,0f,0f,1f,0f,0.6821f,-0.0296f,0f,-0.9996f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0","py":"0.745","pz":"0","ry":"1.698","rx":"0"},"hitbox":{"px":"0","py":"0.557","pz":"0","ry":"1.698","rx":"0"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args