# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lid) {transformation: [-0.9991f,0f,-0.0434f,-0.019f,0f,1f,0f,1.2399f,0.0434f,0f,-0.9991f,-0.4371f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(base) {transformation: [-0.9991f,0f,0.0434f,-0.5212f,0f,-1f,0f,0.6774f,0.0434f,0f,0.9991f,-0.4779f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(freedom) {transformation: [-0.9991f,0f,-0.0434f,0f,0f,1f,0f,0.6774f,0.0434f,0f,-0.9991f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":"0","py":"0.74","pz":"0","ry":"357.515","rx":"0"},"hitbox":{"px":"0","py":"0.552","pz":"0","ry":"357.515","rx":"0"}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args