# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lid) {transformation: [-0.9997f,0f,-0.023f,-0.01f,0f,1f,0f,1.2465f,0.023f,0f,-0.9997f,-0.4374f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(base) {transformation: [-0.9997f,0f,0.023f,-0.5113f,0f,-1f,0f,0.684f,0.023f,0f,0.9997f,-0.4884f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(freedom) {transformation: [-0.9997f,0f,-0.023f,0f,0f,1f,0f,0.684f,0.023f,0f,-0.9997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":"0","py":"0.747","pz":"0","ry":"358.685","rx":"0"},"hitbox":{"px":"0","py":"0.559","pz":"0","ry":"358.685","rx":"0"}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args