# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute positioned ^0 ^0.75 ^0 rotated ~0 ~0 run function aj:wander_chest/animations/idle/zzz/frames/81_locator_locator
$execute as $(hitbox) positioned ^0 ^0.563 ^0 rotated ~0 ~0 run function aj:wander_chest/animations/idle/zzz/frames/81_locator_hitbox